// @ts-nocheck
import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
import type { Session, User } from '@supabase/supabase-js';
import { supabase } from './supabase';
import type { Profile } from './supabase';

type AuthContextValue = { session:Session|null; user:User|null; profile:Profile|null; loading:boolean; sessionExpired:boolean; signIn:(email:string,password:string)=>Promise<{error:string|null}>; signUp:(email:string,password:string,fullName:string,meta?:Record<string,any>)=>Promise<{error:string|null}>; signInWithProvider:(provider:'google'|'github'|'gitlab'|'azure')=>Promise<{error:string|null}>; signOut:()=>Promise<void>; refreshProfile:()=>Promise<void>; refreshSession:()=>Promise<boolean>; resetPassword:(email:string)=>Promise<{error:string|null}>; updatePassword:(newPassword:string)=>Promise<{error:string|null}>; resendVerification:(email:string)=>Promise<{error:string|null}> };
const AuthContext=createContext<AuthContextValue|undefined>(undefined);
async function ensureWorkspace(accountName?:string){const{data,error}=await supabase.rpc('bootstrap_user_workspace',{p_name:accountName||null});if(error)throw error;const row=Array.isArray(data)?data[0]:data;const id=row?.workspace_id;if(!id)throw new Error('Workspace bootstrap did not return a workspace');localStorage.setItem('sandbox.activeWs',id);localStorage.setItem('lh.activeWorkspace',id);return id}
export function AuthProvider({children}:{children:ReactNode}){const[session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[sessionExpired,setSessionExpired]=useState(false);
 async function loadProfile(uid:string){const{data,error}=await supabase.from('profiles').select('*').eq('id',uid).maybeSingle();if(error)throw error;setProfile(data as Profile|null)}
 async function hydrate(s:Session|null){setSession(s);if(!s?.user){setProfile(null);setLoading(false);return}try{await ensureWorkspace(localStorage.getItem('lh.pendingAccount')||undefined);await loadProfile(s.user.id);localStorage.removeItem('lh.pendingAccount');localStorage.removeItem('lh.pendingCompanySize');setSessionExpired(false)}finally{setLoading(false)}}
 const refreshSession=async()=>{const{data,error}=await supabase.auth.refreshSession();if(error||!data.session){setSessionExpired(true);setSession(null);setProfile(null);return false}setSession(data.session);setSessionExpired(false);return true};
 useEffect(()=>{let mounted=true;supabase.auth.getSession().then(({data})=>{if(mounted)void hydrate(data.session)});const{data:sub}=supabase.auth.onAuthStateChange((event,s)=>{if(!mounted)return;if(event==='TOKEN_REFRESHED'){setSession(s);setSessionExpired(false);return}if(event==='SIGNED_OUT'){setSession(null);setProfile(null);setSessionExpired(true);setLoading(false);return}void hydrate(s)});const timer=window.setInterval(async()=>{if(!mounted)return;const{data}=await supabase.auth.getSession();const s=data.session;if(!s)return;const expires=(s.expires_at||0)*1000;if(expires-Date.now()<5*60*1000)await refreshSession()},4*60*1000);const online=()=>{void refreshSession()};window.addEventListener('online',online);return()=>{mounted=false;window.clearInterval(timer);window.removeEventListener('online',online);sub.subscription.unsubscribe()}},[]);
 const signIn=async(email:string,password:string)=>{const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return{error:error.message};try{await ensureWorkspace();if(data.user)await loadProfile(data.user.id);setSessionExpired(false)}catch(e){return{error:e instanceof Error?e.message:'Account initialization failed'}}return{error:null}};
 const signUp=async(email:string,password:string,fullName:string,meta?:Record<string,any>)=>{if(meta?.account_name)localStorage.setItem('lh.pendingAccount',meta.account_name);if(meta?.company_size)localStorage.setItem('lh.pendingCompanySize',meta.company_size);const{data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName,...(meta||{})}}});if(error)return{error:error.message};if(data.session){try{await ensureWorkspace(meta?.account_name);if(data.user)await loadProfile(data.user.id)}catch(e){return{error:e instanceof Error?e.message:'Account initialization failed'}}return{error:null}}if(data.user)return{error:'EMAIL_CONFIRMATION_REQUIRED'};return{error:'Unable to create account'}};
 const signInWithProvider=async(provider:'google'|'github'|'gitlab'|'azure')=>{const{error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:`${window.location.origin}/dashboard`}});return{error:error?.message??null}};
 const signOut=async()=>{const{error}=await supabase.auth.signOut();if(error)throw error;setSession(null);setProfile(null);setSessionExpired(false);localStorage.removeItem('sandbox.activeWs');localStorage.removeItem('lh.activeWorkspace')};
 const refreshProfile=async()=>{if(session?.user)await loadProfile(session.user.id)};const resetPassword=async(email:string)=>{const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});return{error:error?.message??null}};const updatePassword=async(newPassword:string)=>{const{error}=await supabase.auth.updateUser({password:newPassword});return{error:error?.message??null}};const resendVerification=async(email:string)=>{const{error}=await supabase.auth.resend({type:'signup',email});return{error:error?.message??null}};
 return <AuthContext.Provider value={{session,user:session?.user??null,profile,loading,sessionExpired,signIn,signUp,signInWithProvider,signOut,refreshProfile,refreshSession,resetPassword,updatePassword,resendVerification}}>{children}</AuthContext.Provider>}
export function useAuth(){const ctx=useContext(AuthContext);if(!ctx)throw new Error('useAuth must be used within AuthProvider');return ctx}
