import Anthropic from "npm:@anthropic-ai/sdk@0.27.3";
import { createClient } from "npm:@supabase/supabase-js@2";
const origin=Deno.env.get('APP_ORIGIN')||'https://sandbox-ai-app-eight.vercel.app';
const cors={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Client-Info, Apikey'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const SYSTEM=`You are the LytHouse evidence intelligence engine. Accuracy is more important than sounding helpful. You receive repository facts and findings produced by deterministic analysis. Never invent a finding, CVE, file, line, dependency, architecture component, metric, exploit, cost number or compliance claim. Separate VERIFIED facts from INFERENCES. An inference must cite the verified finding IDs that support it and include confidence 0-100. If evidence is insufficient, explicitly say so. Correlate verified findings when their combination creates a larger reliability, security, deployment, architecture, scalability or cost concern. Explain why each priority matters to THIS application, not with generic security prose. The deterministic verdict remains authoritative. Return strict JSON only.`;
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{
 const auth=req.headers.get('Authorization')||'',token=auth.replace(/^Bearer\s+/i,'');if(!token)return json({error:'Authentication required'},401);
 const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const{data:{user}}=await db.auth.getUser(token);if(!user)return json({error:'Invalid session'},401);
 const{validationId}=await req.json();if(!validationId)return json({error:'validationId required'},400);
 const{data:v}=await db.from('validations').select('id,workspace_id,project_id,risk_score,severity,summary,status,total_findings,critical_count,high_count,medium_count,low_count').eq('id',validationId).maybeSingle();if(!v)return json({error:'Validation not found'},404);
 const{data:m}=await db.from('workspace_members').select('id').eq('workspace_id',v.workspace_id).eq('user_id',user.id).maybeSingle();if(!m)return json({error:'Forbidden'},403);
 const{data:entitled}=await db.rpc('workspace_has_feature',{p_workspace:v.workspace_id,p_feature:'ai_analysis'});if(entitled===false)return json({error:'AI analysis is not included in this plan'},403);
 const{data:p}=await db.from('projects').select('id,name,description,git_url,git_branch,language,framework').eq('id',v.project_id).single();
 const{data:f}=await db.from('findings').select('id,severity,category,title,description,file_path,line,recommendation,confidence,status').eq('validation_id',validationId).limit(150);
 const{data:steps}=await db.from('validation_steps').select('key,name,status,detail').eq('validation_id',validationId).order('step_index');
 const key=Deno.env.get('ANTHROPIC_API_KEY');if(!key)return json({error:'AI service is not configured'},503);
 const evidence={project:p,validation:v,analysis_steps:steps||[],verified_findings:f||[]};
 const prompt=`Analyze the verified LytHouse evidence below. Return JSON with exactly these top-level keys:\nexecutive_summary: concise application-specific assessment;\nrelease_assessment: {decision,reason,confidence};\napplication_understanding: {observed_stack:[], observed_delivery:[], evidence_gaps:[]};\npriorities: array of {finding_ids:[],title,why_it_matters,release_impact,recommended_action,confidence};\ncorrelations: array of {finding_ids:[],insight,affected_domains:[],confidence};\nengineering_opportunities: array of {domain,observation,evidence_basis,action,confidence}; only include opportunities supported by evidence;\nconfidence_notes: array explaining evidence limits and what LytHouse could not verify.\nDo not manufacture cost savings, scalability limits or architecture. Mark unsupported areas as evidence gaps. Evidence:\n${JSON.stringify(evidence)}`;
 const client=new Anthropic({apiKey:key});const r=await client.messages.create({model:'claude-sonnet-4-6',max_tokens:3600,temperature:0,system:SYSTEM,messages:[{role:'user',content:prompt}]});
 const text=r.content.filter(x=>x.type==='text').map((x:any)=>x.text).join('');let review:any;try{review=JSON.parse(text.replace(/^```json\s*|\s*```$/g,''))}catch{return json({error:'AI returned invalid structured output'},502)}
 await db.from('ai_insights').insert({workspace_id:v.workspace_id,project_id:v.project_id,validation_id:v.id,type:'validation_review',title:'Evidence-grounded application intelligence',content:review,confidence:review?.release_assessment?.confidence??null,created_by:user.id});
 await db.from('usage_events').insert({workspace_id:v.workspace_id,user_id:user.id,project_id:v.project_id,event_type:'ai.validation_review',quantity:1,metadata:{validation_id:v.id,mode:'evidence_intelligence'}});
 return json({success:true,review});
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'AI review failed'},500)}});
