import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-Client-Info, Apikey, apikey","Access-Control-Max-Age":"86400"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const DOMAINS=['Code','Infrastructure','DevOps','QA','Cost','Dependencies','Vendor Intelligence'];
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);const auth=req.headers.get('Authorization')||'',token=auth.replace(/^Bearer\s+/i,'');try{const url=Deno.env.get('SUPABASE_URL')!,db=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const{data:{user}}=await db.auth.getUser(token);if(!user)return json({error:'Invalid or expired session'},401);const{projectId}=await req.json();if(!projectId)return json({error:'Project is required'},400);const{data:p}=await db.from('projects').select('id,workspace_id,git_url').eq('id',projectId).single();if(!p?.git_url)return json({error:'Connected repository required'},400);const{data:member}=await db.from('workspace_members').select('id').eq('workspace_id',p.workspace_id).eq('user_id',user.id).maybeSingle();if(!member)return json({error:'Forbidden'},403);
const{data:active}=await db.from('validations').select('id,status,created_at').eq('project_id',projectId).eq('trigger','intelligence').in('status',['pending','running']).order('created_at',{ascending:false}).limit(1).maybeSingle();let validation=active;if(!validation){const{data:v,error:ve}=await db.from('validations').insert({project_id:projectId,workspace_id:p.workspace_id,status:'pending',trigger:'intelligence',created_by:user.id}).select('id,status,created_at').single();if(ve)return json({error:ve.message},409);validation=v;}
let{data:run}=await db.from('analysis_runs').select('id').eq('validation_id',validation.id).maybeSingle();if(!run){const{data:r,error:re}=await db.from('analysis_runs').insert({workspace_id:p.workspace_id,project_id:projectId,validation_id:validation.id,mode:'smart',depth:'deep',domains:DOMAINS,status:'running',config:{source:'run_analysis',purpose:'application_intelligence',architecture:'control-plane',stages:{repository:'pending',ai:'pending'}},created_by:user.id}).select('id').single();if(re)return json({error:re.message},400);run=r;}else await db.from('analysis_runs').update({status:'running',completed_at:null}).eq('id',run.id);
const fail=async(message:string,status:number)=>{await db.from('validations').update({status:'failed',summary:message,completed_at:new Date().toISOString()}).eq('id',validation.id);await db.from('analysis_runs').update({status:'failed',completed_at:new Date().toISOString(),config:{source:'run_analysis',purpose:'application_intelligence',failed_stage:message}}).eq('id',run.id);return json({error:message,validationId:validation.id},status)};
const r=await fetch(`${url}/functions/v1/process-validation`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':auth,'apikey':Deno.env.get('SUPABASE_ANON_KEY')||''},body:JSON.stringify({validationId:validation.id})});const text=await r.text();let body:any={};try{body=text?JSON.parse(text):{}}catch{body={error:text||`Processor returned ${r.status}`}}if(!r.ok)return await fail(body.error||`Analysis processor returned ${r.status}`,r.status);
await db.from('analysis_runs').update({status:'running',completed_at:null,config:{source:'run_analysis',purpose:'application_intelligence',architecture:'control-plane',repository:body,stages:{repository:'completed',ai:'running'}}}).eq('id',run.id);
const ai=await fetch(`${url}/functions/v1/ai-validation-review`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':auth,'apikey':Deno.env.get('SUPABASE_ANON_KEY')||''},body:JSON.stringify({validationId:validation.id})});const aiText=await ai.text();let aiBody:any={};try{aiBody=aiText?JSON.parse(aiText):{}}catch{aiBody={error:aiText||`AI returned ${ai.status}`}};
if(!ai.ok){const aiMessage=String(aiBody.error||ai.status);const unavailable=/not configured|missing.*key|api key|service.*unavailable/i.test(aiMessage);if(!unavailable)return await fail(`AI intelligence failed: ${aiMessage}`,ai.status);const completedAt=new Date().toISOString();const config={source:'run_analysis',purpose:'application_intelligence',architecture:'control-plane',repository:body,partial:true,notice:'Deterministic repository analysis completed. AI enrichment is unavailable until the AI service is configured.',stages:{repository:'completed',ai:'not_configured'}};await db.from('analysis_runs').update({status:'completed',completed_at:completedAt,config}).eq('id',run.id);await db.from('validations').update({status:'completed',completed_at:completedAt,summary:`Analysis complete with deterministic evidence: ${body.filesScanned||0} files inspected, ${body.components||0} components discovered, ${body.apis||0} APIs discovered, ${body.findings||0} deterministic findings. AI enrichment is not configured.`}).eq('id',validation.id);return json({success:true,partial:true,validationId:validation.id,analysisRunId:run.id,repository:body,ai:{status:'not_configured',message:'Deterministic analysis completed; AI enrichment is not configured.'}});}
const{data:insight}=await db.from('ai_insights').select('id,content,confidence,created_at').eq('validation_id',validation.id).eq('type','validation_review').order('created_at',{ascending:false}).limit(1).maybeSingle();if(!insight)return await fail('AI intelligence completed without persisting an insight',500);
await db.from('analysis_runs').update({status:'completed',completed_at:new Date().toISOString(),config:{source:'run_analysis',purpose:'application_intelligence',architecture:'control-plane',repository:body,ai_insight_id:insight.id,stages:{repository:'completed',ai:'completed'}}).eq('id',run.id);await db.from('validations').update({status:'completed',summary:`Analysis complete: ${body.filesScanned||0} files inspected, ${body.components||0} components discovered, ${body.apis||0} APIs discovered, ${body.findings||0} deterministic findings, and AI cross-domain analysis persisted.`}).eq('id',validation.id);return json({success:true,validationId:validation.id,analysisRunId:run.id,repository:body,aiInsightId:insight.id,aiConfidence:insight.confidence});}catch(e){return json({error:e instanceof Error?e.message:'Analysis failed'},500)}});