import { useEffect, useState } from 'react';
import {
  supabase,
  type DeploymentPassport,
  type ValidationRun,
  type ServerEnvironment,
  type EnvironmentBlueprint,
  type Verdict,
} from '../../lib/supabase';
import { PageHeader, Spinner, EmptyState, Breadcrumb, SeverityBadge, timeAgo } from '../../lib/ui';
import { useRouter } from '../../lib/router';
import { FileCheck, Download, ArrowLeft, ShieldCheck, ShieldAlert, ShieldX, ChevronRight, Calendar, KeyRound } from 'lucide-react';

function VerdictIcon({ verdict }: { verdict: Verdict | null }) {
  if (!verdict) return <ShieldAlert size={20} className="text-gray-400" />;
  const m: Record<Verdict, { icon: typeof ShieldCheck; cls: string }> = {
    approved: { icon: ShieldCheck, cls: 'text-brand-600' },
    conditionally_approved: { icon: ShieldCheck, cls: 'text-blue-600' },
    rejected: { icon: ShieldX, cls: 'text-danger-600' },
    inconclusive: { icon: ShieldAlert, cls: 'text-gray-500' },
  };
  const v = m[verdict];
  const Icon = v.icon;
  return <Icon size={20} className={v.cls} />;
}

function downloadJSON(filename: string, data: unknown) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export function PassportPage({ runId }: { runId?: string }) {
  const { navigate } = useRouter();
  const [loading, setLoading] = useState(true);
  const [passport, setPassport] = useState<DeploymentPassport | null>(null);
  const [run, setRun] = useState<ValidationRun | null>(null);
  const [env, setEnv] = useState<ServerEnvironment | null>(null);
  const [blueprint, setBlueprint] = useState<EnvironmentBlueprint | null>(null);
  const [passports, setPassports] = useState<(DeploymentPassport & { env_name?: string })[]>([]);
  const [error, setError] = useState('');

  const wsId = () => localStorage.getItem('sandbox.activeWs');

  // Load single passport
  useEffect(() => {
    if (!runId) { loadList(); return; }
    setLoading(true);
    (async () => {
      const { data: ppData, error: ppErr } = await supabase
        .from('deployment_passports').select('*').eq('run_id', runId).order('created_at', { ascending: false }).limit(1).maybeSingle();
      if (ppErr) { setError(ppErr.message); setLoading(false); return; }
      if (!ppData) { setError('No passport found for this run'); setLoading(false); return; }
      const pp = ppData as DeploymentPassport;
      setPassport(pp);
      const { data: runData } = await supabase.from('validation_runs').select('*').eq('id', pp.run_id).single();
      if (runData) {
        const r = runData as ValidationRun;
        setRun(r);
        const [envRes, bpRes] = await Promise.all([
          supabase.from('server_environments').select('*').eq('id', r.environment_id).single(),
          supabase.from('environment_blueprints').select('*').eq('id', r.blueprint_id).single(),
        ]);
        if (envRes.data) setEnv(envRes.data as ServerEnvironment);
        if (bpRes.data) setBlueprint(bpRes.data as EnvironmentBlueprint);
      }
      setLoading(false);
    })();
  }, [runId]);

  const loadList = async () => {
    setLoading(true);
    const wid = wsId();
    if (!wid) { setLoading(false); return; }
    const { data, error } = await supabase
      .from('deployment_passports').select('*').eq('workspace_id', wid).order('created_at', { ascending: false });
    if (error) { setError(error.message); setLoading(false); return; }
    const items = (data ?? []) as DeploymentPassport[];
    // Fetch env names via runs
    const runIds = [...new Set(items.map(p => p.run_id))];
    const envMap: Record<string, string> = {};
    if (runIds.length) {
      const { data: runs } = await supabase.from('validation_runs').select('id,environment_id').in('id', runIds);
      const envIds = [...new Set((runs ?? []).map((r: any) => r.environment_id))];
      if (envIds.length) {
        const { data: envs } = await supabase.from('server_environments').select('id,name').in('id', envIds);
        (envs ?? []).forEach((e: any) => { envMap[e.id] = e.name; });
      }
      (runs ?? []).forEach((r: any) => {
        const pp = items.find(p => p.run_id === r.id);
        if (pp) (pp as any).env_name = envMap[r.environment_id] ?? 'Unknown';
      });
    }
    setPassports(items as (DeploymentPassport & { env_name?: string })[]);
    setLoading(false);
  };

  if (loading) return <div className="flex justify-center py-24"><Spinner size={28} /></div>;

  // ---- List view ----
  if (!runId) {
    return (
      <div>
        <PageHeader
          title="Deployment Passports"
          description="Cryptographically signed deployment authorization documents generated by validation runs."
          breadcrumb={<Breadcrumb items={[{ label: 'Server Validation', to: '/server-validation' }, { label: 'Passports' }]} />}
        />
        {error && <div className="mb-4 rounded-lg bg-red-50 border border-red-200 px-3 py-2 text-sm text-danger-600">{error}</div>}
        {passports.length === 0 ? (
          <EmptyState
            icon={<FileCheck size={22} />}
            title="No deployment passports yet"
            description="Passports are generated automatically when a validation run completes with a verdict."
            action={<button onClick={() => navigate('/server-validation')} className="btn-secondary"><ArrowLeft size={16} /> Back to environments</button>}
          />
        ) : (
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {passports.map(pp => (
              <button key={pp.id} onClick={() => navigate(`/server-validation/passports/${pp.run_id}`)} className="card group text-left transition-all hover:shadow-md hover:border-brand-300">
                <div className="flex items-start justify-between">
                  <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><FileCheck size={18} /></div>
                  <VerdictIcon verdict={pp.verdict} />
                </div>
                <h3 className="mt-3 text-sm font-semibold text-navy-900 group-hover:text-brand-700">{(pp as any).env_name ?? 'Unknown environment'}</h3>
                <p className="mt-1 text-xs text-gray-400">Blueprint v{pp.blueprint_version ?? '—'}</p>
                <div className="mt-3 flex items-center gap-2">
                  {pp.verdict && <span className="chip capitalize bg-gray-50 text-gray-600 border border-[#a1a1aa]">{pp.verdict.replace(/_/g, ' ')}</span>}
                  {pp.confidence_score !== null && <span className="chip bg-blue-50 text-blue-600 border border-blue-200">{pp.confidence_score}% conf</span>}
                </div>
                <div className="mt-3 flex items-center justify-between border-t border-gray-100 pt-3">
                  <span className="flex items-center gap-1 text-xs text-gray-400"><Calendar size={11} /> {timeAgo(pp.created_at)}</span>
                  <span className="flex items-center gap-0.5 text-sm font-medium text-brand-600 opacity-0 transition-opacity group-hover:opacity-100">View <ChevronRight size={14} /></span>
                </div>
              </button>
            ))}
          </div>
        )}
      </div>
    );
  }

  // ---- Single passport view ----
  if (error || !passport) return (
    <EmptyState
      icon={<FileCheck size={22} />}
      title="Passport not found"
      description={error || 'The requested deployment passport could not be located.'}
      action={<button onClick={() => navigate('/server-validation/passports')} className="btn-secondary"><ArrowLeft size={16} /> View all passports</button>}
    />
  );

  return (
    <div>
      <PageHeader
        title="Deployment Passport"
        description={env ? `For ${env.name}` : 'Signed deployment authorization document'}
        breadcrumb={
          <Breadcrumb items={[
            { label: 'Server Validation', to: '/server-validation' },
            { label: 'Passports', to: '/server-validation/passports' },
            { label: 'Document' },
          ]} />
        }
        actions={
          <button onClick={() => downloadJSON(`passport-${passport.id.slice(0, 8)}.json`, { passport, run, environment: env, blueprint })} className="btn-primary">
            <Download size={16} /> Download
          </button>
        }
      />

      {/* Passport document */}
      <div className="mx-auto max-w-3xl">
        <div className="card relative overflow-hidden">
          {/* Watermark */}
          <div className="pointer-events-none absolute -right-8 -top-8 opacity-[0.04]">
            <ShieldCheck size={200} />
          </div>

          {/* Header */}
          <div className="flex items-center justify-between border-b border-gray-100 pb-4">
            <div className="flex items-center gap-3">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><FileCheck size={24} /></div>
              <div>
                <h2 className="text-lg font-bold text-navy-900">Deployment Passport</h2>
                <p className="text-xs text-gray-400">ID: {passport.id}</p>
              </div>
            </div>
            <VerdictIcon verdict={passport.verdict} />
          </div>

          {/* Verdict & confidence */}
          <div className="mt-4 grid grid-cols-2 gap-4">
            <div className="rounded-lg bg-gray-50 p-3">
              <p className="text-xs font-medium uppercase tracking-wide text-gray-400">Verdict</p>
              <p className="mt-1 text-base font-bold capitalize text-navy-900">{passport.verdict?.replace(/_/g, ' ') ?? '—'}</p>
            </div>
            <div className="rounded-lg bg-gray-50 p-3">
              <p className="text-xs font-medium uppercase tracking-wide text-gray-400">Confidence Score</p>
              <p className="mt-1 text-base font-bold tabular-nums text-navy-900">{passport.confidence_score !== null ? `${passport.confidence_score}%` : '—'}</p>
            </div>
          </div>

          {/* Metadata */}
          <div className="mt-4 space-y-3">
            {env && (
              <div className="flex items-center justify-between border-b border-gray-50 py-2">
                <span className="text-sm text-gray-400">Environment</span>
                <button onClick={() => navigate(`/server-validation/${env.id}`)} className="text-sm font-medium text-brand-600 hover:underline">{env.name}</button>
              </div>
            )}
            {blueprint && (
              <div className="flex items-center justify-between border-b border-gray-50 py-2">
                <span className="text-sm text-gray-400">Blueprint Version</span>
                <span className="text-sm font-medium text-navy-900">v{blueprint.version}</span>
              </div>
            )}
            <div className="flex items-center justify-between border-b border-gray-50 py-2">
              <span className="text-sm text-gray-400">Capture Method</span>
              <span className="text-sm font-medium capitalize text-navy-900">{blueprint?.capture_method ?? passport.blueprint_version ?? '—'}</span>
            </div>
            <div className="flex items-center justify-between border-b border-gray-50 py-2">
              <span className="text-sm text-gray-400">Issued</span>
              <span className="text-sm text-gray-600">{new Date(passport.created_at).toLocaleString()}</span>
            </div>
            {passport.expires_at && (
              <div className="flex items-center justify-between border-b border-gray-50 py-2">
                <span className="text-sm text-gray-400">Expires</span>
                <span className="text-sm text-gray-600">{new Date(passport.expires_at).toLocaleString()}</span>
              </div>
            )}
          </div>

          {/* Summary */}
          {passport.human_readable_summary && (
            <div className="mt-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-gray-400">Summary</p>
              <p className="mt-2 text-sm leading-relaxed text-gray-600">{passport.human_readable_summary}</p>
            </div>
          )}

          {/* AI summary from run */}
          {run?.ai_summary && (
            <div className="mt-4 rounded-lg bg-blue-50 border border-blue-200 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-blue-600">AI Assessment</p>
              <p className="mt-1 text-sm leading-relaxed text-blue-800">{run.ai_summary}</p>
            </div>
          )}

          {/* Signature */}
          {passport.signature && (
            <div className="mt-4 flex items-center gap-2 rounded-lg bg-gray-50 p-3">
              <KeyRound size={16} className="text-gray-400" />
              <div className="min-w-0 flex-1">
                <p className="text-xs font-medium uppercase tracking-wide text-gray-400">Signature</p>
                <p className="truncate font-mono text-xs text-gray-600">{passport.signature}</p>
              </div>
            </div>
          )}

          {/* Footer */}
          <div className="mt-6 flex items-center justify-between border-t border-gray-100 pt-4">
            <button onClick={() => navigate(`/server-validation/runs/${passport.run_id}`)} className="btn-ghost">
              <ArrowLeft size={14} /> View validation run
            </button>
            <p className="text-xs text-gray-400">Sandbox.ai · Server Validation</p>
          </div>
        </div>
      </div>
    </div>
  );
}
