import{createClient}from"jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":Deno.env.get("APP_ORIGIN")||"https://lythouse.ai","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, Apikey"};
type Entity={key:string;type:string;name:string;path:string|null;attributes:Record<string,unknown>;confidence:number};
function parseGit(u:string){const m=u.match(/github\.com[/:]([^/]+)\/(.+?)(?:\.git)?$/);return m?{owner:m[1],repo:m[2]}:null}
async function gh(url:string,token:string|null,raw=false){const h:Record<string,string>={Accept:raw?'application/vnd.github.raw+json':'application/vnd.github+json','User-Agent':'lythouse'};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(url,{headers:h});if(!r.ok)return null;return raw?r.text():r.json()}
function discover(path:string,c:string):Entity[]{const e:Entity[]=[];const add=(key:string,type:string,name:string,attrs:Record<string,unknown>={},confidence=80)=>e.push({key,type,name,path,attributes:attrs,confidence});
 if(/package\.json$/i.test(path)){try{const p=JSON.parse(c);add(`app:${path}`,'application',p.name||path,{runtime:'node',scripts:Object.keys(p.scripts||{})},95);const deps={...(p.dependencies||{}),...(p.devDependencies||{})};for(const n of Object.keys(deps)){if(/express|fastify|next|nest|koa/i.test(n))add(`service:${path}`,'service',p.name||path,{framework:n},85);if(/postgres|pg$|prisma|sequelize|mongoose|mysql|redis/i.test(n))add(`data:${n}`,'database',n,{dependency:n},70);if(/stripe|twilio|sendgrid|resend|openai|anthropic|sentry/i.test(n))add(`external:${n}`,'external_service',n,{dependency:n},75)}}catch{}}
 if(/Dockerfile$/i.test(path))add(`infra:${path}`,'infrastructure',`Container ${path}`,{kind:'docker'},95);
 if(/\.tf$/i.test(path)){add(`infra:${path}`,'infrastructure',path,{kind:'terraform'},95);for(const m of c.matchAll(/resource\s+"([^"]+)"\s+"([^"]+)"/g))add(`tf:${m[1]}:${m[2]}`,'infrastructure',m[2],{terraform_type:m[1]},92)}
 if(/\.github\/workflows\/.*\.ya?ml$/i.test(path))add(`pipeline:${path}`,'pipeline',path.split('/').pop()||path,{kind:'github_actions'},95);
 if(/\.(ya?ml)$/i.test(path)&&/kind:\s*(Deployment|StatefulSet|DaemonSet|Service|Ingress)/i.test(c)){for(const m of c.matchAll(/kind:\s*(Deployment|StatefulSet|DaemonSet|Service|Ingress)[\s\S]{0,300}?name:\s*([^\s#]+)/gi))add(`k8s:${m[1]}:${m[2]}`,'infrastructure',m[2],{kind:`kubernetes_${m[1].toLowerCase()}`},90)}
 if(/supabase\/migrations\/.*\.sql$/i.test(path)||/migrations?\/.*\.sql$/i.test(path))add(`database:migrations`,'database','Database migrations',{migration_path:path},85);
 for(const m of c.matchAll(/(?:fetch|axios\.(?:get|post|put|delete)|new URL)\s*\(?\s*["'`]https?:\/\/([^/"'`]+)/g))add(`external:${m[1]}`,'external_service',m[1],{host:m[1]},72);
 for(const m of c.matchAll(/(?:app|router)\.(get|post|put|patch|delete)\s*\(\s*["'`]([^"'`]+)/g))add(`api:${m[2]}`,'api',`${m[1].toUpperCase()} ${m[2]}`,{method:m[1].toUpperCase(),route:m[2]},88);
 return e}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});try{const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return out({error:'Unauthorized'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const caller=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:{user}}=await caller.auth.getUser();if(!user)return out({error:'Unauthorized'},401);const{projectId}=await req.json();if(!projectId)return out({error:'projectId required'},400);const db=createClient(url,service);const{data:p}=await db.from('projects').select('*').eq('id',projectId).single();if(!p)return out({error:'Project not found'},404);const{data:member}=await db.from('workspace_members').select('id').eq('workspace_id',p.workspace_id).eq('user_id',user.id).maybeSingle();if(!member)return out({error:'Forbidden'},403);const repo=parseGit(p.git_url||'');if(!repo)return out({error:'Invalid GitHub repository'},400);const branch=p.git_branch||'main',token=p.github_token||null;const tree=await gh(`https://api.github.com/repos/${repo.owner}/${repo.repo}/git/trees/${encodeURIComponent(branch)}?recursive=1`,token);if(!tree)return out({error:'Repository unavailable'},502);const paths=(tree.tree||[]).filter((x:any)=>x.type==='blob').map((x:any)=>x.path).filter((x:string)=>/package\.json$|Dockerfile$|\.tf$|\.github\/workflows\/.*\.ya?ml$|\.ya?ml$|migrations?\/.*\.sql$|\.(ts|tsx|js|jsx|py|go)$/i.test(x)).slice(0,500);const map=new Map<string,Entity>();for(const path of paths){const c=await gh(`https://api.github.com/repos/${repo.owner}/${repo.repo}/contents/${encodeURIComponent(path).replace(/%2F/g,'/')}?ref=${encodeURIComponent(branch)}`,token,true);if(!c||c.length>180000)continue;for(const e of discover(path,c)){const old=map.get(e.key);if(!old||e.confidence>old.confidence)map.set(e.key,e)}}const entities=[...map.values()];for(const e of entities)await db.from('system_entities').upsert({workspace_id:p.workspace_id,project_id:p.id,entity_key:e.key,entity_type:e.type,name:e.name,source_path:e.path,attributes:e.attributes,confidence:e.confidence,last_seen_at:new Date().toISOString()},{onConflict:'project_id,entity_key'});const{data:stored}=await db.from('system_entities').select('id,entity_key,entity_type,name,source_path,attributes,confidence').eq('project_id',p.id);return out({success:true,projectId:p.id,entities:stored||[],entityCount:stored?.length||0,filesConsidered:paths.length});}catch(e){console.error(e);return out({error:'System discovery failed'},500)}});
