// @ts-nocheck
import { useEffect, useMemo, useState } from 'react';
import { X, Folder, File as FileIcon, ChevronRight, ChevronDown, Loader as Loader2, Code2, ExternalLink, Eye } from 'lucide-react';
import { getTree, getFile, ERROR_TEXT } from './repoCache';
import CodeMirror from '@uiw/react-codemirror';
import { oneDark } from '@codemirror/theme-one-dark';
import { javascript } from '@codemirror/lang-javascript';
import { python } from '@codemirror/lang-python';
import { yaml } from '@codemirror/lang-yaml';
import { json } from '@codemirror/lang-json';
import { html } from '@codemirror/lang-html';
import { css } from '@codemirror/lang-css';
import { markdown } from '@codemirror/lang-markdown';
function parseGitUrl(url:string){const m=(url||'').match(/github\.com[/:]([^/]+)\/(.+?)(?:\.git)?(?:$|\/)/);return m?{owner:m[1],repo:m[2]}:null;}
function langFor(path:string){const e=(path.split('.').pop()||'').toLowerCase();if(['js','jsx','ts','tsx','mjs','cjs'].includes(e))return[javascript({jsx:true,typescript:/tsx?$/.test(e)})];if(e==='py')return[python()];if(['yml','yaml'].includes(e))return[yaml()];if(e==='json')return[json()];if(['html','htm','vue','svelte','xml'].includes(e))return[html()];if(['css','scss','less'].includes(e))return[css()];if(['md','mdx','markdown'].includes(e))return[markdown()];return[];}
function githubUrl(project:any,path:string){const p=parseGitUrl(project.git_url);return p?`https://github.com/${p.owner}/${p.repo}/blob/${project.git_branch||'main'}/${path}`:'';}
function buildTree(paths:string[]){const root:any={};for(const path of paths){const parts=path.split('/');let cur=root;parts.forEach((part,i)=>{const isFile=i===parts.length-1;cur[part]=cur[part]||{__file:isFile,__path:parts.slice(0,i+1).join('/'),children:{}};cur=cur[part].children;});}return root;}
function Node({node,name,depth,onSelect,selected,expanded,toggle}:any){const isFile=node.__file,open=expanded.has(node.__path);const kids=Object.entries(node.children).sort((a:any,b:any)=>a[1].__file===b[1].__file?a[0].localeCompare(b[0]):a[1].__file?1:-1);return <div><button onClick={()=>isFile?onSelect(node.__path):toggle(node.__path)} className={`flex w-full items-center gap-2 rounded-lg py-1.5 pr-3 text-left text-sm transition-colors hover:bg-gray-100 ${selected===node.__path?'bg-brand-50 text-brand-700':'text-navy-700'}`} style={{paddingLeft:depth*14+10}}>{isFile?<FileIcon size={14} className="shrink-0 text-gray-400"/>:<>{open?<ChevronDown size={14} className="shrink-0 text-gray-400"/>:<ChevronRight size={14} className="shrink-0 text-gray-400"/>}<Folder size={14} className="shrink-0 text-brand-500"/></>}<span className="truncate" title={name}>{name}</span></button>{!isFile&&open&&kids.map(([n,c]:any)=><Node key={c.__path} node={c} name={n} depth={depth+1} onSelect={onSelect} selected={selected} expanded={expanded} toggle={toggle}/>)}</div>}
export function FileBrowser({project,onClose}:any){
 const[loading,setLoading]=useState(true),[error,setError]=useState<any>(null),[paths,setPaths]=useState<string[]>([]),[expanded,setExpanded]=useState(new Set<string>()),[selected,setSelected]=useState<string|null>(null),[content,setContent]=useState(''),[fileLoading,setFileLoading]=useState(false),[editing,setEditing]=useState(false);
 useEffect(()=>{const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev;};},[]);
 useEffect(()=>{let live=true;(async()=>{setLoading(true);const t=await getTree(project);if(!live)return;if(t.error)setError(ERROR_TEXT[t.error]||t.error);else setPaths(t.paths||[]);setLoading(false);})();return()=>{live=false;};},[project.git_url,project.git_branch]);
 const tree=useMemo(()=>buildTree(paths),[paths]);const topKids=Object.entries(tree).sort((a:any,b:any)=>a[1].__file===b[1].__file?a[0].localeCompare(b[0]):a[1].__file?1:-1);const toggle=(p:string)=>setExpanded(s=>{const n=new Set(s);n.has(p)?n.delete(p):n.add(p);return n;});
 const select=async(p:string)=>{setSelected(p);setEditing(false);setFileLoading(true);try{const c=await getFile(project,p);setContent(c==null?'':String(c));}catch(e:any){setContent(`Unable to load file: ${e?.message||'Unknown error'}`);}finally{setFileLoading(false);}};
 return <div className="fixed inset-0 z-[9999] bg-slate-950/45 backdrop-blur-[1px]" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="absolute inset-3 sm:inset-6 lg:inset-10 flex flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl">
 <header className="flex h-16 shrink-0 items-center justify-between gap-4 border-b border-gray-200 bg-white px-5 sm:px-6"><div className="min-w-0"><div className="flex items-center gap-2"><Folder size={18} className="text-brand-600"/><h2 className="truncate text-base font-semibold text-navy-900">Repository files — {project.name}</h2></div><p className="mt-0.5 hidden text-xs text-gray-500 sm:block">Browse the repository, preview a file, then open it in the editor.</p></div><button onClick={onClose} className="grid h-9 w-9 shrink-0 place-items-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50" aria-label="Close file browser"><X size={18}/></button></header>
 <div className="flex min-h-0 flex-1"><aside className={`${selected?'hidden md:flex':'flex'} w-full md:w-[340px] lg:w-[380px] shrink-0 flex-col border-r border-gray-200 bg-gray-50/60`}><div className="shrink-0 border-b border-gray-200 px-4 py-3"><p className="text-xs font-semibold uppercase tracking-wider text-gray-500">Repository</p><p className="mt-1 truncate text-xs text-gray-400">{project.git_branch||'main'} · {paths.length} files</p></div><div className="min-h-0 flex-1 overflow-y-auto overflow-x-hidden px-2 py-2">{loading?<div className="flex justify-center py-10"><Loader2 size={20} className="animate-spin text-gray-400"/></div>:error?<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{error}</p>:topKids.map(([n,c]:any)=><Node key={c.__path} node={c} name={n} depth={0} onSelect={select} selected={selected} expanded={expanded} toggle={toggle}/>)}</div></aside>
 <main className={`${selected?'flex':'hidden md:flex'} min-w-0 flex-1 flex-col bg-white`}>{!selected?<div className="flex flex-1 items-center justify-center p-8"><div className="max-w-sm text-center"><FileIcon size={32} className="mx-auto mb-3 text-gray-300"/><p className="text-sm font-medium text-gray-600">Select a file to preview</p><p className="mt-1 text-xs text-gray-400">Choose any file from the repository tree on the left.</p></div></div>:<><div className="flex min-h-12 shrink-0 items-center justify-between gap-3 border-b border-gray-200 px-4"><div className="flex min-w-0 items-center gap-2"><button onClick={()=>{setSelected(null);setEditing(false);}} className="md:hidden rounded p-1 text-brand-600"><ChevronRight size={17} className="rotate-180"/></button><FileIcon size={14} className="shrink-0 text-gray-400"/><span className="truncate font-mono text-xs text-navy-800">{selected}</span>{editing&&<span className="rounded bg-brand-50 px-2 py-0.5 text-[10px] font-bold uppercase text-brand-700">Editor</span>}</div><div className="flex shrink-0 items-center gap-2">{githubUrl(project,selected)&&<a href={githubUrl(project,selected)} target="_blank" rel="noreferrer" className="hidden sm:inline-flex items-center gap-1.5 rounded-lg border border-gray-200 px-2.5 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50"><ExternalLink size={12}/>GitHub</a>}<button onClick={()=>setEditing(v=>!v)} className="inline-flex items-center gap-1.5 rounded-lg bg-brand-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-brand-700">{editing?<Eye size={13}/>:<Code2 size={13}/>} {editing?'Preview':'Open in Editor'}</button></div></div><div className="min-h-0 flex-1 overflow-hidden">{fileLoading?<div className="flex h-full items-center justify-center"><Loader2 size={20} className="animate-spin text-gray-400"/></div>:editing?<CodeMirror value={content} onChange={setContent} height="100%" theme={oneDark} extensions={langFor(selected)} basicSetup={{lineNumbers:true,foldGutter:true}} style={{height:'100%',fontSize:13}}/>:<pre className="h-full overflow-auto bg-[#fbfcfe] p-5 font-mono text-[13px] leading-6 text-slate-800"><code>{content}</code></pre>}</div></>}</main></div></div></div>;
}
