// @ts-nocheck
import{useCallback,useEffect,useState}from'react';
import{supabase,type Project}from'../lib/supabase';
import{Spinner}from'../lib/ui';
import{Link}from'../lib/router';
import{ChevronDown,Settings,ArrowLeft,Network,Sparkles,SlidersHorizontal,GitCompare,Shield,Code2,Server,Database,Activity,DollarSign,Boxes,Search,Play,BrainCircuit,GitBranch,Clock,CheckCircle2,AlertTriangle,Lock,Package,Wifi,Expand,RefreshCw}from'lucide-react';
import{ReleaseWorkspace}from'./ReleaseWorkspace';
import{ProjectIntegrationsPage}from'./ProjectIntegrationsPage';
import{PoliciesPage}from'./PoliciesPage';
import{TopologyView}from'./TopologyView';

const LENSES=[['Overview',Sparkles],['Architecture',Network],['Security',Shield],['Code',Code2],['DevOps',Boxes],['Infrastructure',Server],['Data',Database],['Reliability',Activity],['Cost',DollarSign]];
const DOMAINS=['Security','Code','DevOps','Infrastructure','Dependencies','Data','Networking','Reliability','Scalability','Cost'];
const DOMAIN_ICON={Security:Shield,Code:Code2,DevOps:Boxes,Infrastructure:Server,Dependencies:Package,Data:Database,Networking:Wifi,Reliability:Activity,Scalability:Expand,Cost:DollarSign};

export function ProjectWorkspace({projectId}:{projectId:string}){
 const[project,setProject]=useState<Project|null>(null),[loading,setLoading]=useState(true),[view,setView]=useState('workspace');
 const[lens,setLens]=useState('Overview'),[advanced,setAdvanced]=useState(false),[depth,setDepth]=useState('Standard'),[mode,setMode]=useState('Smart Analysis'),[selected,setSelected]=useState(()=>new Set(DOMAINS));
 const[validations,setValidations]=useState<any[]>([]),[findings,setFindings]=useState<any[]>([]),[intelligence,setIntelligence]=useState<any>(null),[showRelease,setShowRelease]=useState(false);
 const wsId=localStorage.getItem('sandbox.activeWs')||'';
 const load=useCallback(async()=>{setLoading(true);const[p,v,f,a]=await Promise.all([supabase.from('projects').select('*').eq('id',projectId).single(),supabase.from('validations').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(10),supabase.from('findings').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(200),supabase.from('ai_insights').select('*').eq('project_id',projectId).eq('type','validation_review').order('created_at',{ascending:false}).limit(1)]);setProject(p.data as any);setValidations(v.data||[]);setFindings(f.data||[]);setIntelligence(a.data?.[0]?.content||null);setLoading(false)},[projectId]);
 useEffect(()=>{load()},[load]);
 const toggle=(d:string)=>setSelected(s=>{const n=new Set(s);n.has(d)?n.delete(d):n.add(d);return n});
 if(loading)return<div className="flex justify-center py-24"><Spinner size={28}/></div>;
 if(!project)return<div className="text-center py-16"><p className="text-gray-500">Project not found.</p><Link to="/projects" className="text-brand-600 text-sm">← Back to projects</Link></div>;
 const latest=validations.find(v=>v.status==='completed'),open=findings.filter(f=>f.status!=='resolved'),critical=open.filter(f=>['critical','high'].includes(f.severity)),risk=latest?.risk_score,readiness=risk==null?null:Math.max(0,100-risk);
 const domainCount=(d:string)=>open.filter(f=>`${f.category||''} ${f.title||''}`.toLowerCase().includes(d.toLowerCase())||(d==='Security'&&/secret|auth|security|cors|tls/i.test(`${f.category} ${f.title}`))||(d==='DevOps'&&/workflow|docker|kubernetes|ci|deployment/i.test(`${f.category} ${f.title}`))||(d==='Infrastructure'&&/infrastructure|terraform|cloudformation/i.test(`${f.category} ${f.title}`))).length;
 return <div className="h-full overflow-y-auto bg-[#f7f8fa]">
  <div className="border-b border-gray-200 bg-white px-5 lg:px-8 py-4"><div className="flex flex-wrap items-center gap-3"><Link to="/projects" className="text-gray-400 hover:text-gray-700"><ArrowLeft size={17}/></Link><div><div className="flex items-center gap-2"><h1 className="text-lg font-bold text-navy-950">{project.name}</h1><span className="rounded-md bg-gray-100 px-2 py-1 text-[11px] text-gray-500"><GitBranch size={10} className="inline mr-1"/>{project.git_branch||'main'}</span></div><p className="text-xs text-gray-500 mt-0.5">Application Intelligence Workspace</p></div><div className="ml-auto flex gap-2"><button onClick={()=>setView('topology')} className="btn-secondary text-xs"><Network size={13}/>Architecture</button><button onClick={()=>setShowRelease(v=>!v)} className="btn-secondary text-xs"><Play size={13}/>Release workflow</button><button onClick={()=>setView('settings')} className="p-2 rounded-lg border border-gray-200 bg-white"><Settings size={14}/></button></div></div></div>
  {view==='workspace'&&<main className="max-w-[1500px] mx-auto p-5 lg:p-8 space-y-5">
   <section className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden"><div className="p-5 lg:p-6 flex flex-col xl:flex-row xl:items-center gap-5"><div className="flex-1"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-brand-700"><BrainCircuit size={15}/>LytHouse Intelligence</div><h2 className="mt-2 text-2xl font-bold tracking-tight text-navy-950">Understand the application. Validate the evidence. Decide what ships.</h2><p className="mt-2 max-w-3xl text-sm text-gray-600">Run evidence-grounded analysis across architecture, security, delivery, reliability and cost. Start simple or open the Analysis Lab for precise scope and depth.</p></div><div className="flex flex-wrap gap-2"><div className="relative"><select value={mode} onChange={e=>setMode(e.target.value)} className="appearance-none rounded-xl bg-navy-950 text-white pl-4 pr-9 py-2.5 text-sm font-semibold"><option>Smart Analysis</option><option>Full Analysis</option><option>Changes Only</option><option>Targeted Analysis</option><option>Release Validation</option></select><ChevronDown size={14} className="absolute right-3 top-3 text-white pointer-events-none"/></div><button onClick={()=>setAdvanced(v=>!v)} className="btn-secondary"><SlidersHorizontal size={14}/>Analysis Lab</button><button className="btn-secondary"><GitCompare size={14}/>Compare</button></div></div>
    {advanced&&<div className="border-t border-gray-100 bg-slate-50 p-5"><div className="flex flex-wrap items-center gap-4 mb-4"><strong className="text-sm text-navy-950">Analysis Lab</strong><label className="text-xs text-gray-600">Depth <select value={depth} onChange={e=>setDepth(e.target.value)} className="ml-1 rounded-lg border border-gray-200 bg-white px-2 py-1.5"><option>Fast</option><option>Standard</option><option>Deep</option></select></label><span className="text-xs text-gray-400">{selected.size} domains selected</span><button className="ml-auto btn-primary text-xs"><Play size={12}/>Run selected analysis</button></div><div className="flex flex-wrap gap-2">{DOMAINS.map(d=>{const I=DOMAIN_ICON[d];return<button key={d} onClick={()=>toggle(d)} className={`flex items-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-semibold ${selected.has(d)?'border-brand-200 bg-white text-brand-700 shadow-sm':'border-gray-200 bg-gray-100 text-gray-400'}`}><I size={12}/>{selected.has(d)?'✓ ':''}{d}</button>})}</div></div>}
   </section>
   <section className="grid grid-cols-2 md:grid-cols-4 gap-3"><Stat label="Release readiness" value={readiness==null?'—':`${readiness}%`} sub={latest?'Evidence based':'Run first analysis'} tone={readiness!=null&&readiness<70?'bad':'good'}/><Stat label="Open findings" value={open.length} sub={`${critical.length} high priority`} tone={critical.length?'bad':'good'}/><Stat label="Last analysis" value={latest?'Complete':'Not run'} sub={latest?new Date(latest.completed_at||latest.created_at).toLocaleString():'No baseline yet'}/><Stat label="AI intelligence" value={intelligence?'Ready':'Awaiting evidence'} sub={intelligence?'Correlations available':'Generated after validation'} tone={intelligence?'good':''}/></section>
   <section className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><div className="flex gap-1 overflow-x-auto no-scrollbar">{LENSES.map(([n,I]:any)=><button key={n} onClick={()=>{setLens(n);if(n==='Architecture')setView('topology')}} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-semibold whitespace-nowrap ${lens===n?'bg-navy-950 text-white':'text-gray-500 hover:bg-gray-100'}`}><I size={12}/>{n}</button>)}</div></section>
   <div className="grid xl:grid-cols-[1.35fr_.65fr] gap-5"><section className="rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="p-5 border-b border-gray-100"><h3 className="font-bold text-navy-950">Analysis domains</h3><p className="text-xs text-gray-500 mt-1">Drill into the engineering dimensions LytHouse can prove from repository evidence.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-px bg-gray-100">{DOMAINS.map(d=>{const I=DOMAIN_ICON[d],n=domainCount(d);return<button key={d} onClick={()=>setLens(d)} className="bg-white p-4 text-left hover:bg-slate-50 group"><div className="flex items-center justify-between"><span className="h-9 w-9 rounded-xl bg-slate-100 flex items-center justify-center"><I size={16} className="text-navy-700"/></span><span className={`text-xs font-bold ${n?'text-amber-700':'text-emerald-700'}`}>{n?`${n} finding${n===1?'':'s'}`:'No open finding'}</span></div><div className="mt-3 font-semibold text-sm text-navy-950">{d}</div><div className="mt-1 text-xs text-gray-500">Open evidence, checks, relationships and remediation.</div></button>})}</div></section>
    <section className="rounded-2xl border border-gray-200 bg-white shadow-sm p-5"><div className="flex items-center gap-2"><Sparkles size={16} className="text-brand-600"/><h3 className="font-bold text-navy-950">AI intelligence brief</h3></div>{intelligence?<div className="mt-4 space-y-4"><div><div className="text-xs font-bold uppercase text-gray-400">Executive assessment</div><p className="mt-1 text-sm text-gray-700 leading-6">{intelligence.executive_summary||intelligence.release_assessment||'Evidence review completed.'}</p></div>{intelligence.confidence_notes&&<div className="rounded-xl bg-slate-50 border border-gray-100 p-3 text-xs text-gray-600">{typeof intelligence.confidence_notes==='string'?intelligence.confidence_notes:JSON.stringify(intelligence.confidence_notes)}</div>}</div>:<div className="mt-6 text-center py-8"><BrainCircuit size={28} className="mx-auto text-gray-300"/><p className="mt-3 text-sm font-semibold text-navy-900">Intelligence starts with evidence</p><p className="mt-1 text-xs text-gray-500">Run validation first. AI then correlates verified findings instead of inventing issues.</p></div>}</section></div>
   <section className="rounded-2xl border border-gray-200 bg-white shadow-sm p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-navy-950">Findings explorer</h3><p className="text-xs text-gray-500 mt-1">Searchable evidence with severity, location, confidence and remediation.</p></div><div className="relative"><Search size={13} className="absolute left-3 top-2.5 text-gray-400"/><input className="rounded-lg border border-gray-200 pl-8 pr-3 py-2 text-xs" placeholder="Search findings…"/></div></div><div className="mt-4 divide-y divide-gray-100">{open.slice(0,8).map(f=><div key={f.id} className="py-3 flex gap-3"><span className={`mt-0.5 h-2 w-2 rounded-full ${['critical','high'].includes(f.severity)?'bg-red-500':f.severity==='medium'?'bg-amber-500':'bg-blue-500'}`}/><div className="min-w-0 flex-1"><div className="text-sm font-semibold text-navy-900">{f.title}</div><div className="text-xs text-gray-500 mt-1">{f.category||'Analysis'} · {f.file_path||'repository evidence'}{f.line?`:${f.line}`:''} · {f.confidence?`${f.confidence}% confidence`:''}</div></div><button onClick={()=>setShowRelease(true)} className="text-xs font-semibold text-brand-700">Investigate →</button></div>)}{!open.length&&<div className="py-8 text-center text-sm text-gray-500">No open findings in the current evidence set.</div>}</div></section>
   {showRelease&&<section className="rounded-2xl border-2 border-brand-100 bg-white overflow-hidden"><div className="flex items-center justify-between px-5 py-3 border-b border-gray-100"><div><h3 className="font-bold text-navy-950">Release validation & remediation</h3><p className="text-xs text-gray-500">Detailed evidence, remediation, approvals and deployment workflow.</p></div><button onClick={()=>setShowRelease(false)} className="text-xs text-gray-500">Hide</button></div><div className="min-h-[700px]"><ReleaseWorkspace projectId={projectId} project={project}/></div></section>}
  </main>}
  {view==='topology'&&<div className="p-6 overflow-y-auto h-full"><button onClick={()=>setView('workspace')} className="text-xs text-brand-700 mb-4">← Analysis Workspace</button><h2 className="text-xl font-bold text-navy-950">Application Intelligence · Architecture</h2><p className="text-sm text-gray-500 mt-1 mb-5">Explore services, data stores and relationships inferred from repository evidence.</p><TopologyView projectId={projectId} project={project} onOpenFile={()=>setView('workspace')}/></div>}
  {view==='settings'&&<div className="p-8"><button onClick={()=>setView('workspace')} className="text-xs text-brand-700">← Analysis Workspace</button><p className="mt-6 text-sm text-gray-500">Project settings remain available from the Projects page.</p></div>}
 </div>;
}
function Stat({label,value,sub,tone=''}){return<div className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><div className="text-xs font-medium text-gray-500">{label}</div><div className={`mt-2 text-2xl font-bold ${tone==='bad'?'text-red-700':tone==='good'?'text-emerald-700':'text-navy-950'}`}>{value}</div><div className="mt-1 text-[11px] text-gray-400">{sub}</div></div>}
