// @ts-nocheck
import{useCallback,useEffect,useMemo,useState}from'react';
import{supabase,type Project}from'../lib/supabase';
import{Spinner}from'../lib/ui';
import{Link}from'../lib/router';
import{ArrowLeft,Network,Sparkles,Shield,Code2,Server,Database,Activity,DollarSign,Boxes,Search,Play,BrainCircuit,GitBranch,Package,Wifi,Expand,FlaskConical,PlugZap,ExternalLink,TerminalSquare,AlertTriangle,Save,Layers3,ChevronRight}from'lucide-react';
import{ReleaseWorkspace}from'./ReleaseWorkspace';
import{TopologyView}from'./TopologyView';

const DOMAINS=['Security','Code','QA','API','DevOps','Infrastructure','Dependencies','Data','Networking','Reliability','Scalability','Cost'];
const ICON={Security:Shield,Code:Code2,QA:FlaskConical,API:PlugZap,DevOps:Boxes,Infrastructure:Server,Dependencies:Package,Data:Database,Networking:Wifi,Reliability:Activity,Scalability:Expand,Cost:DollarSign};
const GROUPS=[['Build & Code',['Code','Dependencies']],['Quality & Interfaces',['QA','API']],['Platform',['DevOps','Infrastructure','Networking']],['Production',['Security','Data','Reliability','Scalability','Cost']]];
export function ProjectWorkspace({projectId}:{projectId:string}){
 const[project,setProject]=useState<Project|null>(null),[loading,setLoading]=useState(true),[view,setView]=useState('workspace'),[lens,setLens]=useState('Overview'),[showRelease,setShowRelease]=useState(false),[query,setQuery]=useState('');
 const[validations,setValidations]=useState<any[]>([]),[findings,setFindings]=useState<any[]>([]),[intel,setIntel]=useState<any>(null),[runs,setRuns]=useState<any[]>([]),[components,setComponents]=useState<any[]>([]),[apis,setApis]=useState<any[]>([]),[qa,setQa]=useState<any[]>([]),[tests,setTests]=useState<any[]>([]),[external,setExternal]=useState<any[]>([]),[jira,setJira]=useState<any[]>([]);
 const[script,setScript]=useState(''),[testName,setTestName]=useState('Untitled QA test'),[framework,setFramework]=useState('Playwright'),[saving,setSaving]=useState(false),[saved,setSaved]=useState('');
 const load=useCallback(async()=>{setLoading(true);const qs=[supabase.from('projects').select('*').eq('id',projectId).single(),supabase.from('validations').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(10),supabase.from('findings').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(250),supabase.from('ai_insights').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(1),supabase.from('analysis_runs').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(10),supabase.from('application_components').select('*').eq('project_id',projectId).limit(500),supabase.from('api_endpoints').select('*').eq('project_id',projectId).limit(500),supabase.from('qa_gaps').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(100),supabase.from('qa_test_cases').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(100),supabase.from('external_intelligence').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(50),supabase.from('jira_issue_links').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(50)];const r=await Promise.all(qs);setProject(r[0].data);setValidations(r[1].data||[]);setFindings(r[2].data||[]);setIntel(r[3].data?.[0]?.content||null);setRuns(r[4].data||[]);setComponents(r[5].data||[]);setApis(r[6].data||[]);setQa(r[7].data||[]);setTests(r[8].data||[]);setExternal(r[9].data||[]);setJira(r[10].data||[]);setLoading(false)},[projectId]);
 useEffect(()=>{load()},[load]);
 const saveTest=async()=>{if(!script.trim()||!project)return;setSaving(true);setSaved('');const ws=project.workspace_id||localStorage.getItem('sandbox.activeWs');const{error}=await supabase.from('qa_test_cases').insert({workspace_id:ws,project_id:projectId,name:testName||'Untitled QA test',framework,test_type:framework==='API / HTTP'?'api':'custom',source:'test_lab',script,status:'draft',metadata:{origin:'project_test_lab'}});setSaving(false);if(error)setSaved(error.message);else{setSaved('Saved to project QA evidence');setScript('');await load()}};
 if(loading)return <div className="flex justify-center py-24"><Spinner size={28}/></div>;if(!project)return <div className="p-12">Project not found.</div>;
 const latest=validations.find(v=>v.status==='completed'),open=findings.filter(f=>f.status!=='resolved'),critical=open.filter(f=>['critical','high'].includes(f.severity)),readiness=latest?.risk_score==null?null:Math.max(0,100-latest.risk_score),activeRun=runs[0];
 const filtered=open.filter(f=>!query||`${f.title} ${f.category} ${f.file_path}`.toLowerCase().includes(query.toLowerCase()));
 const count=(d:string)=>d==='QA'?qa.filter(x=>x.status!=='resolved').length:d==='API'?apis.length:open.filter(f=>`${f.category||''} ${f.title||''}`.toLowerCase().includes(d.toLowerCase())).length;
 const story=useMemo(()=>{const app= intel?.application_understanding||{};return{stack:[...(app.observed_stack||[]),...components.slice(0,6).map(c=>c.version?`${c.name} ${c.version}`:c.name)].filter(Boolean).slice(0,8),delivery:app.observed_delivery||[],priorities:intel?.priorities||[],cross:intel?.cross_domain_insights||[],future:intel?.future_risks||[],needs:intel?.needs_investigation||[]}},[intel,components]);
 return <div className="h-full overflow-y-auto bg-[#f7f8fa]">
 <header className="border-b bg-white px-6 lg:px-8 py-4 flex items-center gap-3"><Link to="/projects" className="text-gray-400"><ArrowLeft size={17}/></Link><div><div className="flex items-center gap-2"><h1 className="font-bold text-navy-950">{project.name}</h1><span className="text-[11px] bg-gray-100 rounded px-2 py-1"><GitBranch size={10} className="inline mr-1"/>{project.git_branch||'main'}</span></div><p className="text-xs text-gray-500">Application Assurance Workspace</p></div><div className="ml-auto flex gap-2"><button onClick={()=>setView('topology')} className="btn-secondary text-xs"><Network size={13}/>Architecture</button><button onClick={()=>setShowRelease(v=>!v)} className="btn-secondary text-xs"><Play size={13}/>Release workflow</button></div></header>
 {view==='topology'?<div className="p-6"><button onClick={()=>setView('workspace')} className="text-xs text-brand-700 mb-4">← Assurance Workspace</button><TopologyView projectId={projectId} project={project} onOpenFile={()=>setView('workspace')}/></div>:<main className="max-w-[1550px] mx-auto p-5 lg:p-8 space-y-5">
 <section className="rounded-2xl bg-navy-950 text-white p-6 shadow-sm"><div className="flex flex-col xl:flex-row gap-6 xl:items-end"><div className="flex-1"><div className="flex items-center gap-2 text-xs uppercase tracking-[.15em] text-brand-200 font-bold"><BrainCircuit size={16}/>LytHouse Application Story</div><h2 className="text-2xl lg:text-3xl font-bold mt-2">{story.stack.length?`LytHouse understands ${story.stack.slice(0,3).join(' · ')}`:'Repository connected. Application understanding is waiting for a completed intelligence run.'}</h2><p className="text-sm text-slate-300 mt-2 max-w-4xl">{intel?.executive_summary||intel?.release_assessment?.reason||'This workspace becomes useful when repository discovery, validation and AI investigation persist evidence. Empty domains are shown as not evaluated—not as a pass.'}</p></div><div className="grid grid-cols-2 gap-2 text-xs"><Pill t={`${components.length} components`}/><Pill t={`${apis.length} APIs`}/><Pill t={`${qa.length} QA gaps`}/><Pill t={`${external.length} vendor signals`}/></div></div></section>
 <section className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Stat l="Release readiness" v={readiness==null?'—':`${readiness}%`} s={latest?'Evidence-based baseline':'Not evaluated yet'}/><Stat l="Priority risks" v={critical.length} s={`${open.length} open findings`} bad={critical.length>0}/><Stat l="QA assurance" v={qa.length?`${qa.filter(x=>x.status==='resolved').length}/${qa.length}`:'—'} s={`${tests.length} saved tests`}/><Stat l="API surface" v={apis.length||'—'} s={apis.length?'Discovered from evidence':'Not discovered yet'}/><Stat l="Intelligence" v={activeRun?.status|| (intel?'Available':'Not run')} s={activeRun?`${activeRun.mode} · ${activeRun.depth}`:'Project evidence state'}/></section>
 <section className="rounded-2xl border bg-white shadow-sm p-4"><div className="flex gap-2 overflow-x-auto">{['Overview','QA','API','Security','Code','Platform','Production','Vendor Intelligence','Test Lab'].map(n=><button key={n} onClick={()=>setLens(n)} className={`px-3 py-2 rounded-lg text-xs font-semibold whitespace-nowrap ${lens===n?'bg-navy-950 text-white':'text-gray-500 hover:bg-gray-100'}`}>{n}</button>)}</div></section>
 {lens==='Overview'&&<><div className="grid xl:grid-cols-[1.35fr_.65fr] gap-5"><section className="rounded-2xl border bg-white shadow-sm"><Title t="What LytHouse understands" s="A connected story from repository, validation, QA, API and external evidence."/><div className="p-5 grid md:grid-cols-2 gap-4"><Story t="Application shape" items={story.stack} empty="No persisted application components yet."/><Story t="Delivery & runtime" items={story.delivery} empty="Delivery evidence has not been persisted yet."/><Story t="Highest-value priorities" items={story.priorities.map(x=>x.title)} empty={open.length?`${open.length} findings exist; AI correlation has not produced priorities yet.`:'No verified priority evidence yet.'}/><Story t="Cross-domain intelligence" items={story.cross.map(x=>x.title)} empty="No cross-domain conclusion has been verified yet."/></div></section><section className="rounded-2xl border bg-white shadow-sm"><Title t="Assurance status" s="What is known, and what still needs evidence."/><div className="p-5 space-y-3"><Status ok={components.length>0} t="Application model" s={components.length?`${components.length} components persisted`:'Discovery has not populated components'}/><Status ok={apis.length>0} t="API model" s={apis.length?`${apis.length} endpoints persisted`:'API discovery not evaluated'}/><Status ok={qa.length>0||tests.length>0} t="QA evidence" s={qa.length||tests.length?`${qa.length} gaps · ${tests.length} tests`:'QA discovery not evaluated'}/><Status ok={external.length>0} t="External intelligence" s={external.length?`${external.length} evidence records`:'No persisted vendor evidence yet'}/></div></section></div>
 <section className="rounded-2xl border bg-white shadow-sm"><Title t="Explore the application" s="Detailed specialist views are grouped so the workspace stays powerful without becoming overwhelming."/><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-px bg-gray-100">{GROUPS.map(([g,ds]:any)=><button key={g} onClick={()=>setLens(g==='Build & Code'?'Code':g)} className="bg-white p-5 text-left hover:bg-slate-50"><div className="flex items-center"><Layers3 size={16}/><b className="ml-2 text-sm">{g}</b><ChevronRight size={14} className="ml-auto"/></div><p className="mt-2 text-xs text-gray-500">{ds.join(' · ')}</p><div className="mt-3 text-xs font-semibold text-brand-700">{ds.reduce((a,d)=>a+count(d),0)} evidence signals</div></button>)}</div></section></>}
 {lens==='QA'&&<QAView qa={qa} tests={tests} goLab={()=>setLens('Test Lab')}/>} 
 {lens==='Test Lab'&&<section className="rounded-2xl border bg-white shadow-sm"><Title t="QA Test Lab" s="Paste or write a test, persist it to this project, and build a reusable QA evidence trail."/><div className="p-5 grid xl:grid-cols-[1fr_.35fr] gap-5"><div><div className="flex flex-wrap gap-2 mb-3"><input value={testName} onChange={e=>setTestName(e.target.value)} className="border rounded-lg px-3 py-2 text-xs flex-1 min-w-56"/><select value={framework} onChange={e=>setFramework(e.target.value)} className="border rounded-lg px-3 py-2 text-xs"><option>Playwright</option><option>Cypress</option><option>Jest</option><option>Vitest</option><option>Pytest</option><option>API / HTTP</option><option>Shell</option></select></div><textarea value={script} onChange={e=>setScript(e.target.value)} className="w-full min-h-[430px] rounded-xl bg-slate-950 text-slate-100 p-4 font-mono text-xs" placeholder="Paste a Playwright, Cypress, Jest, Pytest, API/HTTP or shell test here…"/><div className="mt-3 flex items-center gap-2"><button onClick={saveTest} disabled={saving||!script.trim()} className="btn-primary text-xs"><Save size={12}/>{saving?'Saving…':'Save Test'}</button><button disabled className="btn-secondary text-xs opacity-50">AI Analyze</button><button disabled className="btn-secondary text-xs opacity-50">Run in isolated sandbox</button><span className="text-[11px] text-gray-500">{saved}</span></div></div><div className="border rounded-xl p-4"><h4 className="font-bold text-sm">Saved project tests</h4><p className="text-xs text-gray-500 mt-1">Database-backed test assets for this application.</p><div className="mt-4 space-y-2">{tests.slice(0,10).map(t=><div key={t.id} className="rounded-lg bg-slate-50 p-3"><b className="text-xs">{t.name}</b><div className="text-[11px] text-gray-500 mt-1">{t.framework||t.test_type||'Custom'} · {t.status}</div></div>)}{!tests.length&&<p className="text-xs text-gray-400">No saved tests yet.</p>}</div></div></div></section>}
 {lens==='API'&&<section className="rounded-2xl border bg-white shadow-sm"><Title t="API Intelligence" s="The API story: endpoint inventory, authentication posture and test readiness."/><div className="p-5">{apis.length?<div className="divide-y">{apis.map(a=><div key={a.id} className="py-3 flex gap-3 items-center"><span className="font-mono text-xs font-bold w-14">{a.method||'ANY'}</span><code className="text-xs flex-1">{a.route}</code><span className="text-xs text-gray-500">{a.auth_required===true?'Auth required':a.auth_required===false?'Auth not observed':'Auth unknown'}</span></div>)}</div>:<Empty icon={PlugZap} t="API discovery has not run" s="The repository is connected, but no API endpoint evidence has been persisted yet. This is not a pass."/>}</div></section>}
 {lens==='Vendor Intelligence'&&<section className="rounded-2xl border bg-white shadow-sm"><Title t="Vendor & lifecycle intelligence" s="Only authoritative external evidence connected to technologies found in this project."/><div className="p-5">{external.length?external.map(x=><div key={x.id} className="border rounded-xl p-4 mb-3"><div className="flex"><b className="text-sm">{x.subject}</b><span className="ml-auto text-xs">{x.intelligence_type}</span></div><p className="text-xs text-gray-600 mt-2">{x.advisory}</p>{x.source_url&&<a href={x.source_url} target="_blank" rel="noreferrer" className="text-xs text-brand-700 mt-2 inline-flex gap-1">Source <ExternalLink size={11}/></a>}</div>):<Empty icon={ExternalLink} t="Vendor research not persisted" s="No lifecycle or advisory claim is shown until LytHouse has source evidence."/>}</div></section>}
 {['Security','Code'].includes(lens)&&<Domain lens={lens} rows={filtered}/>} 
 {lens==='Platform'&&<Grouped title="Platform Intelligence" domains={['DevOps','Infrastructure','Networking']} rows={filtered}/>} 
 {lens==='Production'&&<Grouped title="Production Intelligence" domains={['Security','Data','Reliability','Scalability','Cost']} rows={filtered}/>} 
 <section className="rounded-2xl border bg-white shadow-sm"><div className="p-5 flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">Evidence explorer</h3><p className="text-xs text-gray-500">One evidence stream across engineering, QA, APIs and release decisions.</p></div><div className="relative"><Search size={13} className="absolute left-3 top-2.5 text-gray-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="rounded-lg border pl-8 pr-3 py-2 text-xs" placeholder="Search evidence…"/></div></div><Findings rows={filtered.slice(0,12)}/></section>
 {showRelease&&<section className="rounded-2xl border-2 border-brand-100 bg-white overflow-hidden"><div className="p-4 border-b flex justify-between"><b>Release validation & remediation</b><button onClick={()=>setShowRelease(false)} className="text-xs">Hide</button></div><div className="min-h-[700px]"><ReleaseWorkspace projectId={projectId} project={project}/></div></section>}
 </main>}</div>}
function QAView({qa,tests,goLab}){return <section className="rounded-2xl border bg-white shadow-sm"><Title t="QA Intelligence" s="Coverage gaps, missing scenarios and saved tests tied to the application evidence."/><div className="p-5"><button onClick={goLab} className="btn-primary text-xs mb-4"><TerminalSquare size={12}/>Open Test Lab</button>{qa.length?qa.map(g=><div key={g.id} className="border rounded-xl p-4 mb-3"><div className="flex gap-2"><AlertTriangle size={14}/><b className="text-sm">{g.title}</b><span className="ml-auto text-xs uppercase">{g.severity}</span></div><p className="text-xs text-gray-600 mt-2">{g.description||'Coverage gap identified from evidence.'}</p>{g.recommended_test&&<div className="mt-3 bg-slate-50 p-3 rounded-lg text-xs"><b>Recommended test:</b> {g.recommended_test}</div>}</div>):<Empty icon={FlaskConical} t="QA discovery has not produced gaps yet" s={`${tests.length} saved tests exist. A connected repository alone does not mean QA has been evaluated.`}/>}</div></section>}
function Grouped({title,domains,rows}){const r=rows.filter(f=>domains.some(d=>`${f.category||''} ${f.title||''}`.toLowerCase().includes(d.toLowerCase())));return <section className="rounded-2xl border bg-white shadow-sm"><Title t={title} s={domains.join(' · ')}/><Findings rows={r}/></section>}
function Domain({lens,rows}){return <section className="rounded-2xl border bg-white shadow-sm"><Title t={`${lens} Intelligence`} s="Evidence-backed project findings."/><Findings rows={rows.filter(f=>`${f.category||''} ${f.title||''}`.toLowerCase().includes(lens.toLowerCase()))}/></section>}
function Story({t,items,empty}){return <div className="rounded-xl border p-4"><b className="text-sm">{t}</b>{items?.length?<div className="mt-3 space-y-2">{items.slice(0,6).map((x,i)=><div key={i} className="text-xs text-gray-600 flex gap-2"><span className="text-brand-600">•</span><span>{typeof x==='string'?x:JSON.stringify(x)}</span></div>)}</div>:<p className="mt-2 text-xs text-gray-400">{empty}</p>}</div>}
function Status({ok,t,s}){return <div className="rounded-xl border p-3"><div className="flex items-center"><span className={`h-2 w-2 rounded-full ${ok?'bg-emerald-500':'bg-amber-400'}`}/><b className="ml-2 text-xs">{t}</b><span className="ml-auto text-[10px] font-bold uppercase text-gray-400">{ok?'Evidence':'Not evaluated'}</span></div><p className="mt-1 ml-4 text-[11px] text-gray-500">{s}</p></div>}
function Findings({rows}){return <div className="px-5 pb-5 divide-y">{rows.length?rows.map(f=><div key={f.id} className="py-3 flex gap-3"><span className={`mt-1 h-2 w-2 rounded-full ${['critical','high'].includes(f.severity)?'bg-red-500':f.severity==='medium'?'bg-amber-500':'bg-blue-500'}`}/><div><b className="text-sm">{f.title}</b><p className="text-xs text-gray-500 mt-1">{f.category||'Analysis'} · {f.file_path||'repository evidence'}{f.line?`:${f.line}`:''}</p></div></div>):<div className="py-8 text-center text-xs text-gray-400">No persisted evidence for this view. This domain has not been proven clean.</div>}</div>}
function Title({t,s}){return <div className="p-5 border-b"><h3 className="font-bold text-navy-950">{t}</h3><p className="text-xs text-gray-500 mt-1">{s}</p></div>}
function Empty({icon:I,t,s}){return <div className="py-12 text-center"><I size={26} className="mx-auto text-gray-300"/><b className="block text-sm mt-3">{t}</b><p className="text-xs text-gray-500 mt-1 max-w-lg mx-auto">{s}</p></div>}
function Stat({l,v,s,bad}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="text-xs text-gray-500">{l}</div><div className={`text-2xl font-bold mt-2 ${bad?'text-red-700':'text-navy-950'}`}>{v}</div><div className="text-[11px] text-gray-400 mt-1">{s}</div></div>}
function Pill({t}){return <span className="rounded-lg bg-white/10 px-3 py-2">{t}</span>}
