// @ts-nocheck
// AI Auto-Remediation: generate SAFE, additive fixes and open a real pull
// request via the GitHub API. Only additive/non-breaking fixes are automated;
// risky in-place edits (e.g. rewriting Dockerfile USER) are surfaced as
// manual/guided so a human owns them.

function parseGitUrl(url) {
  if (!url) return null;
  const m = url.match(/github\.com[/:]([^/]+)\/(.+?)(?:\.git)?(?:$|\/)/);
  return m ? { owner: m[1], repo: m[2] } : null;
}
const b64 = (s) => btoa(unescape(encodeURIComponent(s)));

async function gh(path, token, opts = {}) {
  const res = await fetch('https://api.github.com' + path, {
    ...opts,
    headers: { Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', Authorization: 'Bearer ' + token, ...(opts.headers || {}) },
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.message || `GitHub ${res.status}`);
  return data;
}
async function getFile(owner, repo, path, branch, token) {
  try {
    const d = await gh(`/repos/${owner}/${repo}/contents/${path.split('/').map(encodeURIComponent).join('/')}?ref=${branch}`, token);
    return { sha: d.sha, content: d.content ? decodeURIComponent(escape(atob(d.content.replace(/\n/g, '')))) : '' };
  } catch { return null; }
}

// ── Safe fix generators (return {message, files:[{path, content, sha?}]}) ──
const SECURITY_WORKFLOW = `name: Lythouse Security Scan
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret scan (gitleaks)
        uses: gitleaks/gitleaks-action@v2
      - name: Vulnerability scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL,HIGH
`;
const PDB_MANIFEST = `# Generated by Lythouse — protects availability during voluntary disruptions.
# Review the selector labels to match your deployments, then apply.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lythouse-default-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: REPLACE_WITH_YOUR_APP_LABEL
`;

export function buildFixPlan(concerns) {
  const fixes = [];
  const seen = new Set();
  for (const c of concerns) {
    if (seen.has(c.cat)) continue;
    seen.add(c.cat);
    if (c.cat === 'Secrets') fixes.push({ cat: c.cat, label: 'Stop tracking secrets', desc: 'Add .env patterns to .gitignore so secrets stop being committed.', kind: 'gitignore' });
    else if (c.cat === 'Pipeline security') fixes.push({ cat: c.cat, label: 'Add CI security scanning', desc: 'Add a GitHub Actions workflow running Gitleaks + Trivy on every PR.', kind: 'security-workflow' });
    else if (c.cat === 'Resilience') fixes.push({ cat: c.cat, label: 'Add a PodDisruptionBudget', desc: 'Add a PDB manifest template to protect availability during node maintenance.', kind: 'pdb' });
  }
  return fixes;
}

// The risks we don't auto-edit (would risk breaking builds) — surfaced as guided.
export function guidedFrom(concerns) {
  return concerns.filter((c) => ['Container security', 'Reproducibility', 'Governance', 'Consistency', 'Single point of failure'].includes(c.cat))
    .map((c) => ({ label: c.label || c.cat, hint: c.fix }));
}

export async function createFixPR({ project, fixes }) {
  const parsed = parseGitUrl(project.git_url);
  if (!parsed) throw new Error('No GitHub repository URL on this project.');
  const token = project.github_token;
  if (!token) throw new Error('A GitHub token with write access is required to open a pull request. Connect this repo with a token (private repos) to enable auto-remediation.');
  const { owner, repo } = parsed;
  const base = project.git_branch || 'main';

  // 1. base sha
  const ref = await gh(`/repos/${owner}/${repo}/git/ref/heads/${base}`, token);
  const baseSha = ref.object.sha;

  // 2. new branch
  const branch = `lythouse/auto-remediation-${Math.floor(Math.random() * 1e6)}`;
  await gh(`/repos/${owner}/${repo}/git/refs`, token, { method: 'POST', body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }) });

  const applied = [];
  // 3. apply each fix as a contents commit on the branch
  for (const f of fixes) {
    if (f.kind === 'gitignore') {
      const existing = await getFile(owner, repo, '.gitignore', base, token);
      let content = existing?.content || '';
      const lines = ['', '# Added by Lythouse — do not commit secrets', '.env', '.env.*', '*.env'];
      const missing = lines.filter((l) => l && !new RegExp(`^${l.replace(/[.*]/g, '\\$&')}\\s*$`, 'm').test(content));
      if (missing.length) content = content.replace(/\s*$/, '') + '\n' + lines.join('\n') + '\n';
      await gh(`/repos/${owner}/${repo}/contents/.gitignore`, token, { method: 'PUT', body: JSON.stringify({ message: 'chore(security): ignore .env files [lythouse]', content: b64(content), branch, sha: existing?.sha }) });
      applied.push('.gitignore');
    } else if (f.kind === 'security-workflow') {
      await gh(`/repos/${owner}/${repo}/contents/.github/workflows/lythouse-security.yml`, token, { method: 'PUT', body: JSON.stringify({ message: 'ci(security): add Gitleaks + Trivy scanning [lythouse]', content: b64(SECURITY_WORKFLOW), branch }) });
      applied.push('.github/workflows/lythouse-security.yml');
    } else if (f.kind === 'pdb') {
      await gh(`/repos/${owner}/${repo}/contents/k8s/lythouse-pdb.yaml`, token, { method: 'PUT', body: JSON.stringify({ message: 'feat(resilience): add PodDisruptionBudget template [lythouse]', content: b64(PDB_MANIFEST), branch }) });
      applied.push('k8s/lythouse-pdb.yaml');
    }
  }

  // 4. open PR
  const body = `## 🤖 Lythouse Auto-Remediation\n\nThis PR was generated automatically to resolve deployment-readiness findings.\n\n### Changes\n${fixes.map((f) => `- **${f.label}** — ${f.desc}`).join('\n')}\n\n> These are safe, additive changes. Review before merging. Some findings (e.g. running containers as non-root) require human judgment and were left as guided recommendations.`;
  const pr = await gh(`/repos/${owner}/${repo}/pulls`, token, { method: 'POST', body: JSON.stringify({ title: 'Lythouse: auto-remediation for release findings', head: branch, base, body }) });
  return { url: pr.html_url, number: pr.number, applied };
}
