import { useMemo, useState } from 'react';
import { Play, ShieldCheck, TerminalSquare, CheckCircle2, XCircle, Clock3, Network, Save } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Runtime='node'|'python'|'shell';
export function TestLab({projectId,onComplete}:{projectId:string;onComplete?:()=>void}){
 const[runtime,setRuntime]=useState<Runtime>('node'),[script,setScript]=useState(''),[name,setName]=useState('Enterprise validation test'),[domains,setDomains]=useState(''),[running,setRunning]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState('');
 const allowedDomains=useMemo(()=>domains.split(',').map(x=>x.trim()).filter(Boolean),[domains]);
 const run=async()=>{if(!script.trim()||running)return;setRunning(true);setError('');setResult(null);try{const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Your session expired. Please sign in again.');const r=await fetch('/api/test-lab-run',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({projectId,name,runtime,script,allowedDomains})});const body=await r.json();if(!r.ok)throw new Error(body.detail||body.error||'Execution failed');setResult(body);onComplete?.()}catch(e:any){setError(e?.message||'Execution failed')}finally{setRunning(false)}};
 return <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
  <div className="border-b bg-slate-50/70 p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-navy-950 text-white"><TerminalSquare size={18}/></span><div><h4 className="font-bold text-navy-950">Enterprise Test Lab</h4><p className="mt-1 text-xs text-gray-500">Execute validation code in a disposable isolated sandbox and persist the evidence against this project.</p></div><span className="ml-auto inline-flex items-center gap-1 rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700"><ShieldCheck size={12}/>Isolated execution</span></div></div>
  <div className="p-4 space-y-4"><div className="grid sm:grid-cols-[1fr_150px] gap-3"><label className="text-xs font-semibold text-gray-600">Test name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-brand-400"/></label><label className="text-xs font-semibold text-gray-600">Runtime<select value={runtime} onChange={e=>setRuntime(e.target.value as Runtime)} className="mt-1.5 w-full rounded-lg border border-gray-200 bg-white px-3 py-2.5 text-sm font-normal"><option value="node">Node.js</option><option value="python">Python</option><option value="shell">Shell</option></select></label></div>
  <label className="block text-xs font-semibold text-gray-600">Allowed network domains <span className="font-normal text-gray-400">(comma separated; blank = no outbound network)</span><input value={domains} onChange={e=>setDomains(e.target.value)} placeholder="api.example.com, staging.example.com" className="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-brand-400"/></label>
  <div><div className="mb-2 flex items-center justify-between"><span className="text-xs font-semibold text-gray-600">Validation script</span><span className="text-[11px] text-gray-400">50 KB maximum · 120s execution limit</span></div><textarea value={script} onChange={e=>setScript(e.target.value)} className="min-h-64 w-full resize-y rounded-xl bg-slate-950 p-4 font-mono text-xs leading-5 text-slate-100 outline-none ring-brand-300 focus:ring-2" placeholder={runtime==='python'?"print('Run enterprise validation here')":runtime==='shell'?"set -e\necho 'Run enterprise validation here'":"console.log('Run enterprise validation here')"}/></div>
  <div className="flex flex-wrap items-center gap-2"><button onClick={run} disabled={!script.trim()||running} className="btn-primary text-xs disabled:cursor-not-allowed disabled:opacity-50"><Play size={13}/>{running?'Running in isolated sandbox…':'Run in sandbox'}</button><span className="inline-flex items-center gap-1 text-[11px] text-gray-500"><Network size={12}/>{allowedDomains.length?`${allowedDomains.length} approved network destination${allowedDomains.length===1?'':'s'}`:'Outbound network denied'}</span><span className="inline-flex items-center gap-1 text-[11px] text-gray-500"><Save size={12}/>Run + evidence persisted</span></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700"><b>Execution error:</b> {error}</div>}
  {result&&<div className={`rounded-xl border p-4 ${result.status==='passed'?'border-emerald-200 bg-emerald-50/60':'border-red-200 bg-red-50/60'}`}><div className="flex flex-wrap items-center gap-3">{result.status==='passed'?<CheckCircle2 size={18} className="text-emerald-700"/>:<XCircle size={18} className="text-red-700"/>}<b className="text-sm">{result.status==='passed'?'Validation passed':'Validation failed'}</b><span className="ml-auto inline-flex items-center gap-1 text-xs text-gray-500"><Clock3 size={12}/>{result.durationMs} ms</span></div><div className="mt-3 grid sm:grid-cols-3 gap-2 text-xs"><Metric l="Exit code" v={String(result.exitCode)}/><Metric l="Run ID" v={String(result.runId||'—').slice(0,12)}/><Metric l="Network" v={allowedDomains.length?'Restricted':'Denied'}/></div>{result.stdout&&<Output title="stdout" value={result.stdout}/>} {result.stderr&&<Output title="stderr" value={result.stderr}/>}<p className="mt-3 text-[11px] text-gray-500">This execution is stored in QA evidence and can be used by release intelligence and remediation workflows.</p></div>}
  </div></div>
}
function Metric({l,v}:{l:string;v:string}){return <div className="rounded-lg border border-black/5 bg-white/70 p-2.5"><div className="text-[10px] uppercase tracking-wide text-gray-400">{l}</div><div className="mt-1 font-semibold text-gray-700">{v}</div></div>}
function Output({title,value}:{title:string;value:string}){return <div className="mt-3"><div className="mb-1 text-[10px] font-bold uppercase tracking-wide text-gray-500">{title}</div><pre className="max-h-56 overflow-auto rounded-lg bg-slate-950 p-3 text-[11px] leading-5 text-slate-100 whitespace-pre-wrap">{value}</pre></div>}
