import{useEffect,useState}from'react';
import{PageHeader,EmptyState}from'../lib/ui';
import{Network,Plus,X,Loader as Loader2,CheckCircle2,AlertTriangle,Lock,Zap,Globe,ShieldCheck}from'lucide-react';
import{executeApiTest,listApiTestRuns,type ApiTestResult}from'../lib/apiTesting';

type ScanStatus='running'|'completed'|'failed';
type ApiScan={id:string;name:string;baseUrl:string;status:ScanStatus;result?:ApiTestResult;error?:string;createdAt:string};

export function ApiTestingPage(){
 const[scans,setScans]=useState<ApiScan[]>([]),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[expanded,setExpanded]=useState<string|null>(null),[form,setForm]=useState({name:'',baseUrl:'',timeout:'10'});
 const f=(k:'name'|'baseUrl'|'timeout',v:string)=>setForm(p=>({...p,[k]:v}));
 const load=async()=>{setLoading(true);setLoadError('');try{const runs=await listApiTestRuns();setScans(runs.map(r=>({id:r.id,name:r.name||r.targetOrigin,baseUrl:r.targetOrigin,status:r.error?'failed':'completed',result:r.error?undefined:{targetOrigin:r.targetOrigin,status:r.status||0,ok:r.ok===true,durationMs:r.durationMs||0,tls:r.tls,contentType:r.contentType,checkedAt:r.checkedAt},error:r.error||undefined,createdAt:r.createdAt})))}catch(e){setLoadError(e instanceof Error?e.message:'Could not load API test history')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const run=async(baseUrl:string,name:string,id:string=crypto.randomUUID())=>{const scan:ApiScan={id,name:name||baseUrl,baseUrl,status:'running',createdAt:new Date().toISOString()};setScans(p=>[scan,...p.filter(x=>x.id!==id)]);try{const{runId,result}=await executeApiTest(baseUrl,Math.max(1,Math.min(15,Number(form.timeout)||10))*1000,name);setScans(p=>p.map(s=>s.id===id?{...s,id:runId||id,status:'completed',result,error:undefined}:s))}catch(e){setScans(p=>p.map(s=>s.id===id?{...s,status:'failed',error:e instanceof Error?e.message:'API test failed'}:s))}};
 const startScan=async()=>{if(!form.baseUrl.trim())return;setSaving(true);const id:string=crypto.randomUUID();setCreating(false);try{await run(form.baseUrl.trim(),form.name.trim(),id)}finally{setSaving(false)}};
 const completed=scans.filter(s=>s.status==='completed'&&s.result),failed=scans.filter(s=>s.status==='failed');
 return <div>
  <PageHeader title="API Testing" description="Run controlled, authenticated checks against explicitly authorized public HTTPS API targets." actions={<button onClick={()=>setCreating(true)} className="btn-primary"><Plus size={16}/>New API test</button>}/>
  <div className="mb-6 flex items-start gap-3 rounded-xl border border-green-200 bg-green-50 p-4"><ShieldCheck size={18} className="text-green-700 shrink-0 mt-0.5"/><div className="text-sm text-green-900"><strong>Controlled execution.</strong> Results on this page come from the LytHouse API test executor and are persisted as immutable workspace evidence. Targets must be public HTTPS hosts explicitly allowlisted by the deployment administrator.</div></div>
  {loadError&&<div className="mb-4 flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-danger-600"><AlertTriangle size={16}/><div className="flex-1">{loadError}</div><button className="btn-secondary" onClick={()=>void load()}>Retry</button></div>}
  <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[
   ['Total Tests',scans.length,Globe,'bg-blue-50 text-blue-600'],['Successful',completed.filter(s=>s.result?.ok).length,CheckCircle2,'bg-green-50 text-green-600'],['Failed',failed.length+completed.filter(s=>!s.result?.ok).length,AlertTriangle,'bg-red-50 text-danger-600'],['Avg Latency',completed.length?`${Math.round(completed.reduce((a,s)=>a+(s.result?.durationMs||0),0)/completed.length)}ms`:'—',Network,'bg-brand-50 text-brand-600']
  ].map(([l,v,I,c]:any)=><div key={l} className="card flex items-center gap-3 py-3"><div className={`flex h-9 w-9 items-center justify-center rounded-lg ${c}`}><I size={16}/></div><div><p className="text-xl font-bold text-navy-900">{v}</p><p className="text-xs text-gray-500">{l}</p></div></div>)}</div>
  {loading?<div className="card flex items-center justify-center gap-2 py-10 text-sm text-gray-500"><Loader2 size={18} className="animate-spin"/>Loading verified API-test history…</div>:scans.length===0?<EmptyState icon={<Network size={22}/>} title="No API tests yet" description="Run a controlled request against an authorized API target. No sample or fabricated security results are shown." action={<button onClick={()=>setCreating(true)} className="btn-primary"><Plus size={16}/>New API test</button>}/>:<div className="space-y-3">{scans.map(scan=><div key={scan.id} className="card p-0 overflow-hidden"><button onClick={()=>setExpanded(expanded===scan.id?null:scan.id)} className="flex w-full items-center gap-4 px-5 py-4 text-left hover:bg-gray-50/50"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Network size={18}/></div><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-navy-900 text-sm">{scan.name}</span><span className={`chip border text-xs ${scan.status==='completed'&&scan.result?.ok?'bg-green-50 text-green-700 border-green-200':scan.status==='running'?'bg-blue-50 text-blue-700 border-blue-200':'bg-red-50 text-danger-600 border-red-200'}`}>{scan.status==='running'?'Testing…':scan.status==='completed'?(scan.result?.ok?'Passed':'HTTP failure'):'Failed'}</span></div><p className="text-xs text-gray-400 font-mono mt-1">{scan.baseUrl}</p></div>{scan.status==='running'?<Loader2 size={18} className="animate-spin text-blue-600"/>:scan.result?<div className="hidden sm:flex gap-4 text-right"><div><p className="text-xs text-gray-400">HTTP</p><p className="text-sm font-semibold">{scan.result.status}</p></div><div><p className="text-xs text-gray-400">Latency</p><p className="text-sm font-semibold">{scan.result.durationMs}ms</p></div><div><p className="text-xs text-gray-400">TLS</p><p className="text-sm font-semibold text-green-600">{scan.result.tls?'Yes':'No'}</p></div></div>:null}</button>{expanded===scan.id&&<div className="border-t border-gray-100 bg-gray-50/50 px-5 py-4 text-sm">{scan.error?<div className="flex items-start gap-2 text-danger-600"><AlertTriangle size={16}/><div><p>{scan.error}</p><button onClick={()=>void run(scan.baseUrl,scan.name,scan.id)} className="btn-secondary mt-3">Retry</button></div></div>:scan.result?<div className="grid gap-2 sm:grid-cols-2"><p><strong>Origin:</strong> {scan.result.targetOrigin}</p><p><strong>Checked:</strong> {new Date(scan.result.checkedAt).toLocaleString()}</p><p><strong>Content type:</strong> {scan.result.contentType||'Not provided'}</p><p><strong>Transport:</strong> {scan.result.tls?'HTTPS/TLS':'Unverified'}</p></div>:<p>Request is in progress.</p>}</div>}</div>)}</div>}
  {creating&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={()=>!saving&&setCreating(false)}><div className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl" onClick={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Configure API Test</h2><button disabled={saving} onClick={()=>setCreating(false)} className="btn-ghost p-1"><X size={16}/></button></div><div className="space-y-3"><div><label className="label">Test name</label><input className="input" value={form.name} onChange={e=>f('name',e.target.value)} placeholder="Production health endpoint"/></div><div><label className="label">Authorized HTTPS URL</label><input className="input" value={form.baseUrl} onChange={e=>f('baseUrl',e.target.value)} placeholder="https://api.example.com/health"/></div><div><label className="label">Timeout (1–15 seconds)</label><input className="input" type="number" min="1" max="15" value={form.timeout} onChange={e=>f('timeout',e.target.value)}/></div><p className="text-xs text-gray-500"><Lock size={12} className="inline mr-1"/>The backend enforces authentication, workspace membership, plan entitlement, HTTPS, private-network blocking and an administrator target allowlist.</p></div><div className="mt-5 flex justify-end gap-2"><button disabled={saving} onClick={()=>setCreating(false)} className="btn-secondary">Cancel</button><button onClick={startScan} disabled={saving||!form.baseUrl.trim()} className="btn-primary">{saving?<Loader2 size={16} className="animate-spin"/>:<Zap size={16}/>}Run test</button></div></div></div>}
 </div>
}
