// @ts-nocheck
import { useEffect, useState, useRef, type ReactNode, createContext, useContext } from 'react'
import {
  ChartBar as BarChart3, FolderGit2, Server, Boxes, LogOut, BookOpen,
  Menu, Sparkles, Scale, Rocket, ShieldCheck, Zap, Activity,
  Plug, Bug, ClipboardCheck, FileWarning, ScrollText, Users, CreditCard, Settings as SettingsIcon,
  Building2, Layers, Workflow, ChevronsUpDown, Plus, Pin, X, House, ChevronRight, FileText, Gauge, ListFilter
} from 'lucide-react'
import { supabase, type Workspace, type Organization, type WorkspacePlan, type PlanId, PLANS } from '../lib/supabase'
import { usePins, removePin, pinKey, type PinType } from '../lib/pins'
import { useRouter, Link } from '../lib/router'
import { useAuth } from '../lib/auth'
import { CommandPalette } from './CommandPalette'
import { AskAiPanel } from './AskAiPanel'

export const PlanContext = createContext<PlanId>('free')
export function usePlanId(): PlanId { return useContext(PlanContext) }

const NAV_HOME = { label: 'Home', to: '/dashboard', icon: House }
const NAV_DOCS = { label: 'Documentation', to: '/docs', icon: BookOpen }
const SECTIONS = [
  { key: 'platform', label: 'Platform', icon: Boxes, items: [
    { label: 'Projects', to: '/projects', icon: FolderGit2 },
    { label: 'Runs', to: '/runs', icon: ListFilter },
    { label: 'Workspaces', to: '/workspaces', icon: Building2 },
    { label: 'Stacks', to: '/stacks', icon: Layers },
  ] },
  { key: 'delivery', label: 'Delivery', icon: Rocket, items: [
    { label: 'Pipelines', to: '/pipeline', icon: Workflow },
    { label: 'Deployments', to: '/deployments', icon: Rocket },
    { label: 'Simulator', to: '/simulator', icon: Zap },
  ] },
  { key: 'ops', label: 'Operations', icon: BarChart3, items: [
    { label: 'Analytics', to: '/analytics', icon: Activity },
    { label: 'Findings', to: '/findings', icon: Bug },
    { label: 'Executive View', to: '/executive', icon: BarChart3 },
  ] },
  { key: 'gov', label: 'Governance', icon: ShieldCheck, items: [
    { label: 'Change Management', to: '/change-management', icon: FileText },
    { label: 'Approvals', to: '/approvals', icon: ClipboardCheck },
    { label: 'Incidents', to: '/incidents', icon: FileWarning },
    { label: 'Integrations', to: '/integrations', icon: Plug },
    { label: 'Policy Studio', to: '/policies', icon: ShieldCheck },
    { label: 'Compliance', to: '/compliance', icon: Scale },
    { label: 'Audit', to: '/audit', icon: ScrollText },
  ] },
  { key: 'config', label: 'Configuration', icon: SettingsIcon, items: [
    { label: 'Environment', to: '/environment', icon: Server },
    { label: 'Plugins', to: '/plugins', icon: Boxes },
  ] },
  { key: 'org', label: 'Organization', icon: Users, items: [
    { label: 'Organizations', to: '/organizations', icon: Building2 },
    { label: 'Team', to: '/team', icon: Users },
    { label: 'Usage', to: '/usage', icon: Gauge },
    { label: 'Plans', to: '/plans', icon: CreditCard },
    { label: 'Settings', to: '/settings', icon: SettingsIcon },
  ] },
]
const PIN_ICONS: Record<PinType, any> = {workspace:Building2,project:FolderGit2,finding:Bug,stack:Layers,environment:Server}
const TITLES: Record<string,string> = {
  '/dashboard':'Overview','/executive':'Executive View','/projects':'Projects','/runs':'Runs','/deployments':'Deployments','/simulator':'Deployment Simulator','/analytics':'Analytics','/policies':'Policy Studio','/environment':'Environment Validation','/integrations':'Integrations','/findings':'Findings','/change-management':'Change Management','/approvals':'Approvals','/compliance':'Compliance','/incidents':'Incidents','/audit':'Audit','/workspaces':'Workspaces','/organizations':'Organizations','/team':'Team','/usage':'Usage','/plans':'Plans','/settings':'Settings','/docs':'Documentation','/stacks':'Stacks','/plugins':'Plugins','/pipeline':'Release Pipeline'
}

const CSS=`
:root{--lh-bg:#fbfaff;--lh-surface:#fff;--lh-surface2:#f4f2fb;--lh-sidebar:#faf9ff;--lh-border:#d4d4d8;--lh-border2:#71717a;--lh-text:#15171a;--lh-text2:#5b616b;--lh-text3:#8a909a;--lh-accent:#7c5ce6;--lh-accent-weak:#ece8ff;--lh-accent-contrast:#fff;--lh-ring:rgba(124,92,230,.22)}
:root[data-theme="dark"]{--lh-bg:#1b1826;--lh-surface:#232030;--lh-surface2:#2a2639;--lh-sidebar:#181523;--lh-border:#52525b;--lh-border2:#71717a;--lh-text:#eeecf6;--lh-text2:#a9a5bb;--lh-text3:#746f88;--lh-accent:#a78bfa;--lh-accent-weak:rgba(167,139,250,.15);--lh-accent-contrast:#fff;--lh-ring:rgba(167,139,250,.30)}
.lh-app{min-height:100vh;background:var(--lh-bg);color:var(--lh-text)}
:root[data-theme="light"] .lh-app{background:radial-gradient(1150px 560px at 10% -10%,rgba(167,139,250,.22),transparent 60%),radial-gradient(950px 520px at 100% -4%,rgba(147,197,253,.20),transparent 55%),radial-gradient(1000px 640px at 62% 112%,rgba(240,171,214,.18),transparent 55%),#fbfaff;background-attachment:fixed}
.lh-sb{background:var(--lh-sidebar);display:flex;flex-direction:column;height:100%}.lh-brand{display:flex;align-items:center;gap:9px;padding:14px 16px;font-weight:700;font-size:16px}.lh-mk{width:27px;height:27px;border-radius:7px;background:var(--lh-accent);display:grid;place-items:center;color:#fff}.lh-wswrap{position:relative;margin:0 12px 6px}.lh-ws{width:100%;display:flex;align-items:center;gap:9px;padding:8px 10px;border:.5px solid var(--lh-border);border-radius:9px;background:var(--lh-surface);font-size:13px;color:var(--lh-text);cursor:pointer;text-align:left}.lh-ws-org{background:var(--lh-accent-weak)}.lh-ws .wa{width:22px;height:22px;border-radius:6px;background:var(--lh-accent);color:#fff;display:grid;place-items:center;font-weight:700;font-size:11px}.lh-ws .wn{font-weight:600;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.lh-wsm-ov{position:fixed;inset:0;z-index:39}.lh-wsm{position:absolute;top:calc(100% + 6px);left:0;right:0;z-index:40;background:var(--lh-surface);border:.5px solid var(--lh-border);border-radius:11px;box-shadow:0 22px 54px -18px rgba(4,8,14,.55);padding:6px}.lh-wsm-i{display:flex;align-items:center;gap:9px;width:100%;padding:8px;border-radius:8px;border:0;background:transparent;font-size:13px;color:var(--lh-text);text-align:left;cursor:pointer}.lh-wsm-i:hover{background:var(--lh-surface2)}.lh-wsm-i.sub{padding-left:20px}.lh-wsm-i .nm{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.lh-wsm-i.add{color:var(--lh-accent);font-weight:600}.lh-wsm-sep{height:1px;background:var(--lh-border);margin:6px 4px}
.lh-nav{flex:1;overflow-y:auto;padding:8px 10px 12px}.lh-item{display:flex;align-items:center;gap:10px;padding:8px 10px;border-radius:8px;font-size:13.5px;color:var(--lh-text2);font-weight:500;text-decoration:none}.lh-item:hover{background:var(--lh-surface2);color:var(--lh-text)}.lh-item.active{background:var(--lh-accent-weak);color:var(--lh-text);font-weight:600}.lh-toplink{font-weight:600}.lh-grp{margin-bottom:1px}.lh-sec2,.lh-sec.col{display:flex;align-items:center;gap:9px;width:100%;padding:9px 11px;border:0;background:none;border-radius:8px;font-size:13.5px;font-weight:700;color:var(--lh-text2);cursor:pointer;text-align:left}.lh-sec2 .gl{flex:1}.lh-sec2 .cv{transition:transform .2s}.lh-sec2.open .cv{transform:rotate(90deg)}.lh-sec2.open,.lh-sec2.has-active{color:var(--lh-text)}.lh-grp-items{display:grid;grid-template-rows:0fr;transition:grid-template-rows .22s}.lh-grp-items.open{grid-template-rows:1fr}.lh-grp-items-inner{overflow:hidden;min-height:0;margin:2px 0 4px 20px;padding-left:11px;border-left:.5px solid var(--lh-border);display:flex;flex-direction:column}.lh-pinrow .lh-pinlabel{flex:1}.lh-unpin{margin-left:auto;border:0;background:transparent;color:var(--lh-text3)}
.lh-foot{border-top:.5px solid var(--lh-border);padding:10px 12px}.lh-user{display:flex;align-items:center;gap:9px}.lh-ua{width:30px;height:30px;border-radius:50%;background:var(--lh-accent);color:#fff;display:grid;place-items:center;overflow:hidden}.lh-un{font-size:13px;font-weight:600}.lh-ue{font-size:11px;color:var(--lh-text3)}
.lh-iconbtn{width:34px;height:34px;border-radius:8px;border:.5px solid var(--lh-border);background:var(--lh-surface);color:var(--lh-text);cursor:pointer;display:grid;place-items:center;flex-shrink:0}.lh-iconbtn:hover{background:var(--lh-surface2)}.lh-mobile-menu{display:none}@media(max-width:1023px){.lh-mobile-menu{display:grid}}
.lh-tb{position:sticky;top:0;z-index:10;height:56px;display:flex;align-items:center;gap:12px;padding:0 22px;border-bottom:.5px solid var(--lh-border);background:color-mix(in srgb,var(--lh-bg) 86%,transparent);backdrop-filter:blur(10px)}.lh-title{font-size:16px;font-weight:600}.lh-plan-badge{display:inline-flex;align-items:center;gap:7px;font-size:11.5px;font-weight:700;text-transform:uppercase;padding:5px 6px 5px 10px;border-radius:20px;border:.5px solid var(--lh-border);background:var(--lh-surface2);color:var(--lh-text2);text-decoration:none}.lh-plan-badge .up{font-size:10px;text-transform:none;background:var(--lh-accent);color:#fff;padding:3px 8px;border-radius:20px}.lh-plan-badge.enterprise .up{display:none}@media(max-width:820px){.lh-plan-badge{display:none}}.lh-search{display:flex;align-items:center;gap:8px;width:260px;padding:7px 11px;border:.5px solid var(--lh-border);border-radius:9px;background:var(--lh-surface);color:var(--lh-text3);font-size:13px;cursor:pointer}.lh-kbd{margin-left:auto;font-size:11px;border:.5px solid var(--lh-border);border-radius:5px;padding:1px 5px}@media(max-width:767px){.lh-search{display:none}}
.lh-shell-body{position:relative;z-index:1}.lh-ai{position:fixed;right:22px;bottom:22px;z-index:60;display:inline-flex;align-items:center;gap:8px;padding:11px 17px;border-radius:30px;background:var(--lh-accent);color:#fff;border:0;cursor:pointer;font-weight:600}.lh-orgov{position:fixed;inset:0;z-index:120;display:flex;align-items:center;justify-content:center;padding:16px;background:rgba(5,7,10,.45)}.lh-orgm{width:min(94vw,420px);background:var(--lh-surface);border:.5px solid var(--lh-border);border-radius:16px;padding:22px}.lh-orgm input{width:100%;margin-top:14px;background:var(--lh-surface2);border:.5px solid var(--lh-border);border-radius:10px;padding:10px 12px;color:var(--lh-text)}.lh-orgm .row{display:flex;gap:9px;margin-top:16px;justify-content:flex-end}.lh-orgm .b{border-radius:10px;padding:9px 16px;border:.5px solid var(--lh-border);background:transparent;color:var(--lh-text2)}.lh-orgm .b.pri{background:var(--lh-accent);color:#fff}
`
function Brand(){return <div className="lh-brand"><span className="lh-mk"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 3v18M12 3 7 9M12 3l5 6"/><circle cx="12" cy="15" r="2.3" fill="currentColor" stroke="none"/></svg></span>LytHouse</div>}
export function AppShell({children}:{children:ReactNode}){
 const{path,navigate}=useRouter();const{user,profile,signOut}=useAuth();const[activeWs,setActiveWs]=useState<Workspace|null>(null),[orgList,setOrgList]=useState<Organization[]>([]),[activeOrg,setActiveOrg]=useState<Organization|null>(null),[orgMenuOpen,setOrgMenuOpen]=useState(false),[orgSwitchOpen,setOrgSwitchOpen]=useState(false),[modal,setModal]=useState<null|'org'|'ws'>(null),[modalName,setModalName]=useState(''),[modalBusy,setModalBusy]=useState(false),[plan,setPlan]=useState<WorkspacePlan|null>(null),[mobileOpen,setMobileOpen]=useState(false),[paletteOpen,setPaletteOpen]=useState(false),[aiOpen,setAiOpen]=useState(false),[theme,setTheme]=useState<'light'|'dark'>(()=>(localStorage.getItem('lh.theme')as any)||'light');
 const isPathActive=(to:string)=>path===to||path.startsWith(to+'/');const sectionForPath=(p:string)=>SECTIONS.find(s=>s.items.some(i=>p===i.to||p.startsWith(i.to+'/')))?.key??null;const[openSection,setOpenSection]=useState<string|null>(()=>sectionForPath(path));const[pinnedOpen,setPinnedOpen]=useState(true);const pins=usePins();const activeItemRef=useRef<HTMLAnchorElement|null>(null);
 useEffect(()=>{const a=sectionForPath(path);if(a)setOpenSection(a)},[path]);useEffect(()=>{activeItemRef.current?.scrollIntoView({block:'nearest'})},[openSection]);useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPaletteOpen(v=>!v)}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);useEffect(()=>{document.documentElement.setAttribute('data-theme',theme);document.documentElement.classList.toggle('dark',theme==='dark');localStorage.setItem('lh.theme',theme)},[theme]);
 useEffect(()=>{(async()=>{let orgs:Organization[]=[];try{const{data}=await supabase.from('organizations').select('*').order('created_at');orgs=data||[]}catch{}let cur:Organization|null=null;if(orgs.length){setOrgList(orgs);const saved=localStorage.getItem('sandbox.activeOrg');cur=orgs.find(o=>o.id===saved)??orgs[0];setActiveOrg(cur);localStorage.setItem('sandbox.activeOrg',cur.id)}const{data:ws}=await supabase.from('workspaces').select('*').order('created_at');if(!ws?.length)return;const list=cur?(ws.filter(w=>!w.organization_id||w.organization_id===cur.id)||ws):ws;const active=list.find(w=>w.id===localStorage.getItem('sandbox.activeWs'))??list[0];setActiveWs(active);localStorage.setItem('sandbox.activeWs',active.id)})()},[]);useEffect(()=>{if(activeWs)supabase.from('workspace_plans').select('*').eq('workspace_id',activeWs.id).order('created_at',{ascending:false}).limit(1).then(({data})=>data?.[0]&&setPlan(data[0]))},[activeWs]);
 const planId=(plan?.plan_id as PlanId)??'free',planInfo=PLANS[planId],pageTitle=TITLES[Object.keys(TITLES).find(k=>isPathActive(k))||'']||'LytHouse',go=()=>setMobileOpen(false),toggleTheme=()=>setTheme(t=>t==='dark'?'light':'dark');
 const createEntity=async()=>{const name=modalName.trim();if(!name)return;setModalBusy(true);if(modal==='org'){const{data,error}=await supabase.rpc('create_organization_with_workspace',{p_name:name,p_description:null});if(!error&&data){localStorage.setItem('sandbox.activeOrg',String(data.organization_id));localStorage.setItem('sandbox.activeWs',String(data.workspace_id));window.location.assign('/dashboard')}}else if(activeOrg){const{data,error}=await supabase.rpc('create_workspace',{p_organization_id:activeOrg.id,p_name:name,p_description:null});if(!error&&data){localStorage.setItem('sandbox.activeWs',String(data));window.location.assign('/dashboard')}}setModalBusy(false)};
 const Sidebar=<div className="lh-sb"><Brand/><div className="lh-wswrap"><button className="lh-ws lh-ws-org" onClick={()=>setOrgMenuOpen(v=>!v)}><span className="wa">{activeOrg?(activeOrg.name||'O')[0].toUpperCase():<Building2 size={14}/>}</span><span className="wn">{activeOrg?.name||'Organizations'}</span><ChevronsUpDown size={14}/></button>{orgMenuOpen&&<><div className="lh-wsm-ov" onClick={()=>setOrgMenuOpen(false)}/><div className="lh-wsm">{orgList.map(o=><button key={o.id} className="lh-wsm-i" onClick={()=>{localStorage.setItem('sandbox.activeOrg',o.id);localStorage.removeItem('sandbox.activeWs');window.location.assign('/dashboard')}}><span className="nm">{o.name}</span></button>)}<div className="lh-wsm-sep"/><button className="lh-wsm-i add" onClick={()=>{setOrgMenuOpen(false);setModalName('');setModal('org')}}><Plus size={13}/> Create organization</button></div></>}</div><nav className="lh-nav"><Link to={NAV_HOME.to} onClick={go} className={`lh-item lh-toplink ${isPathActive(NAV_HOME.to)?'active':''}`}><House size={16}/>Home</Link>{pins.length>0&&<div className="lh-grp"><button className="lh-sec col" onClick={()=>setPinnedOpen(v=>!v)}><Pin size={11}/>Pinned</button>{pinnedOpen&&pins.map(p=>{const I=PIN_ICONS[p.type]||FolderGit2;return <Link key={pinKey(p.type,p.id)} to={p.to} onClick={go} className="lh-item lh-pinrow"><I size={15}/><span className="lh-pinlabel">{p.label}</span><button className="lh-unpin" onClick={e=>{e.preventDefault();removePin(p.type,p.id)}}><X size={12}/></button></Link>})}</div>}{SECTIONS.map(s=>{const open=openSection===s.key,active=s.items.some(i=>isPathActive(i.to));return <div key={s.key} className="lh-grp"><button className={`lh-sec2 ${open?'open':''} ${active?'has-active':''}`} onClick={()=>setOpenSection(open?null:s.key)}><s.icon size={15}/><span className="gl">{s.label}</span><ChevronRight size={14} className="cv"/></button><div className={`lh-grp-items ${open?'open':''}`}><div className="lh-grp-items-inner">{s.items.map(i=><Link key={i.to} to={i.to} onClick={go} className={`lh-item ${isPathActive(i.to)?'active':''}`}><i.icon size={15}/>{i.label}</Link>)}</div></div></div>})}<Link to="/docs" onClick={go} className="lh-item lh-toplink"><BookOpen size={16}/>Documentation</Link></nav><div className="lh-foot"><div className="lh-user"><span className="lh-ua">{profile?.avatar_url?<img src={profile.avatar_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:(profile?.full_name||user?.email||'U')[0].toUpperCase()}</span><div style={{flex:1,minWidth:0}}><div className="lh-un">{profile?.full_name||'My Account'}</div><div className="lh-ue">{user?.email||''}</div></div><button onClick={()=>signOut()} className="lh-iconbtn"><LogOut size={14}/></button></div></div></div>;
 return <div className="lh-app"><style>{CSS}</style><aside className="fixed left-0 top-0 z-20 hidden h-screen w-64 lg:block">{Sidebar}</aside>{mobileOpen&&<div className="fixed inset-0 z-40 bg-black/40 lg:hidden" onClick={()=>setMobileOpen(false)}/>}<aside className={`fixed left-0 top-0 z-50 h-screen w-64 transition-transform lg:hidden ${mobileOpen?'translate-x-0':'-translate-x-full'}`}>{Sidebar}</aside><div className="lg:pl-64 lh-shell-body"><header className="lh-tb"><button onClick={()=>setMobileOpen(true)} className="lh-iconbtn lh-mobile-menu" aria-label="Open navigation"><Menu size={18}/></button><span className="lh-title">{pageTitle}</span><Link to="/plans" className={`lh-plan-badge ${planId}`}>{planInfo.name}{planId!=='enterprise'&&<span className="up">Upgrade</span>}</Link><button type="button" className="lh-search" onClick={()=>setPaletteOpen(true)}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>Search…<span className="lh-kbd">⌘K</span></button><div style={{flex:1}}/><button className="lh-iconbtn" title="Toggle theme" onClick={toggleTheme}>{theme==='dark'?'☀':'☾'}</button><button className="lh-iconbtn" title="Notifications">♢</button></header><main className="mx-auto max-w-7xl px-4 py-8" style={{color:'var(--lh-text)'}}><PlanContext.Provider value={planId}>{children}</PlanContext.Provider></main></div><button className="lh-ai" onClick={()=>setAiOpen(true)}><Sparkles size={16}/><span>Ask AI</span></button><AskAiPanel open={aiOpen} onClose={()=>setAiOpen(false)}/>{modal&&<div className="lh-orgov" onClick={()=>!modalBusy&&setModal(null)}><div className="lh-orgm" onClick={e=>e.stopPropagation()}><h3>{modal==='org'?'Create organization':'Create workspace'}</h3><input autoFocus value={modalName} onChange={e=>setModalName(e.target.value)} placeholder={modal==='org'?'Acme Inc':'Platform Team'}/><div className="row"><button className="b" onClick={()=>setModal(null)}>Cancel</button><button className="b pri" onClick={createEntity} disabled={modalBusy||!modalName.trim()}>{modalBusy?'Creating…':'Create'}</button></div></div></div>}<CommandPalette open={paletteOpen} onClose={()=>setPaletteOpen(false)} theme={theme} onToggleTheme={toggleTheme} onSignOut={()=>signOut()}/></div>
}
