// @ts-nocheck
import{useEffect,useState,useCallback,useRef}from'react';
import{supabase}from'../lib/supabase';
import{useAuth}from'../lib/auth';
import{useRouter}from'../lib/router';
import{Spinner,timeAgo,EmptyState}from'../lib/ui';
import{
  ChevronLeft,Calendar,Send,CheckCircle2,XCircle,MessageSquare,GitBranch,
}from'lucide-react';
import{jsPDF}from'jspdf';
import{generateDeploymentReview}from'../workspace/changeAI';
import{
  RISK_CLS,STATUS_CLS,STATUS_LABEL,
  ExecutiveSummaryCard,ImpactAnalysisCard,RiskAssessmentCard,ReadinessChecklist,
  RollbackPlanCard,DeploymentTimeline,WhatsChangingCard,PreviousChangesCard,
  ReviewerCommentsCard,ExportToolbar,
}from'./changeManagementUI';

// ── AI Deployment Review Center ─────────────────────────────────────────────
// The page a change request lands on right after it's generated. This is
// the heart of the feature: instead of a form dump, it reads like a senior
// engineer already reviewed the deployment — executive summary, impact
// analysis, a real risk dashboard with trend, a dynamic readiness checklist,
// a DevOps-style rollback runbook, reviewer notes, a plain-English "what's
// changing", a timeline, similar past deployments, and the approval flow.
//
// AI content is generated client-side against the already-deployed ai-chat
// Edge Function (see ../workspace/changeAI.ts) — grounded ONLY in this
// change request's real validation/findings/history, exactly like every
// other AI feature in this app. It's generated fresh on load and cached in
// component state; the page also makes a best-effort attempt to persist it
// back onto the change_requests row (ai_summary / ai_impact / etc. columns)
// so a future visit can skip regenerating — but never depends on that
// persistence succeeding, so the page works whether or not that schema
// migration has been applied yet.

function riskFromCounts(v:any):string{
  if(!v)return'unknown';
  if((v.critical_count||0)>0)return'critical';
  if((v.high_count||0)>0)return'high';
  if((v.medium_count||0)>0)return'medium';
  return'low';
}

function buildMarkdown(cr:any,projectName:string,crNumber:number,findings:any[]):string{
  const L:string[]=[];
  L.push(`# ${cr.title||'Change request'}`,'');
  L.push(`**Change request:** CR-${crNumber}  `);
  L.push(`**Project:** ${projectName}  `);
  L.push(`**Environment:** ${cr.environment}  `);
  L.push(`**Risk level:** ${(cr.risk_level||'unknown').toUpperCase()}  `);
  L.push(`**Status:** ${STATUS_LABEL[cr.status]||cr.status}  `);
  L.push(`**Version:** v${cr.revision||1}  `);
  if(cr.scheduled_start)L.push(`**Deployment window:** ${new Date(cr.scheduled_start).toLocaleString()} → ${cr.scheduled_end?new Date(cr.scheduled_end).toLocaleString():'—'}  `);
  L.push('');
  if(cr.ai_summary)L.push('## AI Executive Summary','',cr.ai_summary,'');
  L.push('## Summary','',cr.summary||'—','');
  L.push('## Scope of Change','',(cr.scope&&cr.scope.length?cr.scope:['General']).map((s:string)=>`- ${s}`).join('\n'),'');
  if(cr.ai_impact&&cr.ai_impact.length)L.push('## Impact Analysis','',cr.ai_impact.map((i:any)=>`- **${i.component}** — ${i.reason}`).join('\n'),'');
  L.push('## Risk Assessment','',cr.risk_assessment||'—','');
  L.push('## Rollback Plan','',cr.rollback_plan||'—','');
  if(cr.ai_rollback&&cr.ai_rollback.steps&&cr.ai_rollback.steps.length){
    const rb=cr.ai_rollback;
    L.push('### AI-Drafted Rollback Detail','',rb.steps.map((s:string,i:number)=>`${i+1}. ${s}`).join('\n'));
    if(rb.estimated_duration)L.push(`\n**Estimated duration:** ${rb.estimated_duration}`);
    if(rb.dependencies?.length)L.push(`**Dependencies:** ${rb.dependencies.join(', ')}`);
    if(rb.approvals_required?.length)L.push(`**Approvals required:** ${rb.approvals_required.join(', ')}`);
    L.push('');
  }
  if(cr.ai_reviewer_comments&&cr.ai_reviewer_comments.length)L.push('## AI Reviewer Comments','',cr.ai_reviewer_comments.map((c:string)=>`- ${c}`).join('\n'),'');
  if(findings&&findings.length)L.push('## Open Critical / High Findings','',findings.map((f:any)=>`- [${f.severity.toUpperCase()}] ${f.title}${f.recommendation?` — ${f.recommendation}`:''}`).join('\n'),'');
  L.push('## Approval','',`Sent to: ${cr.approver_name||'—'}${cr.approver_email?` (${cr.approver_email})`:''}`,`Decision: ${cr.decided_at?`${STATUS_LABEL[cr.status]||cr.status} on ${new Date(cr.decided_at).toLocaleString()}`:'Not yet decided'}`,'');
  L.push('---',`*Generated by LytHouse${cr.ai_summary?' AI':''} on ${new Date().toLocaleString()}*`);
  return L.join('\n');
}
function downloadMarkdown(filename:string,content:string){
  const blob=new Blob([content],{type:'text/markdown'});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);
}

function downloadChangePlanPdf(cr:any,projectName:string,crNumber:number,findings:any[]){
  const doc=new jsPDF({unit:'pt',format:'a4'});
  const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();

  doc.setFillColor(15,15,23);doc.rect(0,0,pw,ph,'F');
  doc.setFillColor(124,92,230);doc.roundedRect(pw/2-24,100,48,48,12,12,'F');
  doc.setDrawColor(255,255,255);doc.setLineWidth(3);
  doc.line(pw/2-13,124,pw/2-4,134);doc.line(pw/2-4,134,pw/2+14,110);
  doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(15);
  doc.text('LytHouse',pw/2,172,{align:'center'});
  doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(170,165,200);
  doc.text(`CHANGE MANAGEMENT REPORT · CR-${crNumber}`,pw/2,188,{align:'center'});

  doc.setFont('helvetica','bold');doc.setFontSize(24);doc.setTextColor(255,255,255);
  const titleLines=doc.splitTextToSize(cr.title||'Change request',pw-140);
  let cy=250;
  for(const ln of titleLines){doc.text(ln,pw/2,cy,{align:'center'});cy+=30;}

  const riskColorMap:Record<string,[number,number,number]>={critical:[220,38,38],high:[217,119,6],medium:[124,92,230],low:[16,163,74],unknown:[110,110,125]};
  const rc=riskColorMap[cr.risk_level]||riskColorMap.unknown;
  doc.setFillColor(rc[0],rc[1],rc[2]);doc.roundedRect(pw/2-58,cy+14,116,26,13,13,'F');
  doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.setTextColor(255,255,255);
  doc.text(`${(cr.risk_level||'unknown').toUpperCase()} RISK`,pw/2,cy+31,{align:'center'});

  const coverRows:[string,string][]=[
    ['Project',projectName],
    ['Environment',cr.environment],
    ['Deployment window',cr.scheduled_start?`${new Date(cr.scheduled_start).toLocaleString()}  →  ${cr.scheduled_end?new Date(cr.scheduled_end).toLocaleString():'—'}`:'Not yet scheduled'],
    ['Approval status',STATUS_LABEL[cr.status]||cr.status],
    ['Prepared by',cr.ai_summary?'LytHouse AI (grounded in real validation data)':'LytHouse'],
    ['Date generated',new Date().toLocaleString()],
    ['Version',`v${cr.revision||1}`],
  ];
  let ry=cy+78;
  doc.setFont('helvetica','normal');doc.setFontSize(9.5);
  for(const[label,value]of coverRows){
    doc.setTextColor(150,145,175);doc.text(label.toUpperCase(),pw/2-165,ry);
    doc.setTextColor(240,240,245);
    const lines=doc.splitTextToSize(String(value),280);
    doc.text(lines,pw/2-15,ry);
    ry+=Math.max(17,lines.length*12.5);
  }
  doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(120,115,145);
  doc.text('Generated automatically by LytHouse, grounded in this project\'s real validation data.',pw/2,ph-40,{align:'center'});

  doc.addPage();
  let y=0;
  doc.setFillColor(20,20,30);doc.rect(0,0,pw,86,'F');
  doc.setFillColor(124,92,230);doc.roundedRect(40,24,38,38,10,10,'F');
  doc.setDrawColor(255,255,255);doc.setLineWidth(2.4);
  doc.line(51,44,58,52);doc.line(58,52,68,36);
  doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(18);
  doc.text('LytHouse',92,42);
  doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(200,195,230);
  doc.text(`Change Management Report · CR-${crNumber}`,92,60);
  doc.setFontSize(8);doc.setTextColor(160,160,180);
  doc.text(`Generated ${new Date().toLocaleString()}`,pw-40,60,{align:'right'});

  y=120;
  const left=40,right=pw-40,width=right-left;
  doc.setTextColor(20,20,30);doc.setFont('helvetica','bold');doc.setFontSize(16);
  doc.text(cr.title||'Change request',left,y);
  y+=22;

  doc.setFont('helvetica','normal');doc.setFontSize(9.5);doc.setTextColor(90,90,105);
  doc.text(`Project: ${projectName}`,left,y);
  doc.text(`Environment: ${cr.environment}`,left+220,y);
  y+=16;
  doc.text(`Status: ${STATUS_LABEL[cr.status]||cr.status}`,left,y);
  doc.text(`Risk level: ${(cr.risk_level||'unknown').toUpperCase()}`,left+220,y);
  y+=16;
  doc.text(`Requested: ${cr.created_at?new Date(cr.created_at).toLocaleString():'—'}`,left,y);
  y+=24;

  const section=(title:string,body:string)=>{
    if(y>760){doc.addPage();y=50;}
    doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(20,20,30);
    doc.text(title,left,y);y+=16;
    doc.setFont('helvetica','normal');doc.setFontSize(9.5);doc.setTextColor(60,60,75);
    const lines=doc.splitTextToSize(body||'—',width);
    for(const ln of lines){
      if(y>780){doc.addPage();y=50;}
      doc.text(ln,left,y);y+=13.5;
    }
    y+=12;
  };

  if(cr.ai_summary)section('AI executive summary',cr.ai_summary);
  section('Summary',cr.summary);
  section('Scope of change',(cr.scope&&cr.scope.length?cr.scope:['General']).map((s:string)=>`• ${s}`).join('\n'));
  if(cr.ai_impact&&cr.ai_impact.length)section('Impact analysis',cr.ai_impact.map((i:any)=>`• ${i.component}: ${i.reason}`).join('\n'));
  section('Risk assessment',cr.risk_assessment);
  section('Rollback plan',cr.rollback_plan);
  if(cr.ai_rollback&&cr.ai_rollback.steps&&cr.ai_rollback.steps.length){
    const rb=cr.ai_rollback;
    section('AI-drafted rollback detail',
      rb.steps.map((s:string,i:number)=>`${i+1}. ${s}`).join('\n')+
      (rb.estimated_duration?`\n\nEstimated duration: ${rb.estimated_duration}`:'')+
      (rb.dependencies?.length?`\nDependencies: ${rb.dependencies.join(', ')}`:'')+
      (rb.approvals_required?.length?`\nApprovals required: ${rb.approvals_required.join(', ')}`:''));
  }
  if(cr.ai_reviewer_comments&&cr.ai_reviewer_comments.length)section('AI reviewer comments',cr.ai_reviewer_comments.map((c:string)=>`• ${c}`).join('\n'));

  if(cr.validation_snapshot&&Object.keys(cr.validation_snapshot).length){
    const s=cr.validation_snapshot;
    section('Validation snapshot (at time of drafting)',
      `Risk score: ${s.risk_score??'—'}/100  ·  Findings: ${s.total_findings??0} total (${s.critical_count??0} critical, ${s.high_count??0} high, ${s.medium_count??0} medium, ${s.low_count??0} low)\nCommit: ${s.commit_sha?String(s.commit_sha).slice(0,10):'—'}  ·  Validated: ${s.completed_at?new Date(s.completed_at).toLocaleString():'—'}`);
  }

  if(findings&&findings.length){
    section('Open critical / high findings referenced',
      findings.map((f:any)=>`• [${f.severity.toUpperCase()}] ${f.title}${f.recommendation?` — ${f.recommendation}`:''}`).join('\n'));
  }

  if(cr.scheduled_start||cr.scheduled_end){
    section('Scheduled window',
      `${cr.scheduled_start?new Date(cr.scheduled_start).toLocaleString():'—'}  →  ${cr.scheduled_end?new Date(cr.scheduled_end).toLocaleString():'—'}`);
  }

  section('Approval',
    `Sent to: ${cr.approver_name||'—'}${cr.approver_email?` (${cr.approver_email})`:''}\nDecision: ${cr.decided_at?`${STATUS_LABEL[cr.status]||cr.status} on ${new Date(cr.decided_at).toLocaleString()}`:'Not yet decided'}${cr.decision_note?`\nNote: ${cr.decision_note}`:''}`);

  doc.save(`cr-${crNumber}-${(cr.title||'change-request').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.pdf`);
}

export function ChangeRequestDetailPage({id}:{id:string}){
  const{user}=useAuth();
  const{navigate}=useRouter();
  const[loading,setLoading]=useState(true);
  const[notFound,setNotFound]=useState(false);
  const[cr,setCr]=useState<any|null>(null);
  const[project,setProject]=useState<any|null>(null);
  const[crNumber,setCrNumber]=useState(0);
  const[comments,setComments]=useState<any[]>([]);
  const[commentText,setCommentText]=useState('');
  const[saving,setSaving]=useState(false);
  const[activeSteps,setActiveSteps]=useState<any[]>([]);
  const[activeFindings,setActiveFindings]=useState<any[]>([]);
  const[stepsLoading,setStepsLoading]=useState(false);
  const[previous,setPrevious]=useState<any[]>([]);
  const[trendPoints,setTrendPoints]=useState<any[]>([]);
  const[aiData,setAiData]=useState<any|null>(null);
  const[aiLoading,setAiLoading]=useState(false);
  const[aiUnavailable,setAiUnavailable]=useState('');
  const generatedRef=useRef<string>('');

  const load=useCallback(async()=>{
    setLoading(true);setNotFound(false);
    const{data:crRow}=await supabase.from('change_requests').select('*').eq('id',id).single();
    if(!crRow){setNotFound(true);setLoading(false);return;}
    setCr(crRow);

    const[{data:proj},{data:cm},{data:prev},{data:trend}]=await Promise.all([
      supabase.from('projects').select('*').eq('id',crRow.project_id).single(),
      supabase.from('change_request_comments').select('*').eq('change_request_id',id).order('created_at'),
      supabase.from('change_requests').select('*').eq('project_id',crRow.project_id).neq('id',id).order('created_at',{ascending:false}).limit(5),
      supabase.from('validations').select('risk_score,completed_at').eq('project_id',crRow.project_id).eq('status','completed').order('completed_at',{ascending:false}).limit(8),
    ]);
    setProject(proj||null);
    setComments(cm??[]);
    setPrevious(prev??[]);
    setTrendPoints((trend??[]).slice().reverse());

    const{count}=await supabase.from('change_requests').select('id',{count:'exact',head:true}).eq('workspace_id',crRow.workspace_id).lte('created_at',crRow.created_at);
    setCrNumber(count||1);

    if(crRow.validation_id){
      setStepsLoading(true);
      const[{data:steps},{data:finds}]=await Promise.all([
        supabase.from('validation_steps').select('*').eq('validation_id',crRow.validation_id).order('step_index'),
        supabase.from('findings').select('*').eq('validation_id',crRow.validation_id).order('severity'),
      ]);
      setActiveSteps(steps??[]);setActiveFindings(finds??[]);
      setStepsLoading(false);
    }else{
      setActiveSteps([]);setActiveFindings([]);
    }

    // If this record already carries persisted AI content (from a prior visit,
    // once the ai_* columns exist), use it and skip regenerating.
    if(crRow.ai_generated_at){
      setAiData({summary:crRow.ai_summary,impact:crRow.ai_impact||[],risk_contributors:crRow.ai_risk_contributors||[],reviewer_comments:crRow.ai_reviewer_comments||[],rollback:crRow.ai_rollback||{}});
    }
    setLoading(false);
  },[id]);
  useEffect(()=>{load();},[load]);

  // Auto-generate the AI review once real evidence has loaded, exactly once
  // per change request — this is what makes opening a freshly-generated
  // change request feel like it's already been reviewed.
  useEffect(()=>{
    if(!cr||loading||stepsLoading)return;
    if(cr.ai_generated_at)return; // already have persisted content
    if(generatedRef.current===cr.id)return;
    generatedRef.current=cr.id;
    runReview();
    // eslint-disable-next-line
  },[cr,loading,stepsLoading]);

  const runReview=async()=>{
    if(!cr)return;
    setAiLoading(true);setAiUnavailable('');
    const evidence={
      changeRequest:{title:cr.title,environment:cr.environment,riskLevel:cr.risk_level,status:cr.status,scope:cr.scope,summary:cr.summary,riskAssessment:cr.risk_assessment,rollbackPlan:cr.rollback_plan,scheduledStart:cr.scheduled_start,scheduledEnd:cr.scheduled_end,approverName:cr.approver_name,approverEmail:cr.approver_email},
      project:project?{name:project.name,branch:project.git_branch,language:project.language,framework:project.framework}:null,
      validation:cr.validation_snapshot&&Object.keys(cr.validation_snapshot).length?cr.validation_snapshot:null,
      findings:activeFindings.map((f:any)=>({category:f.category,severity:f.severity,title:f.title,file:f.file_path,recommendation:f.recommendation,status:f.status})),
      validationSteps:activeSteps.map((s:any)=>({name:s.name,status:s.status,detail:s.detail})),
      previousChangeRequestsForThisProject:previous.map((h:any)=>({title:h.title,riskLevel:h.risk_level,status:h.status,environment:h.environment,createdAt:h.created_at,decidedAt:h.decided_at,decisionNote:h.decision_note,rollbackRequired:h.status==='rolled_back'})),
    };
    const res=await generateDeploymentReview(evidence);
    if(!res.ok){setAiUnavailable(res.error||'AI insights are unavailable right now.');setAiLoading(false);return;}
    setAiData(res.data);
    setAiLoading(false);
    // Best-effort persistence — silently ignored if the ai_* columns (or the
    // rolled_back status value) don't exist in this database yet.
    supabase.from('change_requests').update({
      ai_summary:res.data.summary,ai_impact:res.data.impact,ai_risk_contributors:res.data.risk_contributors,
      ai_reviewer_comments:res.data.reviewer_comments,ai_rollback:res.data.rollback,ai_generated_at:new Date().toISOString(),
    }).eq('id',cr.id).then(()=>{});
  };

  const saveField=async(patch:Record<string,any>)=>{
    if(!cr)return;
    setSaving(true);
    const{data,error}=await supabase.from('change_requests').update({...patch,revision:(cr.revision||1)+1}).eq('id',cr.id).select().single();
    if(data)setCr(data);
    else if(error){
      // revision column may not exist yet on this database — retry without it
      const retry=await supabase.from('change_requests').update(patch).eq('id',cr.id).select().single();
      if(retry.data)setCr(retry.data);
    }
    setSaving(false);
  };
  const decide=async(status:'approved'|'rejected',note:string)=>{
    await saveField({status,decided_by:user?.id||null,decided_at:new Date().toISOString(),decision_note:note||null});
  };
  const markOutcome=async(status:'completed'|'rolled_back')=>{
    await saveField({status});
  };
  const addComment=async()=>{
    if(!cr||!commentText.trim())return;
    const{data}=await supabase.from('change_request_comments').insert({change_request_id:cr.id,workspace_id:cr.workspace_id,body:commentText.trim()}).select().single();
    if(data){setComments(c=>[...c,data]);setCommentText('');}
  };

  if(loading)return<div className="flex justify-center py-24"><Spinner size={28}/></div>;
  if(notFound||!cr)return<div className="max-w-2xl">
    <EmptyState icon={<GitBranch size={22}/>} title="Change request not found" description="It may have been deleted, or you don't have access to it." action={<button onClick={()=>navigate('/change-management')} className="btn-primary">Back to Change Management</button>}/>
  </div>;

  const crView={...cr,...(aiData?{ai_summary:aiData.summary,ai_impact:aiData.impact,ai_risk_contributors:aiData.risk_contributors,ai_reviewer_comments:aiData.reviewer_comments,ai_rollback:aiData.rollback,ai_generated_at:cr.ai_generated_at||new Date().toISOString()}:{})};
  const projectName=project?.name||'—';
  const readiness=cr.validation_snapshot&&typeof cr.validation_snapshot.risk_score==='number'?Math.max(0,100-cr.validation_snapshot.risk_score):null;
  const relatedFindings=activeFindings.filter((f:any)=>f.status==='open'&&(f.severity==='critical'||f.severity==='high'));

  return<div className="max-w-4xl">
    <button onClick={()=>navigate('/change-management')} className="mb-4 inline-flex items-center gap-1 text-xs font-medium text-gray-500 hover:text-navy-700"><ChevronLeft size={14}/>Back to change requests</button>

    {/* Header */}
    <div className="card mb-5">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <p className="text-2xs font-semibold uppercase tracking-wide text-brand-600">CR-{crNumber}</p>
          <h1 className="mt-0.5 text-lg font-bold text-navy-900">{cr.title}</h1>
          <p className="mt-1 flex flex-wrap items-center gap-x-1.5 gap-y-0.5 text-xs text-gray-500">
            <span className="font-medium text-navy-700">{projectName}</span>·<span>{cr.environment}</span>·<span>v{cr.revision||1}</span>·<span>requested {timeAgo(cr.created_at)}</span>
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <span className={`chip ${RISK_CLS[cr.risk_level]||RISK_CLS.unknown}`}>{(cr.risk_level||'unknown').toUpperCase()} risk</span>
          <span className={`chip ${STATUS_CLS[cr.status]||STATUS_CLS.draft}`}>{STATUS_LABEL[cr.status]||cr.status}</span>
        </div>
      </div>
      <div className="mt-4 grid grid-cols-2 gap-3 border-t border-gray-100 pt-4 sm:grid-cols-4">
        <div><p className="text-2xs text-gray-400">Deployment window</p><p className="mt-0.5 text-xs font-medium text-navy-800">{cr.scheduled_start?new Date(cr.scheduled_start).toLocaleDateString():'Not scheduled'}</p></div>
        <div><p className="text-2xs text-gray-400">Risk score</p><p className="mt-0.5 text-xs font-medium text-navy-800">{cr.validation_snapshot?.risk_score??'—'}/100</p></div>
        <div><p className="text-2xs text-gray-400">Deployment readiness</p><p className="mt-0.5 text-xs font-medium text-navy-800">{readiness===null?'—':`${readiness}%`}</p></div>
        <div><p className="text-2xs text-gray-400">Status</p><p className="mt-0.5 text-xs font-medium text-navy-800">{STATUS_LABEL[cr.status]||cr.status}</p></div>
      </div>
    </div>

    <div className="space-y-5">
      <ExecutiveSummaryCard cr={crView} onGenerate={runReview} loading={aiLoading} unavailable={aiUnavailable}/>

      <div className="grid gap-5 lg:grid-cols-2">
        <RiskAssessmentCard cr={crView} trendPoints={trendPoints}/>
        <ReadinessChecklist cr={cr} steps={activeSteps} stepsLoading={stepsLoading}/>
      </div>

      <div className="grid gap-5 lg:grid-cols-2">
        <ImpactAnalysisCard cr={crView} onGenerate={runReview} loading={aiLoading}/>
        <WhatsChangingCard steps={activeSteps} findings={activeFindings}/>
      </div>

      <div className="grid gap-5 lg:grid-cols-2">
        <DeploymentTimeline cr={cr}/>
        <PreviousChangesCard items={previous} loading={false} title="Similar previous deployments"/>
      </div>

      <RollbackPlanCard cr={crView} onGenerate={runReview} loading={aiLoading}/>
      <ReviewerCommentsCard cr={crView} onGenerate={runReview} loading={aiLoading}/>

      {/* Approval */}
      <div className="card">
        <p className="mb-3.5 text-sm font-semibold text-navy-900">Approval</p>
        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <label className="label">Approver name</label>
            <input className="input" defaultValue={cr.approver_name||''} placeholder="e.g. VP Engineering" onBlur={(e)=>saveField({approver_name:e.target.value||null})}/>
          </div>
          <div>
            <label className="label">Approver email</label>
            <input className="input" defaultValue={cr.approver_email||''} placeholder="approver@company.com" onBlur={(e)=>saveField({approver_email:e.target.value||null})}/>
          </div>
          <div>
            <label className="label flex items-center gap-1"><Calendar size={12}/>Scheduled start</label>
            <input type="datetime-local" className="input" defaultValue={cr.scheduled_start?.slice(0,16)||''} onBlur={(e)=>saveField({scheduled_start:e.target.value||null})}/>
          </div>
          <div>
            <label className="label flex items-center gap-1"><Calendar size={12}/>Scheduled end</label>
            <input type="datetime-local" className="input" defaultValue={cr.scheduled_end?.slice(0,16)||''} onBlur={(e)=>saveField({scheduled_end:e.target.value||null})}/>
          </div>
        </div>

        {cr.status==='pending_approval'&&<div className="mt-4"><DecisionBar onDecide={decide}/></div>}
        {cr.decided_at&&(
          <div className="mt-4 rounded-xl border border-[#18181b] p-3 text-xs text-gray-600">
            {STATUS_LABEL[cr.status]} on {new Date(cr.decided_at).toLocaleString()}{cr.decision_note?` — "${cr.decision_note}"`:''}
          </div>
        )}
        {cr.status==='approved'&&(
          <div className="mt-4 flex flex-wrap items-center gap-2 rounded-xl border border-green-200 bg-green-50 p-3.5">
            <p className="mr-auto text-xs font-medium text-green-700">Approved — once it ships, record the real outcome.</p>
            <button onClick={()=>markOutcome('completed')} className="btn-secondary text-xs flex items-center gap-1.5"><CheckCircle2 size={12}/>Mark completed</button>
            <button onClick={()=>markOutcome('rolled_back')} className="btn-secondary text-xs flex items-center gap-1.5"><XCircle size={12}/>Mark rolled back</button>
          </div>
        )}
        <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-gray-100 pt-4">
          {cr.status==='draft'&&(
            <button onClick={()=>saveField({status:'pending_approval'})} className="btn-brand text-xs flex items-center gap-1.5"><Send size={12}/>Send for approval</button>
          )}
        </div>
      </div>

      <ExportToolbar
        summaryText={crView.ai_summary||cr.summary||''}
        onExportPdf={()=>downloadChangePlanPdf(crView,projectName,crNumber,relatedFindings)}
        onExportMarkdown={()=>downloadMarkdown(`cr-${crNumber}-${(cr.title||'change-request').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.md`,buildMarkdown(crView,projectName,crNumber,relatedFindings))}
      />

      {/* Change details (editable record) */}
      <div className="card">
        <p className="mb-3.5 text-sm font-semibold text-navy-900">Change details</p>
        <div className="space-y-5">
          <Field label="Summary" value={cr.summary} onSave={(v)=>saveField({summary:v})} disabled={saving}/>
          <div>
            <label className="label">Scope of change</label>
            <div className="flex flex-wrap gap-1.5">
              {(cr.scope||[]).length===0&&<span className="text-xs text-gray-400">General</span>}
              {(cr.scope||[]).map((s:string)=><span key={s} className="chip bg-gray-100 text-gray-600 border border-[#18181b]">{s}</span>)}
            </div>
          </div>
          <Field label="Risk assessment (editable record)" value={cr.risk_assessment} onSave={(v)=>saveField({risk_assessment:v})} multiline disabled={saving}/>
          <Field label="Rollback plan (editable record)" value={cr.rollback_plan} onSave={(v)=>saveField({rollback_plan:v})} multiline disabled={saving}/>
        </div>
      </div>

      {/* Discussion */}
      <div className="card">
        <p className="mb-3 flex items-center gap-1.5 text-sm font-semibold text-navy-900"><MessageSquare size={14}/>Discussion</p>
        <div className="space-y-3">
          {comments.length===0&&<p className="text-xs text-gray-400">No comments yet — coordinate the change with your team here.</p>}
          {comments.map((c:any)=>(
            <div key={c.id} className="rounded-xl bg-gray-50 px-3.5 py-2.5">
              <p className="text-sm text-navy-800">{c.body}</p>
              <p className="mt-1 text-[11px] text-gray-400">{timeAgo(c.created_at)}</p>
            </div>
          ))}
        </div>
        <div className="mt-3 flex gap-2">
          <input value={commentText} onChange={(e)=>setCommentText(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter')addComment();}} className="input" placeholder="Add a note for your team…"/>
          <button onClick={addComment} className="btn-secondary text-xs shrink-0">Post</button>
        </div>
      </div>
    </div>
  </div>;
}

function Field({label,value,onSave,multiline,disabled}:{label:string;value:string;onSave:(v:string)=>void;multiline?:boolean;disabled?:boolean}){
  const[v,setV]=useState(value||'');
  useEffect(()=>{setV(value||'');},[value]);
  const Tag:any=multiline?'textarea':'input';
  return<div>
    <label className="label">{label}</label>
    <Tag className="input" rows={multiline?5:undefined} value={v} disabled={disabled}
      onChange={(e:any)=>setV(e.target.value)} onBlur={()=>{if(v!==value)onSave(v);}}/>
  </div>;
}

function DecisionBar({onDecide}:{onDecide:(status:'approved'|'rejected',note:string)=>void}){
  const[note,setNote]=useState('');
  return<div className="rounded-xl border border-amber-200 bg-amber-50 p-3.5">
    <p className="mb-2 text-xs font-semibold text-amber-700">This change is awaiting a decision.</p>
    <input value={note} onChange={(e)=>setNote(e.target.value)} placeholder="Decision note (optional)" className="input mb-2"/>
    <div className="flex gap-2">
      <button onClick={()=>onDecide('approved',note)} className="btn-brand text-xs flex items-center gap-1.5"><CheckCircle2 size={12}/>Approve</button>
      <button onClick={()=>onDecide('rejected',note)} className="btn-secondary text-xs flex items-center gap-1.5"><XCircle size={12}/>Reject</button>
    </div>
  </div>;
}
