import{useCallback,useEffect,useState}from'react';
import{supabase,resolveActiveWorkspace,type Deployment}from'../lib/supabase';
import{PageHeader,Spinner,EmptyState,StatusBadge,timeAgo}from'../lib/ui';
import{Link}from'../lib/router';
import{Rocket,Server,Globe,AlertTriangle,GitBranch,ShieldCheck}from'lucide-react';
type DRow=Deployment&{project_name?:string;environment_name?:string;change_title?:string;provider?:string|null;external_id?:string|null;started_at?:string|null;completed_at?:string|null};
type Candidate={id:string;project_id:string;project_name:string;status:string;risk_score:number|null;critical_count:number;created_at:string;commit_sha:string|null};
const ENV_COLORS:Record<string,string>={production:'bg-red-50 text-danger-600 border-red-200',staging:'bg-amber-50 text-amber-600 border-amber-200',preview:'bg-blue-50 text-blue-600 border-blue-200'};
export function DeploymentsPage(){const[loading,setLoading]=useState(true),[deployments,setDeployments]=useState<DRow[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const ws=await resolveActiveWorkspace(),wid=ws.id;const[dp,vl]=await Promise.all([supabase.from('deployments').select('id,workspace_id,project_id,environment_id,change_request_id,validation_id,status,provider,external_id,deployed_by,started_at,completed_at,created_at,projects(name),environments(name,kind),change_requests(title)').eq('workspace_id',wid).order('created_at',{ascending:false}),supabase.from('validations').select('id,project_id,status,risk_score,critical_count,commit_sha,created_at,projects(name)').eq('workspace_id',wid).eq('status','completed').order('created_at',{ascending:false}).limit(20)]);if(dp.error)throw dp.error;if(vl.error)throw vl.error;setDeployments((dp.data??[]).map((r:any)=>({...r,project_name:r.projects?.name,environment_name:r.environments?.name||r.environments?.kind||'Unspecified',change_title:r.change_requests?.title}))as DRow[]);const tracked=new Set((dp.data??[]).map((d:any)=>d.validation_id).filter(Boolean));setCandidates((vl.data??[]).filter((v:any)=>!tracked.has(v.id)).map((v:any)=>({...v,project_name:v.projects?.name||'Project'})))}catch(e:any){setError('Deployments could not be loaded: '+(e?.message||'Unknown error'));setDeployments([]);setCandidates([])}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const changed=()=>load();window.addEventListener('lythouse:workspace-changed',changed);window.addEventListener('lythouse:data-changed',changed);const channel=supabase.channel('deployments-live').on('postgres_changes',{event:'*',schema:'public',table:'deployments'},changed).on('postgres_changes',{event:'*',schema:'public',table:'validations'},changed).subscribe();return()=>{window.removeEventListener('lythouse:workspace-changed',changed);window.removeEventListener('lythouse:data-changed',changed);void supabase.removeChannel(channel)}},[load]);
 if(loading)return<div className="flex justify-center py-24"><Spinner size={28}/></div>;return<div><PageHeader title="Deployments" description="Deployment tracking is driven by validated release evidence; no manual analytics entry is required."/>{error&&<div className="mb-4 flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={15}/>{error}</div>}{candidates.length>0&&<div className="mb-6 rounded-2xl border border-brand-200 bg-brand-50/50 p-4"><div className="mb-3 flex items-center gap-2"><ShieldCheck size={17} className="text-brand-600"/><h2 className="text-sm font-bold">Validated releases awaiting deployment tracking</h2></div><div className="space-y-2">{candidates.slice(0,5).map(v=><Link key={v.id} to={`/projects/${v.project_id}`} className="flex items-center justify-between rounded-xl bg-white p-3 text-sm"><span><b>{v.project_name}</b>{v.commit_sha&&<span className="ml-2 font-mono text-xs text-gray-400">{v.commit_sha.slice(0,7)}</span>}<span className="ml-2 text-xs text-gray-500">risk {v.risk_score??'—'}</span></span><span className={`chip border ${v.critical_count>0?'border-red-200 bg-red-50 text-red-700':'border-green-200 bg-green-50 text-green-700'}`}>{v.critical_count>0?'Gate attention':'Validation cleared'}</span></Link>)}</div><p className="mt-3 text-xs text-gray-500">These records come directly from validation runs and disappear from this queue once a deployment record references the validation.</p></div>}{!error&&deployments.length===0?<EmptyState icon={<Rocket size={22}/>} title="No tracked deployments yet" description="Completed validations appear above automatically. Approved deployment records will appear here when created by the release workflow." action={<Link to="/pipeline" className="btn-primary"><GitBranch size={15}/> Open release pipeline</Link>}/>:<div className="space-y-3">{deployments.map(d=>{const env=(d.environment_name||'Unspecified').toLowerCase();return <div key={d.id} className="card flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><Rocket size={20}/></div><div><h3 className="text-sm font-semibold text-navy-900">{d.project_name??'Unknown project'}</h3>{d.change_title&&<p className="text-xs text-gray-500">{d.change_title}</p>}<div className="mt-1 flex items-center gap-2"><span className={`chip border ${ENV_COLORS[env]??'bg-gray-100 text-gray-600 border-gray-200'}`}><Globe size={11}/>{d.environment_name||'Unspecified'}</span><StatusBadge status={(d.status as any)??'pending'}/></div></div></div><div className="flex items-center gap-4 text-sm text-gray-500"><div className="flex items-center gap-1.5"><Server size={13}/>{d.provider||'Deployment tracking'}{d.external_id?` · ${d.external_id}`:''}</div><span>{timeAgo(d.created_at)}</span></div></div>})}</div>}</div>}
