import{useEffect,useState}from'react';
import{supabase,resolveActiveWorkspace,type WorkspacePlan,type PlanId,PLANS}from'../lib/supabase';
import{PageHeader,Spinner}from'../lib/ui';
import{useRole}from'../lib/useRole';
import{startCheckout,openBillingPortal,isSelfServe}from'../lib/billing';
import{Check,Loader as Loader2,Sparkles,Crown,Zap,Building2,CreditCard,AlertTriangle}from'lucide-react';
const FEATURES:Record<PlanId,string[]>={free:['1 project','5 validations / month','Basic risk scoring','Community support'],developer:['Unlimited projects','Unlimited validations','AI blast radius analysis','Deployment simulator','Slack & GitHub integrations','Email support'],enterprise:['Everything in Developer','SSO / SAML','Custom compliance frameworks','Dedicated collector','Audit log export','Priority support & SLA']};
const ICONS:Record<PlanId,typeof Sparkles>={free:Sparkles,developer:Zap,enterprise:Crown};const ORDER:PlanId[]=['free','developer','enterprise'];
export function PlansPage(){const perms=useRole(),canManage=perms.can('billing.manage');const[loading,setLoading]=useState(true),[plan,setPlan]=useState<WorkspacePlan|null>(null),[workspaceId,setWorkspaceId]=useState(''),[busy,setBusy]=useState<PlanId|'portal'|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
const load=async()=>{setLoading(true);setError('');try{const ws=await resolveActiveWorkspace();setWorkspaceId(ws.id);const{data,error}=await supabase.from('workspace_plans').select('*').eq('workspace_id',ws.id).order('created_at',{ascending:false}).limit(1);if(error)throw error;setPlan(data?.[0]??null)}catch(e:any){setError(e.message||'Billing information could not be loaded.')}setLoading(false)};
useEffect(()=>{load();const c=new URLSearchParams(window.location.search).get('checkout');if(c==='success')setNotice('Payment received. Your plan will update after Stripe confirms the subscription.');else if(c==='cancelled')setNotice('Checkout cancelled. No changes were made.')},[]);
const choose=async(id:PlanId)=>{if(!workspaceId)return;if(!canManage){setError('Only workspace owners and admins can change billing.');return}if(id==='enterprise'){window.location.href='mailto:sales@lythouse.ai?subject=LytHouse%20Enterprise';return}if(!isSelfServe(id)){setError('Paid self-serve checkout is not enabled yet. Your workspace remains on the Free launch plan.');return}try{setBusy(id);setError('');window.location.href=await startCheckout(id,workspaceId)}catch(e:any){setError(e.message||'Could not start checkout.');setBusy(null)}};
const portal=async()=>{if(!workspaceId)return;try{setBusy('portal');setError('');window.location.href=await openBillingPortal(workspaceId)}catch(e:any){setError(e.message||'Could not open billing.');setBusy(null)}};
if(loading)return <div className="flex justify-center py-24"><Spinner size={28}/></div>;const current=(plan?.plan_id as PlanId)??'free',hasSubscription=!!plan?.stripe_subscription_id;
return <div><PageHeader title="Plans" description="Start on Free. Paid plans become selectable when billing is enabled for your workspace." actions={hasSubscription&&canManage?<button onClick={portal} disabled={busy!==null} className="btn-secondary">{busy==='portal'?<Loader2 size={15} className="animate-spin"/>:<CreditCard size={15}/>} Manage billing</button>:null}/>
<div className="mb-6 flex items-start gap-3 rounded-xl border border-violet-200 bg-violet-50 px-4 py-3"><Sparkles size={17} className="mt-0.5 shrink-0 text-violet-600"/><div><p className="text-sm font-semibold text-violet-900">Launch billing status</p><p className="mt-0.5 text-sm text-violet-700">Free is available now. Developer checkout is shown only when a Stripe price is configured. Enterprise is sales-assisted.</p></div></div>
{notice&&<div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-700">{notice}</div>}{error&&<div className="mb-4 flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><AlertTriangle size={16}/>{error}</div>}
<div className="grid gap-6 lg:grid-cols-3">{ORDER.map(id=>{const info=PLANS[id],Icon=ICONS[id],isCurrent=id===current,selfServe=id!=='free'&&isSelfServe(id);return <div key={id} className={`flex flex-col rounded-2xl border bg-white p-6 ${isCurrent?'border-brand-400 ring-1 ring-brand-300':'border-gray-200'}`}><div className="mb-4 flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-violet-100 text-violet-600"><Icon size={20}/></div>{isCurrent&&<span className="chip bg-brand-50 text-brand-700 border border-brand-200"><Check size={11}/>Current</span>}</div><h2 className="text-lg font-bold">{info.name}</h2><div className="mt-2 flex items-baseline gap-1"><span className="text-3xl font-bold">${info.price}</span><span className="text-sm text-gray-500">/mo</span></div><ul className="mt-5 flex-1 space-y-2.5">{FEATURES[id].map(f=><li key={f} className="flex gap-2 text-sm text-gray-600"><Check size={15} className="mt-0.5 shrink-0 text-brand-600"/>{f}</li>)}</ul>{isCurrent?<button disabled className="mt-6 w-full rounded-xl border px-4 py-2.5 text-sm font-semibold">Current plan</button>:id==='enterprise'?<button onClick={()=>choose(id)} className="mt-6 btn-primary w-full justify-center"><Building2 size={16}/> Contact sales</button>:selfServe?<button onClick={()=>choose(id)} disabled={!canManage||busy!==null} className="mt-6 btn-primary w-full justify-center">{busy===id?<Loader2 size={16} className="animate-spin"/>:<Sparkles size={16}/>} Upgrade</button>:<button disabled className="mt-6 w-full rounded-xl border border-gray-200 bg-gray-50 px-4 py-2.5 text-sm font-semibold text-gray-500">Paid checkout coming soon</button>}</div>})}</div><p className="mt-6 text-center text-xs text-gray-400">Prices in USD. Paid checkout appears only when billing is production-configured.</p></div>}
