import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { supabase, edgeFunctionUrl, anonKey, resolveActiveWorkspace, type Project } from '../lib/supabase';
import { PageHeader, EmptyState, Spinner } from '../lib/ui';
import { Link } from '../lib/router';
import { FolderGit2, Plus, GitFork, Search, ChevronRight, ChevronDown, Lock, X, RefreshCw, ShieldCheck, Trash2, GitBranch, Shield, Clock3, SlidersHorizontal, CalendarDays, UserRound, FolderKanban, Check, ArrowDownUp } from 'lucide-react';
import { usePlanId } from './AppShell';
import { PLAN_LIMITS } from '../lib/planLimits';

const repoPath=(u?:string|null)=>{if(!u)return'Repository connected';try{return new URL(u).pathname.replace(/^\//,'').replace(/\.git$/,'')}catch{return u}};
const timeAgo=(v?:string|null)=>{if(!v)return'';const n=Date.now()-new Date(v).getTime(),m=Math.floor(n/60000);if(m<1)return'just now';if(m<60)return`${m} min ago`;const h=Math.floor(m/60);if(h<24)return`${h}h ago`;const d=Math.floor(h/24);if(d<7)return`${d}d ago`;return new Date(v).toLocaleDateString()};
function GitHubMark({size=18}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor"><path d="M12 .7C5.7.7.6 5.8.6 12.1c0 5 3.3 9.2 7.8 10.7.6.1.8-.3.8-.6v-2.3c-3.2.7-3.9-1.4-3.9-1.4-.5-1.3-1.3-1.7-1.3-1.7-1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1 1.8 2.7 1.3 3.4 1 .1-.8.4-1.3.8-1.6-2.6-.3-5.3-1.3-5.3-5.7 0-1.3.5-2.3 1.2-3.1-.1-.3-.5-1.5.1-3.1 0 0 1-.3 3.2 1.2a11 11 0 0 1 5.8 0c2.2-1.5 3.2-1.2 3.2-1.2.6 1.6.2 2.8.1 3.1.8.8 1.2 1.8 1.2 3.1 0 4.4-2.7 5.4-5.3 5.7.4.4.8 1.1.8 2.2v3.2c0 .4.2.7.8.6a11.5 11.5 0 0 0 7.8-10.7C23.4 5.8 18.3.7 12 .7Z"/></svg>}
function ProjectMark({project}:{project:any}){const initial=(project.name||'P').trim().charAt(0).toUpperCase();return <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-slate-950 text-2xl font-black text-white shadow-sm">{initial}</div>}
type Provider='github'|'gitlab'|'bitbucket'|'azure_devops';
type GitRepo={id:number;name:string;full_name:string;private:boolean;html_url:string;default_branch:string;language:string|null;description:string|null};
const providers:{id:Provider;name:string}[]=[{id:'github',name:'GitHub'},{id:'gitlab',name:'GitLab'},{id:'bitbucket',name:'Bitbucket'},{id:'azure_devops',name:'Azure DevOps'}];
const providerOf=(p:any):Provider=>{const raw=String(p.provider||p.git_provider||'').toLowerCase();if(raw.includes('gitlab'))return'gitlab';if(raw.includes('bitbucket'))return'bitbucket';if(raw.includes('azure'))return'azure_devops';return'github'};
const providerName=(p:any)=>providers.find(x=>x.id===providerOf(p))?.name||'GitHub';
const dateOptions=[['all','Any date'],['today','Today'],['7d','Last 7 days'],['30d','Last 30 days'],['90d','Last 90 days']];
const sortOptions=[['created_desc','Created date'],['created_asc','Oldest connected'],['name_asc','Project name A–Z'],['name_desc','Project name Z–A']];
type Field='Project'|'Owner'|'Provider'|'Status'|'Connected date';
const fields:Field[]=['Project','Owner','Provider','Status','Connected date'];
function Popover({children,onClose,wide=false}:{children:any;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const fn=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))onClose()};document.addEventListener('mousedown',fn);return()=>document.removeEventListener('mousedown',fn)},[onClose]);return <div ref={ref} className={`absolute left-0 top-[calc(100%+6px)] z-50 ${wide?'w-[290px]':'w-[230px]'} overflow-hidden rounded-xl border border-gray-200 bg-white p-1.5 shadow-2xl ring-1 ring-black/5`}>{children}</div>}
function Choice({selected,label,sub,onClick}:{selected?:boolean;label:string;sub?:string;onClick:()=>void}){return <button onClick={onClick} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition hover:bg-slate-50"><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded ${selected?'bg-navy-950 text-white':'border border-gray-200 text-transparent'}`}><Check size={12}/></span><span className="min-w-0"><span className="block truncate text-sm font-medium text-navy-950">{label}</span>{sub&&<span className="block truncate text-[11px] text-gray-400">{sub}</span>}</span></button>}

export function ProjectsPage(){
 const planId=usePlanId();
 const[loading,setLoading]=useState(true),[projects,setProjects]=useState<any[]>([]),[wid,setWid]=useState(''),[q,setQ]=useState(''),[projectFilter,setProjectFilter]=useState('all'),[providerFilter,setProviderFilter]=useState<'all'|Provider>('all'),[statusFilter,setStatusFilter]=useState('all'),[dateFilter,setDateFilter]=useState('all'),[creatorFilter,setCreatorFilter]=useState('all'),[sort,setSort]=useState('created_desc');
 const[filterOpen,setFilterOpen]=useState(false),[field,setField]=useState<Field|null>(null),[operatorOpen,setOperatorOpen]=useState(false),[valueSearch,setValueSearch]=useState('');
 const[modal,setModal]=useState(false),[saving,setSaving]=useState<Provider|null>(null),[error,setError]=useState(''),[deleteProject,setDeleteProject]=useState<Project|null>(null),[deleteText,setDeleteText]=useState(''),[deleting,setDeleting]=useState(false),[repos,setRepos]=useState<GitRepo[]>([]),[repoModal,setRepoModal]=useState(false),[repoLoading,setRepoLoading]=useState(false),[importing,setImporting]=useState<number|null>(null),[installationId,setInstallationId]=useState(''),[githubState,setGithubState]=useState('');
 const limit=PLAN_LIMITS[planId]?.projects??null,atLimit=limit!=null&&projects.length>=limit;
 async function api(payload:any){const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Session expired');const r=await fetch(`${edgeFunctionUrl}/git-provider-connect`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,apikey:anonKey},body:JSON.stringify(payload)});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Repository connection failed');return body}
 async function load(){setLoading(true);setError('');try{const ws=await resolveActiveWorkspace();setWid(ws.id);const{data,error:e}=await supabase.from('projects').select('*').eq('workspace_id',ws.id).order('created_at',{ascending:false});if(e)throw e;const rows=data??[],ids=rows.map((p:any)=>p.id),creatorIds=[...new Set(rows.map((p:any)=>p.created_by).filter(Boolean))];let validations:any[]=[],profiles:any[]=[];if(ids.length){const r=await supabase.from('validations').select('id,project_id,status,commit_sha,branch,completed_at,created_at').in('project_id',ids).order('created_at',{ascending:false});validations=r.data??[]}if(creatorIds.length){const r=await supabase.from('profiles').select('id,full_name,email').in('id',creatorIds);profiles=r.data??[]}const latest=new Map(),people=new Map(profiles.map((p:any)=>[p.id,p]));for(const v of validations)if(!latest.has(v.project_id))latest.set(v.project_id,v);setProjects(rows.map((p:any)=>({...p,latestValidation:latest.get(p.id)||null,creator:people.get(p.created_by)||null})))}catch(e){console.error(e);setError('We couldn’t load your projects right now.')}finally{setLoading(false)}}
 useEffect(()=>{load();const h=()=>load();window.addEventListener('lythouse:workspace-changed',h);return()=>window.removeEventListener('lythouse:workspace-changed',h)},[]);
 useEffect(()=>{const p=new URLSearchParams(window.location.search),iid=p.get('installation_id'),state=p.get('state');if(!iid||!state)return;setInstallationId(iid);setGithubState(state);setRepoModal(true);setRepoLoading(true);api({action:'github_repositories',installationId:iid,state}).then(b=>setRepos(b.repositories||[])).catch(()=>setError('We couldn’t load the repositories you authorized.')).finally(()=>setRepoLoading(false));window.history.replaceState({},'',window.location.pathname)},[]);
 async function connect(provider:Provider){if(!wid)return;setSaving(provider);try{const b=await api({action:'start',workspaceId:wid,provider});window.location.assign(b.authorizeUrl)}catch{setError('We couldn’t start the repository connection.');setSaving(null)}}
 async function importRepo(repo:GitRepo){setImporting(repo.id);try{const b=await api({action:'github_import',installationId,state:githubState,repositoryId:repo.id});await load();setRepoModal(false);if(b.project?.id)window.location.assign(`/projects/${b.project.id}`)}catch{setError('We couldn’t connect this repository.')}finally{setImporting(null)}}
 async function removeProject(){if(!deleteProject||deleteText!==deleteProject.name)return;setDeleting(true);const{error:e}=await supabase.rpc('delete_project',{p_project_id:deleteProject.id,p_confirmation:deleteText});if(e){setError('We couldn’t remove this project.');setDeleting(false);return}setProjects(ps=>ps.filter(p=>p.id!==deleteProject.id));setDeleteProject(null);setDeleteText('');setDeleting(false)}
 const creators=useMemo(()=>{const m=new Map<string,any>();projects.forEach(p=>{if(p.created_by)m.set(p.created_by,p.creator||{id:p.created_by,full_name:'Project creator'})});return [...m.values()]},[projects]);
 const filtered=useMemo(()=>{const now=Date.now(),age:any={today:86400000,'7d':604800000,'30d':2592000000,'90d':7776000000};let rows=projects.filter((p:any)=>(!q||`${p.name} ${repoPath(p.git_url)} ${providerName(p)} ${p.creator?.full_name||''}`.toLowerCase().includes(q.toLowerCase()))&&(projectFilter==='all'||p.id===projectFilter)&&(providerFilter==='all'||providerOf(p)===providerFilter)&&(statusFilter==='all'||(statusFilter==='validated'?!!p.latestValidation:!p.latestValidation))&&(creatorFilter==='all'||p.created_by===creatorFilter)&&(dateFilter==='all'||now-new Date(p.created_at).getTime()<=age[dateFilter]));return [...rows].sort((a,b)=>sort==='name_asc'?a.name.localeCompare(b.name):sort==='name_desc'?b.name.localeCompare(a.name):sort==='created_asc'?+new Date(a.created_at)-+new Date(b.created_at):+new Date(b.created_at)-+new Date(a.created_at))},[projects,q,projectFilter,providerFilter,statusFilter,dateFilter,creatorFilter,sort]);
 const active=[projectFilter!=='all'&&{field:'Project',value:projects.find(p=>p.id===projectFilter)?.name||'Project',clear:()=>setProjectFilter('all')},creatorFilter!=='all'&&{field:'Owner',value:creators.find((c:any)=>c.id===creatorFilter)?.full_name||'Owner',clear:()=>setCreatorFilter('all')},providerFilter!=='all'&&{field:'Provider',value:providers.find(p=>p.id===providerFilter)?.name||'Provider',clear:()=>setProviderFilter('all')},statusFilter!=='all'&&{field:'Status',value:statusFilter==='validated'?'Validated':'Not validated',clear:()=>setStatusFilter('all')},dateFilter!=='all'&&{field:'Connected date',value:dateOptions.find(x=>x[0]===dateFilter)?.[1]||'Date',clear:()=>setDateFilter('all')}].filter(Boolean) as any[];
 const choose=(f:Field,v:string)=>{if(f==='Project')setProjectFilter(v);if(f==='Owner')setCreatorFilter(v);if(f==='Provider')setProviderFilter(v as any);if(f==='Status')setStatusFilter(v);if(f==='Connected date')setDateFilter(v);setField(null);setFilterOpen(false);setValueSearch('')};
 const overlay=(child:any)=>createPortal(<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-4">{child}</div>,document.body);
 if(loading)return <div className="flex justify-center py-24"><Spinner size={28}/></div>;
 return <div><PageHeader title="Projects" description="Monitor and validate your connected repositories." actions={atLimit?<Link to="/plans" className="btn-primary"><Lock size={14}/> Upgrade for more projects</Link>:<button onClick={()=>setModal(true)} className="btn-primary"><Plus size={16}/> Connect Repository</button>}/>
 {error&&!modal&&!repoModal&&!deleteProject&&<div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{error}</div>}
 {projects.length===0?<EmptyState icon={<FolderGit2 size={22}/>} title="No projects yet" description="Connect a repository to begin validation." action={<button onClick={()=>setModal(true)} className="btn-primary"><GitFork size={16}/> Connect repository</button>}/>:<>
 <div className="mb-5 rounded-xl border border-gray-200 bg-white shadow-sm">
  <div className="flex min-h-[52px] items-stretch gap-0 p-2">
   <div className="relative flex min-w-0 flex-1 items-center rounded-lg border border-gray-300 bg-white focus-within:border-brand-400 focus-within:ring-2 focus-within:ring-brand-100">
    <button onClick={()=>{setFilterOpen(v=>!v);setField(null)}} className="flex h-10 shrink-0 items-center gap-2 border-r border-gray-200 px-3 text-gray-500 hover:bg-gray-50"><SlidersHorizontal size={15}/><ChevronDown size={12}/></button>
    <div className="flex min-w-0 flex-1 items-center gap-1 overflow-x-auto px-2 py-1 [scrollbar-width:none]">
     {active.map((a:any)=><div key={a.field} className="flex shrink-0 items-center overflow-hidden rounded-md border border-gray-200 bg-slate-50 text-xs"><span className="bg-slate-100 px-2.5 py-1.5 font-semibold text-gray-600">{a.field}</span><button onClick={()=>setOperatorOpen(v=>!v)} className="border-x border-gray-200 px-2 py-1.5 text-gray-500">=</button><span className="max-w-[180px] truncate px-2.5 py-1.5 font-medium text-navy-950">{a.value}</span><button onClick={a.clear} className="px-2 py-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-700"><X size={12}/></button></div>)}
     <div className="relative min-w-[180px] flex-1"><Search size={14} className="absolute left-2 top-1/2 -translate-y-1/2 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} onFocus={()=>{if(!active.length)setFilterOpen(true)}} className="h-8 w-full border-0 bg-transparent pl-7 pr-2 text-sm outline-none" placeholder={active.length?'Search or add filter…':'Filter projects…'}/></div>
    </div>
    {q&&<button onClick={()=>setQ('')} className="px-2 text-gray-400"><X size={15}/></button>}
    {filterOpen&&<Popover onClose={()=>{setFilterOpen(false);setField(null)}} wide>{!field?<><div className="px-3 py-2 text-[11px] font-bold uppercase tracking-wider text-gray-400">Filter by</div>{fields.map(f=><button key={f} onClick={()=>{setField(f);setValueSearch('')}} className="flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-sm font-medium hover:bg-slate-50"><span>{f}</span><ChevronRight size={14} className="text-gray-400"/></button>)}</>:<><div className="flex items-center gap-2 border-b px-2 pb-2"><button onClick={()=>setField(null)} className="rounded p-1 hover:bg-gray-100">‹</button><b className="text-sm">{field}</b></div><div className="p-2"><input autoFocus value={valueSearch} onChange={e=>setValueSearch(e.target.value)} className="input h-9 text-sm" placeholder={`Search ${field.toLowerCase()}…`}/></div><div className="max-h-64 overflow-auto">{field==='Project'&&projects.filter(p=>p.name.toLowerCase().includes(valueSearch.toLowerCase())).map(p=><Choice key={p.id} label={p.name} sub={repoPath(p.git_url)} selected={projectFilter===p.id} onClick={()=>choose(field,p.id)}/>)}{field==='Owner'&&creators.filter((c:any)=>`${c.full_name||''} ${c.email||''}`.toLowerCase().includes(valueSearch.toLowerCase())).map((c:any)=><Choice key={c.id} label={c.full_name||c.email||'Project creator'} sub={c.email} selected={creatorFilter===c.id} onClick={()=>choose(field,c.id)}/>)}{field==='Provider'&&providers.filter(p=>p.name.toLowerCase().includes(valueSearch.toLowerCase())).map(p=><Choice key={p.id} label={p.name} selected={providerFilter===p.id} onClick={()=>choose(field,p.id)}/>)}{field==='Status'&&[['validated','Validated'],['not_validated','Not validated']].map(([v,l])=><Choice key={v} label={l} selected={statusFilter===v} onClick={()=>choose(field,v)}/>)}{field==='Connected date'&&dateOptions.filter(x=>x[0]!=='all').map(([v,l])=><Choice key={v} label={l} selected={dateFilter===v} onClick={()=>choose(field,v)}/>)}</div></>}</Popover>}
    {operatorOpen&&<div className="absolute left-24 top-[48px] z-[60] w-52 rounded-xl border bg-white p-1.5 shadow-xl"><button onClick={()=>setOperatorOpen(false)} className="flex w-full items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>=</span><span className="text-gray-500">is</span></button><button disabled className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-sm text-gray-400"><span>!=</span><span>is not</span></button><button disabled className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-sm text-gray-400"><span>||</span><span>is one of</span></button></div>}
   </div>
   <div className="relative ml-2 flex shrink-0 items-center"><ArrowDownUp size={14} className="pointer-events-none absolute left-3 text-gray-400"/><select value={sort} onChange={e=>setSort(e.target.value)} className="h-full appearance-none rounded-lg border border-gray-300 bg-white pl-9 pr-8 text-xs font-semibold text-gray-600 outline-none hover:bg-gray-50">{sortOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><ChevronDown size={12} className="pointer-events-none absolute right-3 text-gray-400"/></div>
  </div>
 </div>
 <div className="space-y-2">{filtered.map((p:any)=>{const v=p.latestValidation,validated=!!v,failed=v?.status==='failed';return <div key={p.id} className="group relative overflow-hidden rounded-2xl border border-gray-200 bg-white transition hover:border-brand-200 hover:shadow-sm"><div className={`absolute inset-y-0 left-0 w-[3px] ${failed?'bg-amber-400':validated?'bg-emerald-400':'bg-gray-300'}`}/><div className="grid min-h-[126px] grid-cols-1 items-center lg:grid-cols-[1.35fr_1fr_1fr_auto]"><Link to={'/projects/'+p.id} className="flex min-w-0 items-center gap-4 px-6 py-5"><ProjectMark project={p}/><div className="min-w-0"><div className="truncate text-lg font-bold text-navy-950">{p.name}</div><div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-gray-600"><GitHubMark/><span>{providerName(p)}</span><span className="text-gray-300">·</span><span className="truncate font-medium text-brand-600">{repoPath(p.git_url)}</span>{p.git_branch&&<><GitBranch size={14}/><span>{p.git_branch}</span></>}</div>{p.creator&&<div className="mt-2 flex items-center gap-2 text-xs text-gray-400"><UserRound size={13}/>{p.creator.full_name||p.creator.email}</div>}</div></Link><Link to={'/projects/'+p.id} className="border-t border-gray-100 px-6 py-5 lg:border-l lg:border-t-0"><div className="text-sm font-semibold">{validated?'Latest validation':'Ready for first validation'}</div><div className="mt-3 flex items-center gap-2 text-sm text-gray-500"><Clock3 size={16}/>{validated?timeAgo(v.completed_at||v.created_at):`Connected ${timeAgo(p.created_at)}`}</div></Link><Link to={'/projects/'+p.id} className="border-t border-gray-100 px-6 py-5 lg:border-l lg:border-t-0"><span className={`inline-flex rounded-full px-3 py-1 text-sm font-semibold ${failed?'bg-amber-50 text-amber-700':validated?'bg-emerald-50 text-emerald-700':'bg-gray-100 text-gray-600'}`}>{validated?(failed?'Attention':'Ready'):'Not validated'}</span><div className="mt-3 flex items-center gap-2 text-sm text-gray-600"><Shield size={16}/>{validated?'Validation evidence available':'Not validated yet'}</div></Link><div className="flex items-center gap-1 px-4"><Link to={'/projects/'+p.id} className="flex h-10 w-10 items-center justify-center rounded-xl text-gray-500 hover:bg-gray-50"><ChevronRight size={22}/></Link><button onClick={()=>{setDeleteText('');setDeleteProject(p)}} className="flex h-9 w-9 items-center justify-center rounded-xl text-gray-300 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button></div></div></div>})}</div><div className="mt-5 text-sm text-gray-500">Showing {filtered.length} of {projects.length} projects</div></>}
 {modal&&overlay(<div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-semibold">Connect repository</h2><p className="mt-1 text-sm text-gray-500">Choose a Git provider.</p></div><button onClick={()=>setModal(false)}><X size={16}/></button></div>{providers.map(p=><button key={p.id} onClick={()=>connect(p.id)} disabled={!!saving} className="mb-2 flex w-full items-center justify-between rounded-xl border p-4 text-left hover:bg-gray-50"><span className="font-semibold">Continue with {p.name}</span>{saving===p.id?<Spinner size={16}/>:<ChevronRight size={16}/>}</button>)}<div className="mt-3 flex gap-2 text-xs text-gray-500"><ShieldCheck size={14}/>Only repositories you authorize are connected.</div></div>)}
 {repoModal&&overlay(<div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">Choose a GitHub repository</h2><p className="text-sm text-gray-500">Authorized repositories</p></div><button onClick={()=>setRepoModal(false)}><X size={18}/></button></div>{repoLoading?<div className="flex justify-center py-12"><Spinner size={26}/></div>:<div className="mt-5 max-h-[55vh] space-y-2 overflow-auto">{repos.map(r=><button key={r.id} onClick={()=>importRepo(r)} disabled={!!importing} className="flex w-full items-center gap-3 rounded-xl border p-4 text-left hover:bg-gray-50"><GitHubMark/><div className="flex-1"><b>{r.full_name}</b><div className="text-xs text-gray-500">{r.private?'Private':'Public'} · {r.default_branch}</div></div>{importing===r.id?<Spinner size={17}/>:<ChevronRight size={18}/>}</button>)}</div>}</div>)}
 {deleteProject&&overlay(<div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold text-red-700">Delete project</h2><p className="mt-2 text-sm text-gray-600">Type <b>{deleteProject.name}</b> to confirm.</p></div><button onClick={()=>setDeleteProject(null)}><X size={18}/></button></div><input autoFocus className="input mt-5" value={deleteText} onChange={e=>setDeleteText(e.target.value)} placeholder={deleteProject.name}/><div className="mt-6 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setDeleteProject(null)}>Cancel</button><button className="btn-primary bg-red-600" disabled={deleting||deleteText!==deleteProject.name} onClick={removeProject}>{deleting?<Spinner size={14}/>:<Trash2 size={14}/>} Delete</button></div></div>)}
 </div>;
}
