// @ts-nocheck
import{useCallback,useEffect,useState}from'react';import{supabase,resolveActiveWorkspace,type WorkspacePlan,type PlanId,PLANS}from'../lib/supabase';import{PageHeader,Spinner}from'../lib/ui';import{Link}from'../lib/router';import{PLAN_LIMITS}from'../lib/planLimits';import{FolderGit2,ShieldCheck,Users,ArrowUpRight,Gauge,AlertTriangle}from'lucide-react';
const CSS=`.us-wrap{max-width:1000px;margin:0 auto;display:flex;flex-direction:column;gap:18px}.us-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}@media(max-width:800px){.us-grid{grid-template-columns:1fr}}.us-card{background:var(--lh-surface);border:.5px solid var(--lh-border);border-radius:14px;padding:18px 20px}.us-top{display:flex;align-items:center;gap:9px;font-size:13px;font-weight:600;color:var(--lh-text2)}.us-val{display:flex;align-items:baseline;gap:6px;margin-top:10px}.us-num{font-size:30px;font-weight:700}.us-cap,.us-note{font-size:12px;color:var(--lh-text3)}.us-bar{height:6px;border-radius:20px;background:var(--lh-border);overflow:hidden;margin-top:12px}.us-bar i{display:block;height:100%;background:var(--lh-accent)}.us-plan,.us-row{display:flex;align-items:center;justify-content:space-between;gap:16px}.us-plan-name{font-size:16px;font-weight:700}.us-upgrade{display:inline-flex;align-items:center;gap:6px;font-size:13px;font-weight:600;color:var(--lh-accent-contrast);background:var(--lh-accent);border-radius:9px;padding:9px 15px;text-decoration:none}.us-list{display:flex;flex-direction:column}.us-row{padding:11px 20px;border-top:.5px solid var(--lh-border);font-size:13.5px}.rv{font-weight:600}`;
function Meter({label,icon:Icon,used,limit,note}:any){const unavailable=used==null,unlimited=limit==null,pct=unavailable||unlimited?0:Math.min(100,Math.round(used/Math.max(1,limit)*100));return <div className="us-card"><div className="us-top"><Icon size={15}/>{label}</div><div className="us-val"><span className="us-num">{unavailable?'—':used}</span><span className="us-cap">{unavailable?'unavailable':unlimited?'unlimited':`of ${limit}`}</span></div>{!unavailable&&!unlimited&&<div className="us-bar"><i style={{width:`${pct}%`}}/></div>}{note&&<div className="us-note">{note}</div>}</div>}
export function UsagePage(){
 const[loading,setLoading]=useState(true),[error,setError]=useState(''),[plan,setPlan]=useState<WorkspacePlan|null>(null),[projectCount,setProjectCount]=useState<number|null>(null),[monthValidations,setMonthValidations]=useState<number|null>(null),[monthPassed,setMonthPassed]=useState<number|null>(null),[monthFailed,setMonthFailed]=useState<number|null>(null),[memberCount,setMemberCount]=useState<number|null>(null),[openFindings,setOpenFindings]=useState<number|null>(null),[resolvedThisMonth,setResolvedThisMonth]=useState<number|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{
  const ws=await resolveActiveWorkspace(),wid=ws.id,monthStart=new Date();monthStart.setDate(1);monthStart.setHours(0,0,0,0);const iso=monthStart.toISOString();
  const queries:any[]=[
   ['plan',supabase.from('workspace_plans').select('workspace_id,plan_id,status,created_at').eq('workspace_id',wid).order('created_at',{ascending:false}).limit(1)],
   ['projects',supabase.from('projects').select('id').eq('workspace_id',wid)],
   ['validations',supabase.from('validations').select('id',{count:'exact',head:true}).eq('workspace_id',wid).gte('created_at',iso)],
   ['completed validations',supabase.from('validations').select('id',{count:'exact',head:true}).eq('workspace_id',wid).eq('status','completed').gte('created_at',iso)],
   ['failed validations',supabase.from('validations').select('id',{count:'exact',head:true}).eq('workspace_id',wid).eq('status','failed').gte('created_at',iso)],
   ['team members',supabase.from('workspace_members').select('id',{count:'exact',head:true}).eq('workspace_id',wid)]
  ];
  const results=await Promise.all(queries.map(([,q])=>q));const failures:string[]=[];results.forEach((r:any,i:number)=>{if(r.error)failures.push(`${queries[i][0]}: ${r.error.message||'query failed'}`)});
  const[pl,pr,vc,vp,vf,mc]=results;
  setPlan(pl.error?null:(pl.data?.[0]??null));setProjectCount(pr.error?null:(pr.data?.length??0));setMonthValidations(vc.error?null:(vc.count??0));setMonthPassed(vp.error?null:(vp.count??0));setMonthFailed(vf.error?null:(vf.count??0));setMemberCount(mc.error?null:(mc.count??0));
  setOpenFindings(null);setResolvedThisMonth(null);const projectIds=pr.error?[]:(pr.data||[]).map((p:any)=>p.id);
  if(!pr.error&&projectIds.length){const[of,rf]=await Promise.all([supabase.from('findings').select('id',{count:'exact',head:true}).in('project_id',projectIds).eq('status','open'),supabase.from('findings').select('id',{count:'exact',head:true}).in('project_id',projectIds).eq('status','resolved').gte('resolved_at',iso)]);if(of.error)failures.push(`open findings: ${of.error.message||'query failed'}`);else setOpenFindings(of.count??0);if(rf.error)failures.push(`resolved findings: ${rf.error.message||'query failed'}`);else setResolvedThisMonth(rf.count??0)}else if(!pr.error){setOpenFindings(0);setResolvedThisMonth(0)}
  if(failures.length)setError(`Some usage metrics could not be loaded — ${failures.join('; ')}`)
 }catch(e:any){setError(e?.message||'Usage could not be loaded.');setProjectCount(null);setMonthValidations(null);setMonthPassed(null);setMonthFailed(null);setMemberCount(null);setOpenFindings(null);setResolvedThisMonth(null)}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const changed=()=>load();window.addEventListener('lythouse:workspace-changed',changed);return()=>window.removeEventListener('lythouse:workspace-changed',changed)},[load]);
 if(loading)return<div className="flex justify-center py-24"><Spinner size={28}/></div>;
 const planId:PlanId=(plan?.plan_id as PlanId)??'free',planInfo=PLANS[planId],limits=PLAN_LIMITS[planId]??PLAN_LIMITS.free,monthLabel=new Date().toLocaleDateString(undefined,{month:'long',year:'numeric'}),validationNote=monthPassed==null||monthFailed==null?'Validation status unavailable':`${monthPassed} completed · ${monthFailed} failed this month`;
 return <div className="us-wrap"><style>{CSS}</style><PageHeader title="Usage" description={`Persisted consumption for the authenticated workspace against the ${planInfo.name} plan.`}/>{error&&<div className="flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={15}/>{error}</div>}<div className="us-card us-plan"><div><div className="us-plan-name">{planInfo.name} plan</div><div className="us-note">Validation usage resets monthly; projects and members are current totals.</div></div>{planId==='free'&&<Link to="/plans" className="us-upgrade">View plans <ArrowUpRight size={14}/></Link>}</div><div className="us-grid"><Meter label="Projects" icon={FolderGit2} used={projectCount} limit={limits.projects}/><Meter label={`Validations · ${monthLabel}`} icon={ShieldCheck} used={monthValidations} limit={limits.validationsPerMonth} note={validationNote}/><Meter label="Team members" icon={Users} used={memberCount} limit={null}/></div><div className="us-card" style={{padding:0}}><div style={{padding:'15px 20px',borderBottom:'.5px solid var(--lh-border)',display:'flex',gap:8,alignItems:'center'}}><Gauge size={15}/> Findings snapshot</div><div className="us-list"><div className="us-row"><span>Open findings across all projects</span><span className="rv">{openFindings==null?'—':openFindings}</span></div><div className="us-row"><span>Resolved this month</span><span className="rv">{resolvedThisMonth==null?'—':resolvedThisMonth}</span></div></div></div></div>
}
