import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import jwt from 'npm:jsonwebtoken@9.0.2';
const cors={'Access-Control-Allow-Origin':Deno.env.get('APP_ORIGIN')||'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
type Provider='github'|'gitlab'|'bitbucket'|'azure_devops';
function stateSecret(){const secret=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!secret)throw new Error('Server authorization secret is unavailable');return secret}
function makeState(payload:Record<string,unknown>){return jwt.sign(payload,stateSecret(),{algorithm:'HS256',expiresIn:'30m'})}
function readState(token:string){try{return jwt.verify(token,stateSecret(),{algorithms:['HS256']}) as Record<string,unknown>}catch{throw new Error('Invalid or expired authorization state')}}
function appJwt(){const appId=Deno.env.get('GITHUB_APP_ID'),key=(Deno.env.get('GITHUB_APP_PRIVATE_KEY')||'').replace(/\\n/g,'\n');if(!appId||!key)throw new Error('GitHub App credentials are incomplete');const now=Math.floor(Date.now()/1000);return jwt.sign({iat:now-60,exp:now+540,iss:appId},key,{algorithm:'RS256'})}
async function reposFor(id:string){const tr=await fetch(`https://api.github.com/app/installations/${encodeURIComponent(id)}/access_tokens`,{method:'POST',headers:{Authorization:`Bearer ${appJwt()}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'LytHouse'}}),tb=await tr.json();if(!tr.ok)throw new Error(tb?.message||'GitHub installation could not be authenticated');const r=await fetch('https://api.github.com/installation/repositories?per_page=100',{headers:{Authorization:`Bearer ${tb.token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'LytHouse'}}),body=await r.json();if(!r.ok)throw new Error(body?.message||'Authorized repositories could not be loaded');return(body.repositories||[]).map((x:any)=>({id:x.id,name:x.name,full_name:x.full_name,private:x.private,html_url:x.html_url,default_branch:x.default_branch,language:x.language,description:x.description}))}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Authentication required'},401);const supabaseUrl=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const userClient=createClient(supabaseUrl,anon,{global:{headers:{Authorization:auth}}});const{data:{user},error:ue}=await userClient.auth.getUser();if(ue||!user)return json({error:'Authentication required'},401);const body=await req.json(),action=String(body.action||'start'),db=createClient(supabaseUrl,service);
if(action==='start'){const workspaceId=String(body.workspaceId||''),provider=String(body.provider||'') as Provider;if(!workspaceId)return json({error:'workspaceId is required'},400);if(!['github','gitlab','bitbucket','azure_devops'].includes(provider))return json({error:'Unsupported source-control provider'},400);const{data:member}=await db.from('workspace_members').select('role').eq('workspace_id',workspaceId).eq('user_id',user.id).maybeSingle();if(!member||!['owner','admin','developer'].includes(member.role))return json({error:'You do not have permission to connect repositories'},403);const origin=Deno.env.get('APP_ORIGIN')||'',state=makeState({workspaceId,userId:user.id,provider});let authorizeUrl='';if(provider==='github'){const slug=Deno.env.get('GITHUB_APP_SLUG');if(!slug)return json({error:'GitHub App is not configured yet.'},503);authorizeUrl=`https://github.com/apps/${encodeURIComponent(slug)}/installations/new?state=${encodeURIComponent(state)}`;}else if(provider==='gitlab'){const id=Deno.env.get('GITLAB_CLIENT_ID');if(!id)return json({error:'GitLab OAuth is not configured yet.'},503);authorizeUrl=`https://gitlab.com/oauth/authorize?client_id=${encodeURIComponent(id)}&redirect_uri=${encodeURIComponent(origin+'/integrations/gitlab/callback')}&response_type=code&state=${encodeURIComponent(state)}&scope=${encodeURIComponent('read_api read_repository')}`;}else if(provider==='bitbucket'){const id=Deno.env.get('BITBUCKET_CLIENT_ID');if(!id)return json({error:'Bitbucket authorization is not configured yet.'},503);authorizeUrl=`https://bitbucket.org/site/oauth2/authorize?client_id=${encodeURIComponent(id)}&response_type=code&state=${encodeURIComponent(state)}`;}else{const id=Deno.env.get('AZURE_DEVOPS_CLIENT_ID');if(!id)return json({error:'Azure DevOps authorization is not configured yet.'},503);authorizeUrl=`https://app.vssps.visualstudio.com/oauth2/authorize?client_id=${encodeURIComponent(id)}&response_type=Assertion&state=${encodeURIComponent(state)}&scope=${encodeURIComponent('vso.code')}&redirect_uri=${encodeURIComponent(origin+'/integrations/azure-devops/callback')}`;}return json({provider,authorizeUrl});}
if(action==='github_repositories'||action==='github_import'){const installationId=String(body.installationId||''),state=String(body.state||'');if(!installationId||!state)return json({error:'GitHub installation information is missing'},400);const st=readState(state);if(st.provider!=='github'||st.userId!==user.id)return json({error:'This GitHub authorization does not belong to the signed-in user'},403);const workspaceId=String(st.workspaceId||''),{data:member}=await db.from('workspace_members').select('role').eq('workspace_id',workspaceId).eq('user_id',user.id).maybeSingle();if(!member||!['owner','admin','developer'].includes(member.role))return json({error:'You do not have permission to connect repositories'},403);const repositories=await reposFor(installationId);if(action==='github_repositories')return json({installationId,workspaceId,repositories});const repositoryId=Number(body.repositoryId),repo=repositories.find((x:any)=>x.id===repositoryId);if(!repo)return json({error:'That repository is not authorized for this GitHub installation'},403);const{data:existing}=await db.from('projects').select('id,name').eq('workspace_id',workspaceId).eq('github_repository_id',repositoryId).maybeSingle();if(existing)return json({project:existing,existing:true});const{data:project,error:pe}=await db.from('projects').insert({workspace_id:workspaceId,name:repo.name,description:repo.description||null,status:'active',git_url:repo.html_url,git_branch:repo.default_branch||'main',language:repo.language||null,created_by:user.id,github_installation_id:Number(installationId),github_repository_id:repo.id,github_repository_full_name:repo.full_name,github_token:null}).select('id,name,git_url,git_branch,workspace_id,github_installation_id,github_repository_id,github_repository_full_name').single();if(pe)throw pe;return json({project,existing:false});}
return json({error:'Unsupported action'},400);}catch(e){console.error('git-provider-connect',e);return json({error:e instanceof Error?e.message:'Repository connection failed.'},500);}});
