import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":Deno.env.get("APP_ORIGIN")||"https://lythouse.ai","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, Apikey"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const rules=[
 [/\.github\/workflows\//i,'ci',14],[/(^|\/)(terraform|infra|infrastructure)\/|\.tf(vars)?$/i,'infrastructure',18],[/(^|\/)(k8s|kubernetes|helm)\/|Dockerfile|docker-compose/i,'infrastructure',16],[/package(-lock)?\.json$|requirements\.txt$|go\.(mod|sum)$/i,'dependency',12],[/(^|\/)supabase\/migrations\/|(^|\/)migrations\//i,'database',20],[/(^|\/)(auth|security|permissions|iam|rbac)(\/|\.|-)/i,'security',20],[/\.env|vercel\.json|netlify\.toml|config\./i,'configuration',16],[/(^|\/)(api|server|functions|routes)\//i,'application',10]
] as const;
function classify(path:string){const m=rules.filter(r=>r[0].test(path));const strongest=m.sort((a,b)=>b[2]-a[2])[0];return{path,kind:strongest?.[1]||'application',weight:strongest?.[2]||4};}
function parseGitUrl(url:string){const m=url.match(/github\.com[/:]([^/]+)\/(.+?)(?:\.git)?$/);return m?{owner:m[1],repo:m[2]}:null;}
async function gh(url:string,token:string|null){const h:Record<string,string>={Accept:'application/vnd.github+json','User-Agent':'lythouse'};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(url,{headers:h});return r.ok?r.json():null;}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});try{
 const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Authentication required'},401);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
 const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:{user}}=await uc.auth.getUser();if(!user)return json({error:'Invalid session'},401);
 const{projectId,environment='staging'}=await req.json();if(!projectId)return json({error:'projectId required'},400);
 const db=createClient(url,service);const{data:project}=await db.from('projects').select('*').eq('id',projectId).single();if(!project)return json({error:'Project not found'},404);
 const{data:member}=await db.from('workspace_members').select('role').eq('workspace_id',project.workspace_id).eq('user_id',user.id).maybeSingle();if(!member)return json({error:'Workspace access denied'},403);
 const{data:validation}=await db.from('validations').select('*').eq('project_id',projectId).eq('status','completed').order('created_at',{ascending:false}).limit(1).maybeSingle();if(!validation)return json({error:'Run a validation before simulating'},409);
 const{data:findings}=await db.from('findings').select('severity,category,file_path,title').eq('validation_id',validation.id).neq('status','resolved');const fs=findings||[];
 const parsed=parseGitUrl(project.git_url||'');let changed:string[]=[];let baseSha:string|null=null,headSha:string|null=null;
 if(parsed){const commits=await gh(`https://api.github.com/repos/${parsed.owner}/${parsed.repo}/commits?sha=${encodeURIComponent(project.git_branch||'main')}&per_page=2`,project.github_token||null);if(commits?.length>=2){headSha=commits[0].sha;baseSha=commits[1].sha;const cmp=await gh(`https://api.github.com/repos/${parsed.owner}/${parsed.repo}/compare/${baseSha}...${headSha}`,project.github_token||null);changed=(cmp?.files||[]).map((f:any)=>f.filename);}}
 const impacts=changed.map(classify);const counts={critical:fs.filter((f:any)=>f.severity==='critical').length,high:fs.filter((f:any)=>f.severity==='high').length,medium:fs.filter((f:any)=>f.severity==='medium').length};
 const findingRisk=Math.min(100,counts.critical*25+counts.high*15+counts.medium*8);const changeRisk=Math.min(100,impacts.reduce((n,i)=>n+i.weight,0));const envFactor=environment==='production'?1.12:environment==='preview'?.88:1;const score=Math.min(100,Math.round((findingRisk*.7+changeRisk*.3)*envFactor));
 const sensitive=impacts.some(i=>['security','database','infrastructure'].includes(i.kind));const verdict=score>=70||counts.critical>0?'BLOCK':score>=35||sensitive?'REVIEW':'SHIP';const blast=impacts.length>=8||counts.critical>=2?'critical':impacts.length>=4||counts.critical?'large':impacts.length?'medium':'small';const confidence=changed.length?Math.min(96,70+Math.min(20,changed.length*2)):55;
 const affected=[...new Set(impacts.map(i=>i.kind))];const summary=`${verdict}: ${changed.length} changed file${changed.length===1?'':'s'}; ${counts.critical} critical and ${counts.high} high open finding${counts.critical+counts.high===1?'':'s'}. Change risk ${changeRisk}/100, combined deployment risk ${score}/100.`;
 const{data:row,error}=await db.from('deployment_simulations').insert({workspace_id:project.workspace_id,project_id:projectId,environment,validation_id:validation.id,affected_services:affected,predicted_risk_score:score,predicted_severity:score>=70?'critical':score>=50?'high':score>=25?'medium':'low',blast_radius:blast,confidence,impact_summary:summary,rollback_plan:environment==='production'?'Keep the previous release immediately deployable; rollback on elevated error rate, latency, or failed health checks.':'Redeploy the last known-good build if validation or health checks regress.',simulation_metadata:{verdict,base_sha:baseSha,head_sha:headSha,changed_files:changed,change_impacts:impacts,change_risk:changeRisk,finding_risk:findingRisk},status:'completed',completed_at:new Date().toISOString()}).select().single();if(error)return json({error:error.message},500);return json({simulation:row,verdict,changedFiles:changed,impacts});
}catch(e){console.error(e);return json({error:'Simulation failed'},500);}});
