import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":Deno.env.get("APP_ORIGIN")||"https://sandbox-ai-app-eight.vercel.app","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-Client-Info, Apikey, apikey"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const DOMAINS=['Code','Infrastructure','DevOps','QA','Cost','Dependencies','Vendor Intelligence'];
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors}); if(req.method!=='POST')return json({error:'Method not allowed'},405);
 try{const auth=req.headers.get('Authorization')||'',token=auth.replace(/^Bearer\s+/i,'');const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const {data:{user}}=await db.auth.getUser(token);if(!user)return json({error:'Invalid or expired session'},401);const {projectId}=await req.json();if(!projectId)return json({error:'projectId required'},400);
 const {data:p}=await db.from('projects').select('id,workspace_id').eq('id',projectId).single();if(!p)return json({error:'Project not found'},404);const {data:m}=await db.from('workspace_members').select('id').eq('workspace_id',p.workspace_id).eq('user_id',user.id).maybeSingle();if(!m)return json({error:'Forbidden'},403);
 const {data:run}=await db.from('analysis_runs').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!run)return json({status:'not_run',domains:Object.fromEntries(DOMAINS.map(d=>[d,[]]))});
 const [{data:jobs},{data:findings},{data:components},{data:relationships}]=await Promise.all([db.from('analysis_jobs').select('stage,status,attempt,max_attempts,error,started_at,completed_at').eq('analysis_run_id',run.id).order('created_at'),db.from('intelligence_findings').select('*').eq('analysis_run_id',run.id).order('created_at'),db.from('application_components').select('id,component_type,name,file_path,confidence').eq('analysis_run_id',run.id),db.from('intelligence_relationships').select('id,source_component_id,target_component_id,relationship_type,confidence,evidence').eq('analysis_run_id',run.id)]);
 const domains=Object.fromEntries(DOMAINS.map(d=>[d,(findings||[]).filter((f:any)=>f.domain===d)]));return json({analysisRunId:run.id,status:run.status,createdAt:run.created_at,completedAt:run.completed_at,config:run.config||{},stages:jobs||[],applicationModel:{components:components||[],relationships:relationships||[]},domains});
 }catch(e){return json({error:e instanceof Error?e.message:'Could not load analysis status'},500)}});