import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const corsHeaders={'Access-Control-Allow-Origin':Deno.env.get('APP_ORIGIN')||'https://sandbox-ai-app-eight.vercel.app','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...corsHeaders,'Content-Type':'application/json'}});
serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});try{
 const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Authentication required.'},401);
 const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});const token=auth.slice(7);const{data:{user},error:ue}=await sb.auth.getUser(token);if(ue||!user)return json({error:'Invalid session.'},401);
 const{provider,config={},ticket={},workspace_id}=await req.json();if(!workspace_id||!ticket.title)return json({error:'workspace_id and ticket title are required.'},400);
 const{data:member}=await sb.from('workspace_members').select('workspace_id').eq('workspace_id',workspace_id).eq('user_id',user.id).maybeSingle();if(!member)return json({error:'Workspace access denied.'},403);
 const fail=(m:string)=>json({error:m},400);
 if(provider==='jira'){const{site,email,token:apiToken,projectKey,issueType='Task',assigneeAccountId}=config;if(!site||!email||!apiToken||!projectKey)return fail('Jira needs site, email, API token and project key.');const r=await fetch(`${site.replace(/\/$/,'')}/rest/api/3/issue`,{method:'POST',headers:{Authorization:'Basic '+btoa(`${email}:${apiToken}`),'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({fields:{project:{key:projectKey},summary:ticket.title,issuetype:{name:issueType},description:{type:'doc',version:1,content:[{type:'paragraph',content:[{type:'text',text:ticket.body||''}]}]},...(assigneeAccountId?{assignee:{id:assigneeAccountId}}:{})}})});const d=await r.json().catch(()=>({}));if(!r.ok)return fail(d.errorMessages?.join(', ')||JSON.stringify(d.errors||d));return json({url:`${site.replace(/\/$/,'')}/browse/${d.key}`,id:d.key})}
 if(provider==='linear'){const{apiKey,teamId}=config;if(!apiKey||!teamId)return fail('Linear needs an API key and team ID.');const q='mutation($t:String!,$d:String,$team:String!){issueCreate(input:{title:$t,description:$d,teamId:$team}){issue{url identifier}}}';const r=await fetch('https://api.linear.app/graphql',{method:'POST',headers:{Authorization:apiKey,'Content-Type':'application/json'},body:JSON.stringify({query:q,variables:{t:ticket.title,d:ticket.body||'',team:teamId}})});const d=await r.json().catch(()=>({}));if(d.errors)return fail(d.errors[0]?.message||'Linear error');return json({url:d.data?.issueCreate?.issue?.url,id:d.data?.issueCreate?.issue?.identifier})}
 if(provider==='servicenow'){const{instance,user:snUser,password}=config;if(!instance||!snUser||!password)return fail('ServiceNow needs an instance URL, user and password.');const r=await fetch(`${instance.replace(/\/$/,'')}/api/now/table/incident`,{method:'POST',headers:{Authorization:'Basic '+btoa(`${snUser}:${password}`),'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({short_description:ticket.title,description:ticket.body||''})});const d=await r.json().catch(()=>({}));if(!r.ok)return fail(JSON.stringify(d));return json({url:`${instance.replace(/\/$/,'')}/nav_to.do?uri=incident.do?sys_id=${d.result?.sys_id}`,id:d.result?.number})}
 if(provider==='slack'||provider==='msteams'){const{webhook}=config;if(!webhook)return fail(`${provider==='slack'?'Slack':'Teams'} needs a webhook URL.`);const body=provider==='slack'?{text:`:rotating_light: *${ticket.title}*\n${ticket.body||''}`}:{title:ticket.title,text:(ticket.body||'').replace(/\n/g,'<br/>')};const r=await fetch(webhook,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)return fail('Webhook rejected the message.');return json({url:null,id:'posted'})}
 if(provider==='azureboards'){const{orgUrl,project,pat}=config;if(!orgUrl||!project||!pat)return fail('Azure Boards needs org URL, project and PAT.');const r=await fetch(`${orgUrl.replace(/\/$/,'')}/${encodeURIComponent(project)}/_apis/wit/workitems/$Issue?api-version=7.0`,{method:'POST',headers:{Authorization:'Basic '+btoa(':'+pat),'Content-Type':'application/json-patch+json'},body:JSON.stringify([{op:'add',path:'/fields/System.Title',value:ticket.title},{op:'add',path:'/fields/System.Description',value:(ticket.body||'').replace(/\n/g,'<br/>')}])});const d=await r.json().catch(()=>({}));if(!r.ok)return fail(d.message||`Azure returned ${r.status}`);return json({url:d._links?.html?.href||`${orgUrl}/${project}/_workitems/edit/${d.id}`,id:d.id})}
 if(provider==='github'){const{token:ghToken,owner,repo}=config;if(!ghToken||!owner||!repo)return fail('GitHub Issues needs a token and owner/repo.');const r=await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`,{method:'POST',headers:{Authorization:'Bearer '+ghToken,Accept:'application/vnd.github+json','User-Agent':'lythouse'},body:JSON.stringify({title:ticket.title,body:ticket.body||''})});const d=await r.json().catch(()=>({}));if(!r.ok)return fail(d.message||`GitHub returned ${r.status}`);return json({url:d.html_url,id:`#${d.number}`})}
 return fail('Unknown provider.');
}catch(e){return json({error:e instanceof Error?e.message:'Ticket creation failed.'},500)}});
